### ISSUE TITLE
Use geometric algebra?

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#10]
Resources:
- https://bivector.net/
- https://www.youtube.com/watch?v=tX4H_ctggYo: video to blow your mind.
- https://github.com/enkimute/ganja.js/blob/master/codegen/python Python implementation.
- https://github.com/pygae/clifford another Python implementation.
- https://enkimute.github.io/ganja.js/examples/coffeeshop.html#pga3d_motor_orbits: demo to blow your mind.

This looks incredible, but I am not mathy enough to see if and how this can be useful in this project. I think one requisite should be that it does not make things (much) harder than linalg.

Questions:
* What would the advantages be exactly?
* Can we wrap this stuff up in an API that's actually easy to use?
* What are the implications in terms of maintainability (e.g. dependence on someone who understands this stuff)?
* Do we only need the `PGA3D` thing?

**Comment by Korijn** [comment]
Also relevant: https://github.com/pygae/clifford

I don't think this will help making our library easy to adopt though :) I'd rather not spend time on it for now

**Comment by almarklein** [comment]
> I don't think this will help making our library easy to adopt though :) 

That depends on the second question above :)  If this can be made easy to work with, it'd be a *very* powerful tool.

**Comment by Korijn** [comment]
I think that's a big if. :)

**Comment by almarklein** [comment]
I made a start: https://github.com/pygfx/pga3

I think this could work, but there are a few open questions:
* So far I have not yet seen scaling transforms. Maybe because they cannot be described? If not, is that a bad thing, or could we implement a `pre_scale` property to scale each world-object (but not its children)?
* If we don't allow scaling in our transforms, then we could also represent transforms as a translation plus a quaternion, or using a dual quaternion. Though with a minor optimization, a PGA3 transform would have the exact same performance as a dual quaternion.
* I'm pretty sure its possible (because it's done [here](https://github.com/jeremyong/Klein)), but I do not know yet how to create a 4x4 matrix from a pga3 transform.

**Comment by almarklein** [comment]
On scaling: https://discourse.bivector.net/t/scaling-with-pga/43/3 -> no scaling, but this restriction may be a good thing?

**Comment by almarklein** [comment]
On the 4x4 matrix: https://discourse.bivector.net/t/generating-a-4x4-transformation-matrix-from-pga3d/110/6

**Comment by almarklein** [comment]
In pygfx we have the following uses for a linalg system:

1. Describe points, lines, planes, etc. and do operations on these to e.g. find intersections etc.
2. Do these for a batch of objects at the same time in one call (vectorized with numpy for performance).
3. Describe the scale/rotation/translation of world-objects.
4. Compose the total transform of a world-object with that of its parents (in the scene graph).

For (1) geometric algebra would be awesome. I suspect we could make (2) work as well. For (3) we have a bit of a problem, because geometric algebra cannot describe non-uniform scaling (see link in previous post). This may be overcome by doing a pre-scaling. However, this means that we cannot describe a transform that is the composition of two world-object transforms.

This means that we either:
* Accept that we don't have non-uniform scaling - one can use the geometry for this.
* Use a pre-scaling that only applies to the object and not it's children.
* Accept that we can't do (4), and chain the transforms of the scene graph in the shader.

**Comment by almarklein** [comment]
We can close this in favor of #40
