### ISSUE TITLE
Flipping normals towards viewer in fragment shader

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#105]
The faceForward trick that we use to flip normals in the mesh shader only works if the light comes from (about) the same direction as the eye vector. Otherwise, normals on faces that that are near-parallel to the eye vector can flip, affecting how they're lit, causing bright and dark artifacts at the edges of objects.

This means we have to make sure that all normals are correct in the first place. Not sure what to do with surfaces that can be seen from two sides, such as planes and e.g. the Klein bottle.

I also wonder if I might be overlooking something that still allows flipping normals ...

**Comment by almarklein** [comment]
ref https://github.com/vispy/vispy/pull/2091

**Comment by Korijn** [comment]
Is there really a need for this to be dynamic? You should be able to configure:

* MeshMaterial.side = Front|Back|Double
* MeshMaterial.frontFacing = CW|CCW

And you just provide normals on the geometry.

What more could you need?

**Comment by Korijn** [comment]
I wasn't aware of this flip trick in the shader! IMHO it should be removed. The designer of the world/scene should be in control.

**Comment by almarklein** [comment]
Well, without it, a surface has an outside (which is lit correctly), and an inside (which is not). This means that in cases where you want both the inside and outside to be lit as expected, you're out of luck. One example is the Klein bottle, but a simple rectangular plane would too.

**Comment by Korijn** [comment]
I'm misunderstanding perhaps. My point is: we should not _need_ any _tricks_. All required information should be available.

In GLSL, you have access to the boolean flag [`gl_FrontFacing`](https://khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FrontFacing.xhtml) which you can use to flip normals when you are shading a back-face. Is this not available to us?

**Comment by almarklein** [comment]
> In GLSL, you have access to the boolean flag gl_FrontFacing 

Ah, right. Yes I think I was thinking about this too hard...

**Comment by Korijn** [comment]
It's available in WGSL too as `front_facing`: https://gpuweb.github.io/gpuweb/wgsl/#builtin-variables

**Comment by almarklein** [comment]
Some notes for the record and my ow understanding.

You *can* use the normal and view vector to flip normals that point away from the viewer with

```wgsl
normal = faceForward(normal, -normal, view);
```

However, this is unstable when the two vectors are (close to) orthogonal, as in the image below. This still does not have to be a problem if the light comes from almost the same direction as the eye. However, if it comes from the side, it's the difference between highly lit (with specular highlights) and unlit.


I wonder if the instability occurs because perspective is not correctly taken into account or something.

But it does not matter, because the GPU can simply *tell* us whether the face is
