### ISSUE TITLE
Simple viewer shortcut

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#107]
What I think would be supremely valuable for prototyping and debugging purposes, is a simple viewer UI (based on ...Qt?) that can be launched with a simple single function.

For example... you're in the middle of some code, your scene is in a certain state, and you want to debug it at that point by inspecting it visually. Just write `pygfx.show(scene)` (or something like that) and a little window pops up with its own independent canvas, renderer and a default orbit camera with some simple interaction to control it.

What do you think?

**Comment by almarklein** [comment]
I'm not sure if I understand the intended benefits. I assume that the debug-scene would somehow show more information about the state than the original visualization does?

**Comment by Korijn** [comment]
The idea is that you can drop a line anywhere in your codebase, to inspect a scene in whatever intermediate state it is in at that point.
