### ISSUE TITLE
Make sure that the docs are complete

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#113]
Complete as in all public classes, methods, and properties have a docstring that is complete.

Let's track per subpackage:
* [x] cameras
* [x] controls
* [x] geometries
* [x] helpers
* [ ] linalg
* [x] materials
* [x] objects
* [x] renderers -> also document the "common functions" that we make available internally.
* [x] resources
* [x] utils (I think we only have utils for private use)

**Comment by almarklein** [comment]
I think we can leave this open to remind ourselves on the parts that are not yet documented.

**Comment by almarklein** [comment]
Closing! The only remaining point is linalg, but that will get its own docs, I presume.

**Comment by Korijn** [comment]
See https://github.com/pygfx/pylinalg/issues/3
