### ISSUE TITLE
Write a guide in the docs

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#114]
Topics:

* [x] Installation.
* [x] Explain getting started / minimal example.
* [x] Better explain world objects, materials, geometries.
* [x] Explain running in Jupyter.
* [ ] ~~Explain buffers and textures.~~ See #19
* [x] Explain renderers.

**Comment by FirefoxMetzger** [comment]
I think we now have point 2 in the above list: explain getting started/minimal example (see https://github.com/pygfx/pygfx/pull/371)
