### ISSUE TITLE
WorldObject.visible behavior

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#123]
It looks (to me) like properties on a Material apply to the objects that the material applies to, whereas properties of a WorldObject apply to that object and is children (and their children). This is at least the case for transforms. Should this apply to `.visible` too? And does it now?

**Comment by Korijn** [comment]
You can try it right here: https://threejs.org/editor/

**Comment by almarklein** [comment]
> I don't think that is how we have implemented this in wgpurenderer right now.

Nope.
