### ISSUE TITLE
Effect on culling on other materials

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#135]
I made sure that culling behaves correctly for meshes, but what about other materials? Does culling even make sense for e.g. lines?

**Comment by Korijn** [comment]
I don't think it makes any sense for lines or points... right?

**Comment by almarklein** [comment]
Indeed, threre's no front or back to define. So maybe this should be moved to the MeshMaterial.

**Comment by almarklein** [comment]
Not sure what I was thinking when I wrote this, but culling (`material.side`) is already specific to the mesh material ☺️
