### ISSUE TITLE
Switch to poetry

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#137]
Since pygfx is a pure python library, we can easily switch to poetry. Would you be open to it @almarklein ? I can handle changing over CI etc but I'm not sure how thrilled you are about this. :)

It's probably also more accessible for guest contributors since it's quickly becoming the standard environment & dependency management tool in the python ecosystem.

**Comment by almarklein** [comment]
I've only played with poetry a bit so far. What would switching imply? E.g. what changes for CI?

**Comment by Korijn** [comment]
Well, first you drop setup.py and instead use pyproject.toml.

Then you use `poetry lock` to create a `poetry.lock` file.

Finally you create your virtual env and run things with poetry. So, `poetry install` creates a virtualenv using the lockfile. Commands are run using `poetry run flake8`, etc.

Creating a wheel is `poetry build` (puts it in a `dist` folder).

So in CI you start with `pip install poetry` and then you use the above commands to do things as you usually would. That's it really.

**Comment by almarklein** [comment]
My only worry is that we'd be forcing poetry on everybody how wants to contribute to pygfx (is it?). It may be simpler, but its another thing to learn for newcomers. 

(My dirty little secret is that I run (almost) all my projects in a single Python env, haha)

Anyways, open to giving it a shot.

**Comment by Korijn** [comment]
That is indeed a dirty little secret... man!

**Comment by berendkleinhaneveld** [comment]
And that is exactly why poetry would be a Good Idea (tm) ;)

**Comment by almarklein** [comment]
I don't think this is needed. The pyproject should be enough to set dependencies, pin them as needed, and downstream libs or end-users can install/pin pygfx with whatever package manager they want ...
