### ISSUE TITLE
Improve API of Controls (Orbit) to better support saving and restoring state

### ISSUE THREAD

**Issue by berendkleinhaneveld** [pygfx/pygfx#148]
OrbitControls currently takes `eye`, `target` and `up` as init parameters, but not all those values are actually updated. So saving and restoring state of a camera and controls is not as straight-forward as it could be.

Would be nice to try and make the API for the parameters a bit more symmetric: use the same parameters as input and output.

**Comment by Korijn** [comment]
I propose we just mimic the API from three.js: https://threejs.org/docs/index.html?q=Controls#examples/en/controls/OrbitControls

* saveState() stores a snapshot of the camera/controller's current state
  * a snapshot is comprised of the target, position and zoom
* resetState() restores the last snapshot

**Comment by almarklein** [comment]
I think this should work?
* `savestate` stores the internal state and also returns an opaque object that represents the state.
* `restorestate` restores the given state, or the internal state if none is given.

**Comment by Korijn** [comment]
Exactly
