### ISSUE TITLE
Mesh per-face coloring

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#152]
Proposing to add something like `geometry.face_colors` that specifies a color for each triangle (as defined by the indices). Implementing per-face colors is normally not trivial, but because of how we render meshes, we have access to the face index :)  so this is easy to implement.

**Comment by ivoflipse** [comment]
Here's an example of what I've done in the past
![2016-11-10 11_35_00-Figure 6~2.png](https://user-images.githubusercontent.com/485186/135750741-a69417ea-b745-44e3-b7b4-5ef7f6338ed2.png)

It's the distance between 2 meshes drawn on top of one of the two meshes

**Comment by Korijn** [comment]
But that's vertex coloring, not face coloring

**Comment by almarklein** [comment]
In #529 face colors are implemented, but we should take some time to think about the API.

cc @sharon92

### Current color modes

* uniform color (`material.color`).
* mapped via per-vertex texcoords (`geometry.texcoords` is sampled with vertex index, and result used to sample in `material.map`).
* vertex colors (`geometry.colors` is sampled with vertex index).

API-wise, vertex colors are only activated when `material.vertex_colors` is set to `True`. The colormap mode is automatically activated when `material.map` is not `None`. It is assumed that there are `texcoords` on the geometry (will error if not).

### New face color mode(s)

Ideally, I'd like to add:

* mapped via per-face texcoords (`geometry.texcoords` is sampled with face index, and result used to sample in `material.map`).
* face colors (`geometry.colors` is sampled with face index).

Some options for the API that I could think of:

#### Option 1
We could introduce a `material.face_colors` property, but then we can't distinguish between the different colormapped modes.

#### Option 2

We could introduce `material.color_mode` to explicitly set the mode ("uniform", "map", "vertex", "face-map", "face").

Perhaps including mode "auto" for backwards compatibility, that switches between "uniform" and "map" depending on whether `material.map` is present. 

#### Option 3

We could decide whether to use `geometry.colors` as vertex or face colors based on the size of the buffer: if it matches the number of vertices, they are vertex colors, if it matches the number of faces, they are face colors. Same for texcoords. We can then rename `vertex_colors` to `geometry_colors`.

I thought it might feel a bit too magical at first, but it is easy to document this behavior and JustWorks.

@Korijn thoughts?

**Comment by Korijn** [comment]
I'm inclined to go with color_mode (option 2) as it makes it  explicit and obvious. Also maybe it allows you to set a map and a color and then switch between them at runtime?

**Comment by almarklein** [comment]
Agreed. The explicitness is nice.

> and then switch between them at runtime?

Right, there could be a uniform that sets what color to actually use, so you can switch the color mode without recompiling the shader! Could even blend colors with something like `color_mode = "uniform*0.4+face*0.6"` 🤔 But let's not do a mini DSL right now 😅.

**Comment by almarklein** [comment]
Summarizing, starting out with a simple implementation (no hot switching).

* A new prop `MeshAbstractMaterial.color_mode`, simply sets a `._store.color_mode`.
* The `MeshAbstractMaterial.vertex_colors` should be deprecated. We keep it around for a bit and make it set `color_mode` and print a warning.
* The mesh shader sets up the path to calculate color based on `color_mode` (and checks whether the `color_mode` is possible, e.g. is `geometry.colors` available and of the correct size.

**Comment by almarklein** [comment]
Mmm, our point and line materials should probably receive the same treatment ...
