### ISSUE TITLE
The geometry abstraction

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#176]
## Problem

A thing that bothers me a bit about our architecture is that the geometry abstraction is sometimes confusing.

For example in #175, the `width` and `color` are on the material, which means that they are details about how the points are rendered. But when a user specifies the `width` or `color` per point, its on the geometry, which means that suddenly it's data intrinsic to the object.

(Another thing is that we use properties everywhere, but on the geometry we just set attributes as needed. But let's discuss that later to prevent this getting too big.)

## The purpose of geometry

In my words:

1. Group the "intrinsic data of the object" in one place.
2. To make it easy to create multiple objects with the same geometry (instead of having to specify positions, normals, texcoords, indices, etc). 
3. (extending 1) To allow the rule that every property on the `WorldObject` also affects its children.

For (2) there are other ways to make that work. But for me (3) is the best selling point.

## Options

Some thoughts (not mutually exclusive):

### We should better define what geometry means and what its purpose is

And document it in the docstring and guide.

###  We could rename "geometry"

Or is geometry ok? Could you consider colors geometry? The name "data" is nice and short, but also *very* generic. One strong point in favor of geometry is that its consistent with ThreeJS.

### We could allow providing data in the object constructor

Resulting in less verbose code:

```py
points1 = gfx.Points(positions=..., colors=... material=...)
```

### We could make the helpers create an object instead of geometry

Instead of :
```py
cube1 = gfx.Mesh(geometry=gfx.CubeGeometry(2, 2, 2), material=...)
cube2 = gfx.Mesh(geometry=cube1.geometry, material=...)
```
we do:
``` py
cube1 = gfx.Cube(2, 2, 2, material=...)
cube2 = gfx.Mesh(geometry=cube1.geometry, material=...)
```

This makes for code that's somewhat easier on the eye, especially for newcomers.

### We could introduce a clone method
``` py
cube2 = cube1.clone(material=...)
```

Similarly we could have a clone method on the material and geometry.

**Comment by Korijn** [comment]
I'm sorry but I strongly disagree with changing this abstraction. It's very simple and powerful, which is why so many people have gotten the hang of ThreeJS. If anything we should document it more clearly.

I also noticed that you proposed the concept "helpers create an object" that we already have in place actually, and so does ThreeJS. Perhaps you just haven't gotten used to it yet. See https://github.com/pygfx/pygfx/tree/main/pygfx/helpers and https://threejs.org/docs/?q=helper

**Comment by almarklein** [comment]
I think I was not clear about my intentions. I agree that generally speaking the abstraction is good. However, I observe that the geometry sometimes causes confusion, and that to me the abstraction sometimes fails (colors are strictly speaking not geometry), and I hope we can improve this. I've proposed a few options as possible directions, not as a full package of what I think we should do.

Perhaps we should start with the definition of its purpose, otherwise this might become a welles-nietes game :)  Do you agree with how I stated the purpose?

**Comment by almarklein** [comment]
This is now resolved.
