### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#18]
There might be something like a visvis2, but it would be build on top of what we're building here. So let's find a better name.

I'm not so sure about "three.py" anymore; we borrow a lot of ideas, but naming it this way may suggest more similarities than there are?

**Comment by Korijn** [comment]
I have two suggestions!

* radiant
* bedazzled

**Comment by almarklein** [comment]
I like radiant :)

**Comment by Korijn** [comment]
Let's do it? :)

**Comment by Korijn** [comment]
Seems that it's taken :(
https://pypi.org/project/radiant/

**Comment by almarklein** [comment]
* Vidi / Vidas (esperanto verb for "to see" / "see")
* sceno ("scene" in esperanto ;))

**Comment by Korijn** [comment]
pyoptic
pynoculars
prysma
photon

**Comment by almarklein** [comment]
p3

**Comment by Korijn** [comment]
- [renderlib](https://pypi.org/project/renderlib/)
- [wgpu-graph](https://pypi.org/project/wgpu-graph/)
- [pygfx](https://pypi.org/project/pygfx/)
- [gfx.py](https://pypi.org/project/gfx.py/)
- [tranquil](https://pypi.org/project/tranquil/)
- [poundcake](https://pypi.org/project/poundcake/)

**Comment by almarklein** [comment]
Current consensus: `pygfx`  as in "pygraphics" with `pip install pygfx`  and `import pygfx as gfx`

**Comment by Korijn** [comment]
How would you feel about putting wgpu-py, pygfx and python-shader under a "pygfx" organization? I have some stuff I'd like to contribute on my own later as well, and I'd also like to split off the linalg module to its own package.

**Comment by almarklein** [comment]
I think that would make a lot of sense!
