### ISSUE TITLE
Text rendering

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#20]
# Text rendering

An overview of our options. Latest update 16-11-2021.

## Goals

I think our goal should be:

* Aim for high quality text rendering (though not necessarily perfect).
* Make sure that there is a default font that looks good and is complete and always available.
* Provide support (one way or another) for all languages, including CJK.
* Preferably support user-provided fonts, so graphs in papers can be publication-worthy quality with a uniform style.
* Preferably an approach where we can start simple and improve on with further steps.

### Leveraging a GUI toolkit

We could leverage the text support of e.g. Qt to create text overlays. We have an example for this in pygfx.

### Bitmaps

Historically, fonts are rendered using glyph bitmaps that match the screen resolution. All glyphs in use are put into an atlas: a large image/texture that has all glyphs packed together.

A downside is that the bitmaps should match the screen pixels, so the bitmaps are font-size specific, and rendering glyphs at an angle is not possible without degrading quality.

### SDF

In 2007 Chris Green from Valve [published](https://steamcdn-a.akamaihd.net/apps/valve/2007/SIGGRAPH2007_AlphaTestedMagnification.pdf) an approach that uses scalar distance fields (SDF) to render glyphs. This approach makes it possible to create a special kind if bitmap (which encodes distances to the edge instead of a mask), that can then be used to render that glyph at any scale and rotation. This was a big step in games, but also for generic visualization.

There are variations on the way to calculate an SDF. The current industy standard seems to be [anti-aliased euclidian distance transform](https://weber.itn.liu.se/~stegu/aadist/edtaa_preprint.pdf).

### MSDF

Around 2015, Viktor Chlumsky [published](https://github.com/Chlumsky/msdfgen/files/3050967/thesis.pdf) his Master thesis, in which he proposes a method for a Multi-channel Signed Distance Field (MSDF). The key contribution is that directional information is encoded too, making is possible to produce sharp corners. It produces better results than normal SDF, at a smaller scale. The fragment shader is changed only slightly, causing just a minor performance penalty.

### Glyphy

The [Glyphy](https://github.com/behdad/glyphy) C library converts bezier curves to arcs and then calculates the signed distance to those arcs in the shader, producing better results than normal SDF. It's not well documented, but is by the author of Harfbuzz ...

### Vector rendering

It's also possible to render the Bezier curves from the glyphs directly on the GPU. See e.g. http://wdobbie.com/. This approach seems to require some preprocessing to divide the bezier curves into cells. If this can be changed to create an atlas (i.e. each cell is one glyph) then this may be a feasible approach for a dynamic context like ours. Also see [Slug](https://sluglibrary.com/), which looks pretty neat, but is not open source and covered by a patent.

Also see this fairly simple approach: https://medium.com/@evanwallace/easy-scalable-text-rendering-on-the-gpu-c3f4d782c5ac It uses a prepass to calculate the winding number for the rough shape, then composes the final shape and applies aa in a fragment shader. A disadvantage (for us) is that it needs multiple passes, making it harder to fit into our renderer, I think. 

### How visvis does text

https://github.com/almarklein/visvis/tree/master/text

Visvis produces glyphs on the fly using FreeType. Freetype is available by default on Linux, on Windows it must be installed. If FreeType is not available, visvis falls back on system that uses pre-rendered fonts. Visvis also ships with FreeSans, so there is always a good sans font available. Further, it can make use of other fonts installed on the system.

The rendered glyps are on a fixed resolution and put in an atlas texture. When rendered, the glyph is sampled using a smoothing kernel, giving reasonable results at multiple scales.

Further, visvis includes a mini-SDL to create bold, italic, and math symbols using escaping with backslash.

### How vispy does text

https://github.com/vispy/vispy/tree/main/vispy/util/fonts and https://github.com/vispy/vispy/tree/main/vispy/visuals/text

Vispy produces SDF glyphs on the fly. It first gets a glyph bitmap using FreeType (via Rougier's FreeType wrapper) on Windows and Linux, and Quartz on MacOS. The bitmap is then converted to an SDF using either the GPU or Cython. It can use most fonts installed on the system. The code to list and load fonts is platform specific.

The SDF glyphs are packed into an atlas texture, and rendered using regular SDF rendering. 

### How Matplotlib does text

Unless I'm mistaken, they use the GUI backend to render text.

## Discussion

SDF rendering already provides pretty solid results and is widely used. MSDF seems like a very interesting extension that may make it possible to create better results with smaller SDF sizes. Whether this is true depends also on the complexity of the glyphs - it has been reported that it does not provide much advantage for e.g. Chinese glyphs. We'd need tests to visually judge what glyph sizes are needed in both approaches.

In terms of dependencies, to create SDF we can get away with just FreeType to create the bitmaps, plus steal some code from vispy to generate the SDF. For MSDF there is that one project, but its not that actively maintained, so at this point it may be a liability. It may be worth investigating if its possible to generate an MSDF from a bitmap.  

Vector rendering seems to be popular lately. It produces better results, but is more complex and less performant than SDFs. Further you may need a bitmap fallback for high scales. There is also the question of how to generate the vector-data from the font files.

If you want to do render text perfectly, you should take into account kerning, ligatures, combinatory glyphs, left-to-right languages, etc. We can do kerning, but the rest is way more complex. Tools that handle these correctly are e.g. Slug and [Harfbuzz](https://harfbuzz.github.io).  The latter might be feasible to use - there are multiple Python wrappers.

## More details obtaining a glyph

I imagine that somewhere in our code we have a method `create_glyph(font, char)` that returns an SDF/MSDF/bezier-curve-set and some metadata. We can place this info in an atlas texture together with other used glyphs. Now, how does this function work? 

*The below more or less assumes SDF / MSDF, but similar questions apply to the Bezier-based rendering.*

#### Using prerendered glyph maps

We could produce prerendered glyph atlas, so `create_glyph()` samples one glyph from that (offline) atlas and to put it in our GPU atlas. That way, the dependencies for rendering the glyphs are only needed by devs, and not the users.
See e.g. https://github.com/Chlumsky/msdf-atlas-gen A disadvantages is that the font and available characters are limited by what atlasses we chose to ship. If we'd ship CJK fonts, that would grow the package size a lot, so maybe we'd need a `pygfx-cjk-fonts` or something.

Some measurements for rendering all chars from a font:

* OpenSans   ->  1011 glyphs -> 1.5MB @ 32   0.5MB @ 16
* FreeSans   ->  4372 glyphs -> 7MB @ 32     2.3MB @ 16
* NotoSans   ->  2300 glyps  -> 3.5MB @ 32   1.1MB @ 16
* NotoSansJP -> 16735 glyps  ->   ??          15.1MB @ 16

This shows that with 16x16 MSDF glyphs, the atlas is about 3x the size of the .ttf file. Or 9x for 32x32. Not bad, but I don't now yet whether 16x16 is enough, especially for the more complex glyphs in CJK fonts.

### Using a tool to render glyph on the fly

If we can produce the SDF glyph from the fontfile at the user, then support for all languages, and custom fonts is obtained. The cost is that we need a dependency for this.  

One option is FreeType. There is Rougiers https://github.com/rougier/freetype-py which provides binaries for multiple platforms (but not MacOS M1 or Linux aarch64 yet). IIUC freetype can render a glyph bitmap at any scale, but to create an SDF we need to do some extra work ourselves. I am not sure if a MSDF is feasible, because you'd miss the vectors, or can we do edge detection on a high-rez glyph to find the orientation?

Another option is https://github.com/Chlumsky/msdfgen. We'd need to build and distribute the code for all platforms that we support. Since this code is not *that* actively maintained, this feels a bit tricky.

## Typesetting

Typesetting is the process of positioning the quads that contain the glyphs. This includes kerning (some combination of glyhs have a custom distance). Also inclded are justifcation, alignment, text wrapping etc.

I think its not too hard to do this in pure Python, though existing solutions may make things easier. Examples are [Slug](https://sluglibrary.com) and [Harfbuzz](https://harfbuzz.github.io), but these are not feasible dependencies. I don't know of any Python libraries for typesetting.

For the kerning we would need the kerning maps. FreeType can provide this info. I *think* that msdfgen also provides it in the CSV/JSON metadata.

## Formatting

We should consider a formatting approach so users can create bold/italic text etc. Visvis uses escaping, but maybe an micro-HTML-subset would be nicer. Or something using braces. Or maybe its out of scope. This is definitely something that we can do *later*.

## Fonts of interest

* OpenSans is a pretty nice and open font.
* FreeSans is a GNU project that aims to cover almost all Unicode, except CJK.
* Noto is a family of over 100 fonts that aims to have full Unicode coverage. It basically has a font for each script. The plain NotoSans has over 3k glyphs and with support for Latin, Cyrillic and Greek scripts it covers 855 languages.

**Comment by almarklein** [comment]
We added textrendering using text overlays with Qt, as an example, in #56

**Comment by Korijn** [comment]
When, eventually, we'll do SDF based text rendering, we can probably leverage this tool to do some of the preprocessing for us: https://github.com/Chlumsky/msdf-atlas-gen

**Comment by Korijn** [comment]
I guess there are three parts to this:

* Creating glyph maps
* Rendering glyphs on quads
* Typesetting strings (positioning quads)

I have been looking for existing solutions for that third part but I haven't been able to find much. Ideally we can find something that is implemented in C(++) or Rust and has Python wrapper wheels available on pypi. But I'm not aware of any; do you happen to know any?

**Comment by almarklein** [comment]
With the 3d part you mean e.g. the kerning etc. right? In visvis I used Freetype for  step 1 and 3, and it looks like vispy does the same, via https://github.com/rougier/freetype-py.

**Comment by Korijn** [comment]
> With the 3d part you mean e.g. the kerning etc. right? In visvis I used Freetype for step 1 and 3, and it looks like vispy does the same, via https://github.com/rougier/freetype-py.

That's right. I was just thinking there should be something a little more high level than freetype; it provides per-glyph info, but you still have to implement line wrapping, justification and alignment etc yourself. I was hoping there are engines available for that!

**Comment by almarklein** [comment]
> you still have to implement line wrapping, justification and alignment etc yourself. I was hoping there are engines available for that!

Yes, that part is done in Python :)  it's not rocket science, but if there's something to make this easier than this would be great ...

**Comment by Korijn** [comment]
> > you still have to implement line wrapping, justification and alignment etc yourself. I was hoping there are engines available for that!
> 
> Yes, that part is done in Python :) it's not rocket science, but if there's something to make this easier than this would be great ...

Well, if I think about the difference between e.g. word, a browser, and latex typesetting, there's quite some ways to go. I figured it would be awesome if we could just drop in an optimized typesetting engine :) but we can start simple, of course.

**Comment by almarklein** [comment]
I've done some digging and organized my understanding of our options in the top post.

The first thing we should do, I think, is agree on the goals. I made a start with that, but this is up for discussion. One of the goals that affects our chosen approach, is that (I believe) we should (at least eventually) support CJK fonts, and preferably *any* user-provided fonts.

I was initially enthusiastic about the idea of using prebuild MSDF atlasses, and some tests seemed to suggest that this is quite feasible for common fonts. However, to support CJK fonts, we'd need to provide huge atlasses, e.g. via additional packages. And users are limited to the fonts that we provide atlasses for.

Therefore I'm now inclined to use the good old FreeType to generate bitmaps and generate an SDF from that, similar to what vispy does. In the future we could investigate if we can implement MSDF this way too.

I have some more concrete ideas, but it probably better to make sure we're on the same page before diving deeper.

**Comment by almarklein** [comment]
Here's a little Python script I used to call `msdf-atlas-gen`. (I already lost it once when my computer died last week, so I figured I'd post it here.)

```py

import os
import subprocess

import freetype


def get_codepoints_in_font(fontfilename):
    face = freetype.Face(fontfilename)
    return [code for code, index in face.get_chars()]


def generate_msdf_atlas(fontfilename, size=32):

    # Write charset file containing all codepoints in the font
    codepoints = get_codepoints_in_font(fontfilename)
    with open("charset.txt", "wt") as f:
        f.write(" ".join(str(i) for i in codepoints))

    print("Number of codepoints:", len(codepoints))

    exe = "msdf-atlas-gen.exe"

    subprocess.check_call([exe,
        "-font", fontfilename,
        "-charset", "charset.txt",
        "-size", str(size),
        "-csv", "atlas.csv",
        "-format", "bmp",
        "-imageout", "atlas.bmp",
    ], cwd=os.getcwd())


if __name__ == "__main__":

    # fontname = "FreeSans.ttf"
    # fontname = "OpenSans-Regular.ttf"
    fontname = "NotoSans-Regular.ttf"
    # fontname = "NotoSansJP-Regular.otf"

    generate_msdf_atlas(os.path.abspath(fontname), 32)
```

**Comment by Korijn** [comment]
You might find this MEP interesting, it contains lots of insights and useful references: https://github.com/matplotlib/matplotlib/blob/f6e0ee49c598f59c6e6cf4eefe473e4dc634a58a/doc/devel/MEP/MEP14.rst#L49

**Comment by Korijn** [comment]
> I've done some digging and organized my understanding of our options in the top post.

Great overview!!

> Therefore I'm now inclined to use the good old FreeType to generate bitmaps and generate an SDF from that, similar to what vispy does. In the future we could investigate if we can implement MSDF this way too.

Good, let's start "simple". :) It's complicated enough as it is just getting the dependencies sorted.

> I have some more concrete ideas, but it probably better to make sure we're on the same page before diving deeper.

Definitely.

Regarding bitmap -> SDF conversion, I believe the [anti-aliased euclidian distance transform](https://weber.itn.liu.se/~stegu/aadist/edtaa_preprint.pdf) is the "optimal" method currently in the industry. Again, not something we have to do right now, we can always improve later, as it wouldn't impact the API for users.

That's something I think is missing from this discussion: what do we envision the API for users to look like?

There are some libraries for Three.js that add (M)SDF text rendering capabilities, including typesetting etc:

* https://github.com/Jam3/three-bmfont-text
* https://github.com/felixmariotto/three-mesh-ui
  * Usage example: https://github.com/felixmariotto/three-mesh-ui/wiki/Getting-started
* https://www.npmjs.com/package/troika-three-text

**Comment by almarklein** [comment]
> You might find this MEP interesting,

Wow, I did not realize how similar their needs are to ours. Sounds like it could be a separate lib that more projects can benefit from ... or is that naive thinking?

> That's something I think is missing from this discussion: what do we envision the API for users to look like?

To be honest, I think that's a different discussion worthy of a separate issue :)

**Comment by Korijn** [comment]
> > You might find this MEP interesting,
> 
> Wow, I did not realize how similar their needs are to ours. Sounds like it could be a separate lib that more projects can benefit from ... or is that naive thinking?

That's sort of the tagline of harfbuzz etc no?

**Comment by Korijn** [comment]
I opened a [PR to add M1 wheels to freetype-py](https://github.com/rougier/freetype-py/pull/139).

**Comment by Korijn** [comment]
And [aarch64 wheels for Linux are now also available for freetype-py](https://github.com/rougier/freetype-py/pull/144).

**Comment by almarklein** [comment]
I'm not sure if I mentioned this before, but freetype can generate an SDF nowadays. That makes things easier.

**Comment by Korijn** [comment]
Yes; although it's the most basic kind of SDF, not sure if it's adequate for our needs.

**Comment by almarklein** [comment]
https://tympanus.net/codrops/2019/10/10/create-text-in-three-js-with-three-bmfont-text/

**Comment by Korijn** [comment]
Looks impressive; can we start with defining a simple first step?

**Comment by almarklein** [comment]
Yes, we can start with the Latin shortcut :)  Maybe having stubs for the other steps, or at least have an implementation that makes it easy to add steps later.

**Comment by almarklein** [comment]
That step is basically this: get the Unicode ints, look the glyph up in the font file, generate an SDF from the glyph, put it in an atlas to upload to the GPU (and also texture coords and positions).

Then we can add kerning which will change the positioning for some letter combinations. Or shaping, which will produce a different series of glyphs and positions. Alignment and justification etc. only influences positioning.

**Comment by Korijn** [comment]
Are we going to leverage harfbuzz or libraqm or something of the sort for shaping? Do we need to start looking at the availability of python bindings?

Also, I think freetype-py hasn't had a release yet since the SDF capabilities were added. Rougier indicates he could use help prepping release notes.

**Comment by almarklein** [comment]
Yes, for shaping I won't try to do that ourselves :)   I took a quick look the other day, and there are several harfbuzz wrappers on Pypi. I haven't looked at quality/stability/activity of these projects yet.

Anyway, I plan to accommodate for shaping, but skip the step at first, so we can add it in later.

**Comment by almarklein** [comment]
Just saw this: https://twitter.com/tha_rami/status/1524448087581806592
