### ISSUE TITLE
Proposal: automatic varyings

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#200]
This is a proposal / motivation for a solution that is part of #198.

## Background

In #198 I'm working on implementing multiple render passes. This poses a problem regarding how our shaders are written, because:
* We don't want users (people who write shaders) to have to write a shader for each render pass.
* The fragment output differs per render-pass, and even per blending mode; this detail must be hidden from the user.
* Only the first render-pass has a picking output. We would want to disable the varyings, because we [cannot rely](https://github.com/gfx-rs/naga/issues/1509) on the compiler to do this. That means we also want to have render-pass specific vertex-shaders. And also specfic varying structs. That sounds like a lot of templating :(
* We don't want to complicate writing shaders with whimsical rules specific to pygfx.

I've thought about (many) different ways to solve this, and I think the approach below should be part of the solution.

## Proposal: automatic varyings

The idea is to add a post-processing step to the WGSL (after templating has been applied). In this step we parse and modify the shader. In short:
* User does *not* define the struct for the varyings.
* We detect what varyings are assigned,  and which are read.
* We comment-out assignments of varyings that are not used.
* We auto-generate the exact struct that's needed.

Note: With a varying being assigned, I mean that its set/written in the vertex shader. With a varying being used, I mean it's get/read, usually in the fragment shader.

## How does this help?

For the OIT, this means enabling/disabling the passing of the picking varying to the output, can be done with templating in a single point (the fragment shader) and everything just works *and* is efficient.

## Why does this work?

The varyings struct will only contain varyings that are actually used in the fragment shader. Because the assignments are commented out, any logic used to generate the values for that varying are easily identified as unused - dead code elimination is a relatively simple optimization that we can assume nearly all driver-specific compilers to do.

A more detailed note on that is that the dead code elimination can be done at a very early stage. Even Naga could do it. If instead the struct included unused varyings and the vertex shader also set these unused varyings, the optimization to drop varyings can only be made when the pipeline is assembled.

## Other benefits

Some time ago, we added support for vertex colors to meshes. Right now, templating is used in 3 places to enable/disable this. We can reduce this to one place (the fragment shader). So it keeps our shaders cleaner!

## An example

Instead of doing:

``` wgsl

struct Varyings {
    $$ if has_color
    [[location(0)]] color : vec4<f32>;
    $$ endif
    [[builtin(position)]] position : vec4<f32>;
};

fn vs_main(in: VertexInput) -> Varyings {
    var varyings : Varyings; 
    ...
    $$ if has_color
    varyings.color = some_color
    $$ endif
}

fn fs_main(varyings : Varyings) {
    ...
    $$ if has_color
    let color = varyings.color;
    $$ else
    let color = u_material.color;
    $$ endif
}
```

We can write this:

``` wgsl

fn vs_main(in: VertexInput) -> Varyings {
    var varyings : Varyings; 
    ...
    varyings.color = vec4<f32>(some_color);
}

fn fs_main(varyings : Varyings) {
    ...
    $$ if has_color
    let color = varyings.color;
    $$ else
    let color = u_material.color;
    $$ endif
}
```

## Details

* Note how in the assignment the `vec4<f32>` is explicitly cast. We need this in order to obtain the type.
* Yes, this also works if varyings are set/used in functions other than vs_main and fs_main.
* Because we may comment it, we force varying assignments to be on a single line. 
* Inside vs_main, only assignments are allowed (no gets), to avoid unintended using a varying.
* We also warn if a varying is used but not assigned.

## Implementation

I've implemented this in #198, see https://github.com/pygfx/pygfx/pull/198/commits/da44edb6648bbcbedfd7f2dc20af3c794d3a18f9. The function to resolve the varyings is about 130 lines, which seems reasonable.

**Comment by Korijn** [comment]
I would need a birds-eye overview of the shader templating pipeline to be able to review and respond to this adequately. There's strings assembly, there's jinja templating, and now there's regex post-processing too, I'm losing track of how this thing works. :)

> Note how in the assignment the vec4<f32> is explicitly cast. We need this in order to obtain the type.

This to me seems like a strong argument _against_ this approach. At least right now, I think that it should be possible for users to write shaders. Making it necessary for users to be conscious of the requirements of a shader engine post-processing step is making it too hard, I think.

**Comment by almarklein** [comment]
> I thought you meant the GLSL needs it, but it's a regex that captures the type from the line!

No, the regex does not need the type. We need the type so we can build the `struct Varyings {...}`. If the user does a varying assignment without the explicit cast, then the assignment is still detected and an error is raised that clearly explains whats needed.

This, plus the requirement that assignments must be single-line are the only two things that are *extra*. I think its worth it, especially since both cases are detected.

> Can we work together on the "architecture design phase" for this shader templating system, and begin with working out the requirements for the system?

Yes!

**Comment by almarklein** [comment]
Here's a setup for the developer docs on writing shaders (including the proposal in this PR). For now I hope it will help our understanding of whats needed.

## Writing shaders in pygfx

To write shaders in Pygfx, you make use of a Shader object that helps with structuring your code, applying templating, and generating bindings for uniforms, textures, and storage buffers:

### The structure of a shader

Lets start with a simplified shader to explain its structure:

```py
from pygfx.renderers.wgpu._shadercomposer import WorldObjectShader


class MyShader(WorldObjectShader):

    def get_code(self):
        return self.vertex_shader() + self.fragment_shader()

    def vertex_shader(self):
        return """
        struct VertexInput {
            ...
        };

        [[stage(vertex)]]
        fn vs_main(in: VertexInput) -> Varyings {
            ...
        }
        """

    def fragment_shader(self):
        return """
        [[stage(fragment)]]
        fn fs_main(varyings: Varyings) -> FragmentOutput {
            ...
        }
        """
```

The shader object must at least implement `get_code()`. The typical use is to compose the result of multiple functions here, to easier structure/navigate your shader.

We can also see that the entrypoints are named `vs_main` and `fs_main`. These
are the entrypoint names that pygfx will use.


### Assigning varyings

Varyings is a GPU construct to communicate information from the vertex shader to the fragment shader. Varyings are assigned in the vertex shader, and can be used in the fragment shader. Their value will be
interpolated (e.g. over the face of a triangle).


```wgsl
        [[stage(vertex)]]
        fn vs_main(in: VertexInput) -> Varyings {
            ...

            var varyings : Varyings;
            varyings.position = vec4<f32>(ndc_pos);
            varyings.normal = vec3<f32>(normal);
        }

        [[stage(fragment)]]
        fn fs_main(varyings: Varyings) -> FragmentOutput {
        ...

        calculate_light(varyings.normal);
        }
```

The definition of the Varyings struct is handled by pygfx, and will be based on the varyings that are actually used in the fragment shader. It is safe to assign all variables that may possibly be needed in the fragment shader - unused varyings will be automatically disabled. This is especially useful in combination with templating.

A consequence is that assigning varyings must be on a single line, and that the value must be explicitly cast to the appropriate type, so that Pygfx has the info it needs to define the Varyings struct. That's why it does not say just `varyings.normal =normal`.

### Fragment shader output

In pygfx, rendering one frame may take two render passes (to hande transparent fragments better). The fragment output also depends on the renderers blend mode. Therefore, you do not simply return a color, but use functions provided by pygfx.

Further, you may want to discard fragments that are clipped by calling another pygfx-defined function.

This is still a bit up in the air, but it currently looks like this:

```wgsl
        [[stage(fragment)]]
        fn fs_main(varyings: Varyings) -> FragmentOutput {
        ...

        apply_clipping_planes(varyings.world_pos);
        add_fragment(varyings.position.z, final_color);
        var out = finalize_fragment();
```


### Templating

Often, a material has multiple properties and options. Sometimes these take effect as uniforms, but sometimes they will affect the shader code. This is where templating can be of great help.

Imagine this snipped:

```
        $$ if lighting
            let world_pos = varyings.world_pos;
            let lit_color = lighting_{{ lighting }}(is_front, varyings.world_pos, varyings.normal, varyings.light, varyings.view, albeido);
        $$ else
            let lit_color = albeido;
        $$ endif
```

The control flow blocks indicated with ``$$`` can be used to enable/disable blocks of code, based on a templating variable. In this case to chose between code for lighting or plain color. The blocks marked with ``{{...}}`` can be used to insert code. In this case this is used to specify the used lighting function.

Template variable are assigned to the shader object in three ways:

```py
# When initializing the shader object
shader = MyShader(lighting=True)
# By key access
shader["foo"] = 3.0
# When getting the wgsl
shader.generate_wgsl(bar=2)
```


### Bindings

TODO


### Putting it togeter in a render function

TODO

```py

@register_wgpu_render_function(Mesh, MyMaterial)
def my_renderer(wobject, render_info):
    geometry = wobject.geometry
    material = wobject.material  # noqa

    shader = MyShader(lighting=True)
    ...
    return [
        {
            "render_shader": shader,
            "primitive_topology": topology,
            "cull_mode": cull_mode,
            "indices": (range(n), range(n_instances)),
            "index_buffer": index_buffer,
            "vertex_buffers": vertex_buffers,
            "bindings0": bindings0,
            "bindings1": bindings1,
        }
    ]

```


### A summary of the rules that you have to be aware of:

* The vertex and fragment shader entrypoints must be named vs_main and fs_main.
* The fragment shader returns a `FragmentOutput` struct.
* The vertex shader return a Varyings struct, and the fragment shader has it as input.
* The varyings object is called "varyings" in both the vertex and fragment shader.
* Assignments to varyings must be on a single line and explicitly cast to the correct type.
* Fragment shader output needs to be handed via `add_fragment()` and `finalize_fragment()`.

**Comment by Korijn** [comment]
> A consequence is that assigning varyings must be on a single line, and that the value must be explicitly cast to the appropriate type, so that Pygfx has the info it needs to define the Varyings struct. That's why it does not say just `varyings.normal =normal`.

* I guess you opted not to have users "declare" varyings up front, because you want to detect if they are actually used or not?
* You could declare the types of the varyings up-front, to avoid requiring type-casting in shaders, right?
* Can you give an example of a multi-line varying assignment? I'm not sure what that would look like.

> ### Fragment shader output
> In pygfx, rendering one frame may take two render passes (to hande transparent fragments better). The fragment output also depends on the renderers blend mode. Therefore, you do not simply return a color, but use functions provided by pygfx.

It would be useful to list pygfx-provided functions. I imagine there are lots of reusable functions anyway (e.g. computing the world position of a vertex, or of a fragment).

> ### A summary of the rules that you have to be aware of:
> * The vertex and fragment shader entrypoints must be named vs_main and fs_main.
> * The fragment shader returns a `FragmentOutput` struct.
> * The vertex shader return a Varyings struct, and the fragment shader has it as input.
> * The varyings object is called "varyings" in both the vertex and fragment shader.

I think this part makes sense and is simple enough.

> * Assignments to varyings must be on a single line and explicitly cast to the correct type.
> * Fragment shader output needs to be handed via `add_fragment()` and `finalize_fragment()`.

I was wondering about those last two functions, what do they do?

**Comment by almarklein** [comment]
> I guess you opted not to have users "declare" varyings up front, because you want to detect if they are actually used or not?

Exactly. I think I used the word "define", but declare is much better.

> You could declare the types of the varyings up-front, to avoid requiring type-casting in shaders, right?

Yes we could. Maybe by letting the user declare a struct without the ``[[position]]`` stuff, and we update that struct.

> Can you give an example of a multi-line varying assignment? I'm not sure what that would look like.

I was thinking mostly of:
```wgsl
varying.foo = vec4<f32>(
    bladi, aldsnad very long math to calculatare each field etc.
);

> It would be useful to list pygfx-provided functions.

Good point, we should definitely list these in the (upcoming) developer docs!

> I was wondering about those last two functions, what do they do?

That part may change a bit as I implement OIT further. But the idea is that e.g. in volume raycasting, you encounter multiple transparent "layers", and you can blend them in the appropriate way using `add_fragment()`. Most other materials will produce just one value though, so perhaps a single function to deal with that case makes things a bit easier.

**Comment by Korijn** [comment]
> > You could declare the types of the varyings up-front, to avoid requiring type-casting in shaders, right?
> 
> Yes we could. Maybe by letting the user declare a struct without the `[[position]]` stuff, and we update that struct.

I was thinking of declaring them in python-land (e.g. as a dict on the shader object), so you only need to detect which ones are used in the shader. That should be sufficient information to create the struct and insert it. Might make it a little easier (on the user).

**Comment by almarklein** [comment]
Interesting idea! I'm not fully convinced about the advantage though ... I kinda liked how the types are defined where they're assigned.

How is "detecting which keys are actually used" different from "recognizing varyings"? With your suggestion, we still would need to detect the varying assignments, to distinguish them from normal varying use.

Also, detecting the type is not hard :)  I think the main downside is that shaders need to apply the cast consistently, but a good error message goes a long way in that regard.
