### ISSUE TITLE
Segmentation fault when changing blend mode on macOS

### ISSUE THREAD

**Issue by berendkleinhaneveld** [pygfx/pygfx#207]
When changing the blend mode in the transparency examples, I run into the following segmentation fault:

```
Selecting blend_mode blended
thread '<unnamed>' panicked at 'ColorState(1, FormatNotBlendable(R16Float))', src/device.rs:645:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    79601 segmentation fault  poetry run python examples/transparency2.py
```
Here is the full backtrace: [rust_backtrace.log](https://github.com/pygfx/pygfx/files/7608737/rust_backtrace.log)

For now, the examples run fine when I change the `_texture_info["accum"]` and `_texture_info["reveal"]` in [BlendedFragmentBlender](https://github.com/pygfx/pygfx/blob/9b706a5209366c64e955517822e23aa23c013480/pygfx/renderers/wgpu/_blender.py#L523) from 16 bit to 32 bit variants.

**Comment by almarklein** [comment]
The error is raised here:

https://github.com/gfx-rs/wgpu/blob/cd59c76e3a9b05525450f245e73aceb55cb9e035/wgpu-core/src/device/mod.rs#L2327-L2348

It says "not blendable", but it tests for the format being filterable. We don't actually need the filter, so we might be able to work around this by using texture-fetch instead of texture-sample.

**Comment by almarklein** [comment]
This also relates to https://github.com/gfx-rs/wgpu/issues/1412

For the record, F16 textures are supposed to be filterable according to the table at page 130 in [es_spec_3.0](https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf), as well as in table in the [webgpu spec](https://gpuweb.github.io/gpuweb/#texture-format-caps).

**Comment by almarklein** [comment]
Observations:
* The rgba16float works fine, its the r16float that causes the error. This is strange.
* The formats r8unorm and r32float both work.

**Comment by almarklein** [comment]
For the record, this no longer seems to happen for r16float.
