### ISSUE TITLE
Dont use ShaderType's to define uniforms

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#21]
The `ShaderType` type system (from `python-shader`) is convenient for defining uniform structs, because we can use the type both for instantiating a structured numpy array to hold the uniform data, and tell the shader what the uniforms struct looks like.

I think this guarantee that they match up is very valuable, but we may do it using ctypes types instead. Or another JSON-ish representation. Will need to add some logic in `python-shader` to convert in the other direction.

**Comment by Korijn** [comment]
Another way to look at this: if you implement a deferred renderer, the shader uniforms and types may be very different, but the material and its parameters still makes sense as input to that renderer.

**Comment by Korijn** [comment]
Closed in #98 and #97
