### ISSUE TITLE
Line rendering

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#23]
There are (at least) two methods for drawing lines. Using a pre-compute stage (ala geometry shader) or via instancing.

Using instancing appears to be a simpler solution. However, I just happen to overhear (in the [wgpu-native chat](https://riot.im/app/#/room/#wgpu:matrix.org)) that some drivers kinda break down at large amount of instances.

> looks like somewhere between 5K and 10K Intel driver fails to correctly reject the depth pixels and tries to overwrite them times and times again
> I'd call this a driver bug
> 
> You’re saying to limit instances on metal to 4K?
>
> that's a possible outcome, for this specific GPU family/driver, but it's not a decision that is made
we are just keeping that on the radar

**Comment by Korijn** [comment]
continued:
> yeah, it's not supposed to help :) if my guess is right, and we are hitting a limit on some HW per-pixel units, it doesn't matter whether we are submitting draw calls or instances
> so this is a good indicator that putting a limit to the number of instances is not a solution :)
...so both approaches would hit this theoretical limit if I understand correctly?

Either way: we can implement both approaches if we wanted to. I don't think it matters too much in the end.

**Comment by almarklein** [comment]
Agreed. Just wanted to document this potential pitfall somewhere :)

**Comment by almarklein** [comment]
> so both approaches would hit this theoretical limit if I understand correctly?

Actually, I think the suggestion was to divide instances over multiple draw calls, which is not gonna help. In the alternative line-drawing solution, there is just one draw call. One with potentially a enormous amount of vertices, but that should not matter, GPU's are pretty good there well into the millions.

**Comment by almarklein** [comment]
Done!
