### ISSUE TITLE
Can't run examples with shader error, how to fix it

### ISSUE THREAD

**Issue by Jungle178** [pygfx/pygfx#233]
```
Shader '' parsing error: unknown attribute  ┌─ wgsl:2:11
  │                                       : 'block'
2 │         [[block]]
  │           ^^^^^ unknown attribute     

', src\device.rs:191:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace       
```
wgpu = 0.7.2
pygfx = the latest from GitHub

I don't know where to find this "src\device.rs"

**Comment by almarklein** [comment]
Is this in a custom shader? The `[[block]]` syntax is no longer necessary.

**Comment by Jungle178** [comment]
> Is this in a custom shader? The `[[block]]` syntax is no longer necessary.

Run any .py in [[pygfx examples folder](https://github.com/pygfx/pygfx/tree/main/examples)] cause this error, for example [cube.py](https://github.com/pygfx/pygfx/blob/main/examples/cube.py).

I can't find any `[[block]]` or .rs file in pygfx or wgpu-py

**Comment by almarklein** [comment]
Could it be that its somehow using an older version of pygfx, and not the latest commit on the `main` branch? These shaders are in pygfx, and the blocks were removed a short while ago.

**Comment by Jungle178** [comment]
Problem has been solved by manually copying the latest commit version into python Lib\site-packages, thx.

**Comment by almarklein** [comment]
This should also work (from your pygfx clone):
```
pip uninstall pygfx
pip install -e .
```

Then you can `git pull` and it should just work :)
