### ISSUE TITLE
Bug in box_geometry()

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#246]
When you create a box that is not a perfect cube, the sides don't fit. So if in e.g. the `cube.py`example, you change to `gfx.box_geometry(100, 200, 200)`, you get this:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/3015475/153728645-d75aa755-90ec-429b-8274-262d80c15584.png">

I looked into it briefly. It seems like the segments data is corect for the data, so my impression that the matrix might be wrong. @Korijn you're more familiar with this code, any ideas?

https://github.com/pygfx/pygfx/blob/b20b4570ee6455b1c860926c4aca9a55a40b2b5a/pygfx/geometries/_box.py#L59-L81

**Comment by Korijn** [comment]
It's probably some axes problem. It might be easier to scale after composing the planes.
