### ISSUE TITLE
(Thick) Line material displaces vertices to infinity under certain conditions

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#250]

**Comment by Korijn** [comment]
Just with the default arguments!

**Comment by Korijn** [comment]
Can confirm this is an issue with the line material shaders.

![image](https://user-images.githubusercontent.com/1882046/154468556-38e447bc-cd55-4d0f-832d-a5bc4ebceb3b.png)

Zoom in and get....

![image](https://user-images.githubusercontent.com/1882046/154468595-7674349a-dd81-4f96-8f2c-45cd593f6ca3.png)

As you can see the box helper is also affected.

**Comment by Korijn** [comment]
Thin lines are not affected.

![image](https://user-images.githubusercontent.com/1882046/154469776-8878102a-9c80-492a-8ce4-d4ec03bb1912.png)
