### ISSUE TITLE
Can only do 30fps in basic cube example

### ISSUE THREAD

**Issue by safijari** [pygfx/pygfx#254]
Just started getting into this library. Was profiling one of the basic cube animation examples and I'm only getting about 30fps. I saw in the readme that even for very large scenes the author is able to get close to 60fps. Trying to understand what the issue could be.

My computer has a Quadro T2000 and an i9, and I'm on Ubuntu 21.04. glxgears runs at 1736fps. Unsure if this is something inherent to pygfx, wgpu, or something to do with vulkan support in my drivers. Any guidance would be much appreciated.

**Comment by Korijn** [comment]
All canvas classes take a `max_fps` kwarg which defaults to 30. :) Try setting it to something really high!

**Comment by safijari** [comment]
Ah, that's what I get for not reading the examples closely. Ok now it runs at a very suspicious locked 60fps no matter how high I set the max_fps. Is there something else implicit controlling some sort of vsync? I tried grepping through the source code for references to something like that to no avail.

**Comment by Korijn** [comment]
Good question. Could be the window toolkit you are using. Try using the GLFW canvas, I'm pretty sure that should work.

**Comment by safijari** [comment]
Hmm, tried that and was still stuck at 60fps. Ensured the max fps stuff is being set correctly and passed properly to the wait function. At least now I know where to poke around so I'll keep messing with it. Thanks.
