### ISSUE TITLE
High level pointer events

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#262]
As the use cases come up, we can implement the remaining pointer events.

* Over
* Enter
* Leave
* Out
* Got capture
* Lost capture
* Cancel

Reference docs: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

I think maybe over/out are most immediately valuable in pygfx to support material swapping on hover.

**Comment by berendkleinhaneveld** [comment]
Do you maybe want to keep this open for the other high level events?

**Comment by Korijn** [comment]
For now I don't really see good use cases for them. We can open new issues later.
