### ISSUE TITLE
Jerky animations

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#264]
I'm seeing jerky animations with e.g. the gizmo.

I only really see it if I attach an external screen. I can confirm that it is caused by the abundant calling of `get_pick_info` in pointer move events.

Interestingly, it also appear when the window is on my laptop's monitor. My current theory is that the GPU is just a bit busier with a second screen to control, and since picking is a sync operation (the CPU has to wait for the GPU to do the work) plus the fact that mouse move events can come in quite rapidly, this adds up.

**Comment by almarklein** [comment]
I tried replacing  `self._pixel_info_buffer.map_read()` with `queue.read_buffer(self._pixel_info_buffer)`. If anything, it makes it worse.

**Comment by almarklein** [comment]
The delay seems to occur in the call to `self.device.queue.submit()`. There's even a delay if I submit an empty list of commands.

**Comment by almarklein** [comment]
I tried using `self.device.queue.read_texture()`, avoiding the explicit call to `queue.submit()`, but again, no effect :(

```py
        data = self.device.queue.read_texture(
            {
                "texture": render_texture,
                "mip_level": 0,
                "origin": (x, y, 0),
            },
            {
                "offset": 0,
                "bytes_per_row": 256,
                "rows_per_image": 1,
            },
            size=(1, 1, 1),)
```

**Comment by almarklein** [comment]
There are about 500-600 events processed per second. Ok, I can see why this breaks down under certain conditions.

**Comment by almarklein** [comment]
I see two possible solutions. Either we rate-limit the move events to say 100 per second, or we don't add picking info to move events. 

Wheel events can possibly also be generated at a high rate, but it looks like these come in at less than 100 per second, and indeed dont show the jerky behavior.

**Comment by Korijn** [comment]
60 mouse move events per second is enough. I guess.

**Comment by Korijn** [comment]
> [...], or we don't add picking info to move events.

I just want to point out that this isn't really solution. Users will then just call it themselves and have the same issue.

**Comment by almarklein** [comment]
Good point. Rate limiting the pointer move events seems like a good solution that won't really affect usability. We can do it in wgpu-py or in pygfx. I'm leaning for wgpu-py, because similar issues might arise in other libs that would use wgpu-py. Any arguments for pygfx?

**Comment by Korijn** [comment]
I agree with implementing it in wgpu. Should probably go along with the max_fps setting.

**Comment by Korijn** [comment]
> The delay seems to occur in the call to `self.device.queue.submit()`. There's even a delay if I submit an empty list of commands. This is for the commands to copy data from the render textures to a tiny buffer.

There may be a more advanced way to optimize, if we already have the mouse position during the render call, you may be able to queue the read command and have everything execute in a single batch?

Just a thought and definitely not the first thing I would try :)

**Comment by berendkleinhaneveld** [comment]
> I agree with implementing event rate limiting it in wgpu. The rate limit should probably just respect the max_fps setting.

Yes, I think this would be best if we were to apply rate-limiting to the mouse-move events. Note that we need to carefully manage/accumulate offsets for those events.

> It's a silly idea but it might actually be more efficient (faster than the overhead of a queue.submit call for retrieval of a single pixel) to forget about the mouse position and just read the entire picking texture into cpu memory at the end of the render command queue! Then you can get the picking info of any pixel you want and there won't be any need to call queue.submit.

Silly idea maybe, but certainly interesting!

> That would also "rate limit" the picking info requests to the GPU to be in sync with the render frame rate, without rate limiting mouse events. Might be better for perceived input latency?

Without event rate limiting though, there is still the overhead for each event handler that will run on every emitted event, so I guess we would want to apply event rate limiting anyways. But yes: maybe a combination would work quite well!

**Comment by almarklein** [comment]
I think you mentioned 2 "crazy ideas", right @Korijn ?

1) Read the entire pick texture at the end of each draw, so lookups are in CPU-land. This is actually what Visvis does, and is also the reason visvis has a limited frame rate :)  - that's quite a lot of data to copy from GPU to CPU. We could give it a quick shot to see how bad it is though.

2) Queue incoming move events until a new draw is done. This is interesting, but I'm not sure if I'd bind it to a draw event, because maybe there won't be a draw for a few seconds. We could still batch mouse events, but in terms of timing this will feel the same as rate limted move events, except that a handler now has to handle 20 or so events in quick succession :) - but perhaps ì was missing a point in your idea.

**Comment by Korijn** [comment]
With regards to number two, I am thinking of game loops which go like this:

1. Poll inputs
2. Update world state
3. Render

It seems wrong that you could have hundreds of mouse move events in step 1. Only the final mouse state at the end of step 1 really matters, right? Or am I missing something?

I guess that I'm thinking we should theoretically only need to sample the picking texture once per frame.

**Comment by almarklein** [comment]
Ah right, more like rate limiting following the frame rate. The only problem I see with that is that we're not a game engine, and there are plenty of use-cases where we don't draw as fast as we can, but do want to process mouse events.

**Comment by Korijn** [comment]
> Ah right, more like rate limiting following the frame rate. The only problem I see with that is that we're not a game engine, and there are plenty of use-cases where we don't draw as fast as we can, but do want to process mouse events.

Yeah, now that you put it like that, I can imagine game devs could still implement this type of rate limiting on top of whatever we decide here anyhow.

OK! Let's implement event rate limiting in wgpu-py. :)
