### ISSUE TITLE
Text API

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#271]
A proposal for the text API.

Interesting links (for inspiration):
* https://www.npmjs.com/package/troika-three-text
* https://github.com/almarklein/visvis/wiki/Text
* https://vispy.org/api/vispy.visuals.text.text.html

### General discussion

Which props belong on the world-object, and which on the material? ThreeJS' troika has everything at the Object3D and uses a modified mesh material. Initially I liked the idea of putting most props on the material, since they affect how the text is rendered. But most of these props affects the positioning of the text, so they feel quite "structural".

### Alternative 1

A `Text` wobject and corresponding material. Not sure how to to bold/italic unless it is applied to the whole text.

class `Text(WorldObject)`, with properties:

* text
* font: the name of a builtin or system font, or a path to a font file
* font_size
* color
* anchor_x
* anchor_y
* angle
* max_width: if text goes beyond this, it will wrap
* line_height
* text_align

class `TextMaterial(Material)`, with properties:

* color

Maybe this could be a MeshMaterial ...

### Alternative 2

To have better support for formatting, we could introduce an object to hold a piece of text plus its formatting. We can then provide ways to generate these easily from e.g. Markdown, HTML or Latex.

class `TextPiece`, with properties:

* text: the Unicode text
* font
* font_size
* weight: bold, normal, etc.
* italic

We could have e.g. a `MathTextPiece` that has its own specific font and shaper, based on Latex input. Or a `MusicalNotesTextPiece`, if someone wants to go crazy. Bottom line is that with this we solve the "itemization" step, and that the TextPiece is responsible for the shaping. In comes Unicode, out come font indices and (relative) vertex positions.

class `Text(WorldObject)`, with properties:

* pieces: a list of `TextPiece` objects.
* text: shortcut to create a single text piece.
* markdown: shortcut to create simple formatted text.
* html: shortcut to create somewhat more advanced formatted text (e.g. `<small>` etc.)

... rest the same as alternative 1.

### Alternative 3

The geometry consists of an array of TextPiece objects. We have some functions to generate it.
```py
text = Text(
    gfx.text_geometry(markdown="hello **world**"),
    gfx.TextMaterial(...)
)
```

All props go on the material (except the specifics for the `TextPiece`). The buffers with positions and atlas indices are private.

### Alternative 4

The geometry consists of the actual positions and atlas indices, and we have functions to generate it. The code sample is the same as above, except now TextPieces are an internal construct, and the `text_geometry` function has arguments for all "properties" that affect positioning (e.g. `text_align`). In effect the material is "clean" and you can *always* put a different material on the same geometry without incurring unexpected CPU processing.

This is actually quite clean. The only downside that I see now, is that users may be a bit confused why some aspects are set as arguments in `text_geometry` and some as material properties.

**Comment by Korijn** [comment]
What data would be stored in the geometry buffers, and what data would go into the material properties?

The world object's core role is transformation.

**Comment by almarklein** [comment]
Okay, let's write out what we need for rendering:

* A texture for the atlas (this one is global to the device/application).
* A buffer with texcoords, or maybe just 1D integer indices into the atlas. One per text object.
* A buffer with positions (a quad for each glyph). One per text object.

These could be exposed/public, but we could also hide them (consider them an implementation detail).

Now, let's see how the different properties affect these data. These properties affect the glyph, thus the content of the atlas:

* the text itself
* font
* weight: bold, normal, etc.
* italic

These properties relate to positioning and layout, so they change the positions buffer during the pre-processing:

* max_width: if text goes beyond this, it will wrap
* line_height
* text_align

I think we can handle these props in the shader, so they can be uniforms:
* font_size (font size for the whole object)
* anchor_x
* anchor_y
* angle

And of course this one can be a uniform :)

* color

----

> What data would be stored in the geometry buffers, and what data would go into the material properties?

I'd consider the text or text pieces (or maybe TextItems is a nicer name) the "geometry" or source data. If we place most properties on the material - which makes sense IMO - I think it would be better to hide the position and texcoord buffers, because it would be weird if changing the material affected the public geometry.

> What computations have to run as preprocessing, and which ones run on the GPU at runtime?

Selecting the glyph, calculating the SDF, determining the relative positions of the glyph are all done on the CPU. The positioning that applies to the whole text object (like the anchor and size, can be done in the vertex shader. 

> Note: I don't support adding properties to world object, it's important to be able to share geometry and materials between world objects. This also goes for text.

Yeah, right now none of our world objects have properties beyond that of the base (only the InstancedMesh has a method).

> Imagine a scene where a bit of text keeps coming back in different locations. I want to create the geometry and material once (performs any expensive preprocessing?), and add it to the scene multiple times via world objects.

 Good point. If we are careful, taking into account which props change the internal buffers, we can even re-use the internal buffers for objects that have the same geometry, but a different material.

**Comment by almarklein** [comment]
I added two more alternatives in the top post. I like alternative 4, and I have a feeling you might too :)

**Comment by Korijn** [comment]
I really do like #4 :) 

> only downside that I see now, is that users may be a bit confused why some aspects are set as arguments in text_geometry and some as material properties

You could see this as an upside too: it communicates to users which arguments affect what (material or geometry).

**Comment by almarklein** [comment]
There is a use-case that our current API choice does not really support. Consider a piece of text that changes quickly (e.g. an FPS counter), or pieces of text that appear/disappear quickly (like ticks). It would potentially hurt performance in a significant way if these changes required new pipeline compositions. I wonder if we can somehow avoid that.

**Comment by Korijn** [comment]
Can you explain why?

**Comment by Korijn** [comment]
I don't fully understand why you couldn't update an existing geometry object?

**Comment by almarklein** [comment]
My point is that with the API that we've come up with so far does not allow updating the text anywhere :) A solution could indeed be to make this possible. This is a bit tricky though, because the number of glyphs cannot be increased (I guess we can reduce it by ignoring unused glyph slots).

**Comment by Korijn** [comment]
Looks like one of the reference implementations we linked above in this thread also goes the route of updating geometries:

* https://github.com/protectwise/troika/blob/main/packages/troika-three-text/src/GlyphsGeometry.js
