### ISSUE TITLE
pass animation parameter to shader

### ISSUE THREAD

**Issue by mikeny07** [pygfx/pygfx#282]
Thank you for adding custom object examples. 

Is it possible to pass a uniform animation parameters to shader, like the time parameter in three.js

**Comment by almarklein** [comment]
Sure, you'd do something like the color property here:
https://github.com/pygfx/pygfx/blob/2a0c057d10c8da57f02d62665f8aee55f96ee873/examples/custom_object2.py#L29-L47

... but call it `time`, and update it on each frame in the animation loop.

**Comment by jack1232** [comment]
Thanks, It works.

**Comment by mikeny07** [comment]
Thank you for the suggestion. It works.
