### ISSUE TITLE
Useful mesh shading (Phong, PBR)

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#29]

**Comment by almarklein** [comment]
I think we meant phong shading (or similar) here?

**Comment by Korijn** [comment]
I think it was in reference to this material: https://threejs.org/docs/#api/en/materials/MeshBasicMaterial

**Comment by almarklein** [comment]
Yeah, it probably was. Well, we have that. I'll just change the title then to track actually useful shading.

**Comment by Korijn** [comment]
Well, it has it's purposes. It can be used to implement picking via colors as IDs for example.

**Comment by almarklein** [comment]
We have Phong shading.
