### ISSUE TITLE
Map event coordinates from canvas to WorldObject positions data

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#293]
It would be useful to map mouse events, such as clicks on the canvas, to the `WorldObject`'s geometry's data.

For example, when using multiple scenes and viewports, mouse click events return the data in canvas coordinates. It should be possible to determine which rect is being used to map it to a viewport, and then get the camera position and zoom info to map it to the object's geometry data position. I think I could do if it this sounds reasonable, and if you have suggestions on the best approach that works universally regardless of viewports and scene complexity.

**Comment by Korijn** [comment]
This available in an event object under the pick_info property!

**Comment by kushalkolar** [comment]
Thanks!! I'll play with it this week, no worries about the docs; most of the code is already quite simple & readable!

**Comment by sharon92** [comment]
@Korijn if my click doesn't have a `World Object` under it, it's not possible to map the scene coords from the canvas coords. The pick_info also doesn't emit `ndc`. Could you help me out here? :)

**Comment by almarklein** [comment]
I think we've removed ndc from the info at some point (though the docs still mentions it). You can calculate the ndc relatively easy with `ndc = pos[0] / renderer.logical_size[0], pos[1] / renderer.logical_size[1]`, where `pos`  is the logical position.

**Comment by sharon92** [comment]
@almarklein I see, so ndc is not really what I need in that case. I am trying to implement a selection box, I want to draw a rectangle on the screen and select objects underneath. If my screen selection rectangle upper left and lower left is say: (20,20) and (40,40), is there a way to convert these positions to the `scene.local` coordinates?

**Comment by almarklein** [comment]
This should work. For 2D scenes with an ortho camera this should work pretty well. For 3D scenes, the result is very sensitive to the `depth` value (which is the depth in ndc coords, from 0..1).
```py
la.vec_unproject(ndc_pos_2d, camera.camera_matrix, depth=xxx)
```

**Comment by sharon92** [comment]
@almarklein is depth calculated as distance of camera to object?

**Comment by almarklein** [comment]
> is depth calculated as distance of camera to object?

Yes, but expressed as a number 0..1 between the near and far plane.
