### ISSUE TITLE
colormap issue

### ISSUE THREAD

**Issue by mikeny07** [pygfx/pygfx#295]
Tried to run the colormap_mesh.py example, and it works fine. However, when replacing the orthographic camera by a perspective one:

camera = gfx.PerspectiveCamera(70, 1)
camera.position.z = 10

the ob4 (color for each vertex)  gives a strange result as shown in the attached image:

![image](https://user-images.githubusercontent.com/96586756/163729116-a87537a7-b54c-4b05-a231-c8740df85e42.png)

Don't know why the colormap for ob4 depends on the camera.

**Comment by almarklein** [comment]
Interesting 😃 Thanks for letting us know!

**Comment by mikeny07** [comment]
Tried to place the vertex colors in this example to the Geometry class:

geo = gfx.Geometry(positions, indices, colors=vert_colors)

The program gives error ValueError("Expected Nx4 data for colors"). But the docs says colors can be NxM (M=1-4).

Anyway, adding the opacity component to the colors and then putting the colors to gfx.Geometry again gives a black screen without error. It seems gfx.Geometry class does not accept the colors argument...
