### ISSUE TITLE
Move example test running code out of tests folder to examples folder

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#298]
It's more convenient for people unfamiliar with pytest to use `pytest tests` and `pytest examples` than to have to figure out how to use the `-k` flag, since you need to look up the test name and the syntax for the flag, so:

* Move test_examples to the examples folder to enable `pytest tests` and `pytest examples`
* Update CI accordingly
* Update readme

As a bonus:

* Remove exception handlers for Qt and wxPython errors from tests, since we prefer just disabling the examples explicitly:

https://github.com/pygfx/pygfx/blob/05436b91b9e5d1c0eae97f4915bbbc15f6d5dc6d/tests/examples/test_examples.py#L58-L68

**Comment by almarklein** [comment]
It's also more convenient for people familiar with pytest but who would have to lookup the name of the test to mention in the `-k` arg 😉

**Comment by Korijn** [comment]
> It's also more convenient for people familiar with pytest but who would have to lookup the name of the test to mention in the `-k` arg 😉

Indeed, that is what I tried to refer to with "figuring out how to use the `-k` flag". This is more convenient!
