### ISSUE TITLE
controller method to center camera in a scene

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#301]
It would be useful to have a controller method that pans the camera such that the edges of the set camera position form a bounding box for all `Geometry` objects. I notice that there's a method to get the bounding box for `Geometry` objects, but not for the scene.

I'm wondering if there's a better way to possibly implement this:

```python
x1, y1, x2, y2 = (0, 0, 0, 0)
for obj in scene.children():
    if hasattr(obj, 'geometry')
    bb = obj.geometry.bounding_box()
    x1 = np.min(x1, bb[0][0])  
    y1 = np.min(y1, bb[0][1])
    x2 = np.max(x2, bb[1][0])
    y2 = np.max(x1, bb[1][1])

center = Vector3(
    (x2 - x1) / 2,
    (y2 - y1) / 2,
    0.0
)

pos = camera.position
delta = pos.clone().sub(center)
controller.pan(delta)
controller.update_camera(camera)
```

**Comment by Korijn** [comment]
Try `camera.show_object`? Does that do the trick for you?

**Comment by kushalkolar** [comment]
Nope this doesn't work (at least for Image objects), for example modifying the `geometry_image.py` example throws an exception:

```python
"""
Show an image.
"""

import imageio
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx


canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

im = imageio.imread("imageio:astronaut.png")[:, :, 1]

image = gfx.Image(
    gfx.Geometry(grid=gfx.Texture(im, dim=2)),
    gfx.ImageBasicMaterial(clim=(0, 255)),
)
scene.add(image)

camera = gfx.OrthographicCamera(512, 512)
camera.position.set(0, 0, 0)
camera.scale.y = -1

camera.show_object(image)

canvas.request_draw(lambda: renderer.render(scene, camera))
canvas
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 26>()
     23 camera.position.set(0, 0, 0)
     24 camera.scale.y = -1
---> 26 camera.show_object(image)
     28 canvas.request_draw(lambda: renderer.render(scene, camera))
     29 canvas

File ~/Insync/kushalkolar@gmail.com/drive/repos/pygfx/pygfx/cameras/_base.py:60, in Camera.show_object(self, target, view_dir, distance_weight)
     41 def show_object(
     42     self, target: WorldObject, view_dir=(-1, -1, -1), distance_weight=2
     43 ):
     44     """Utility function to position and rotate the camera to ensure
     45     a particular world object is in view.
     46 
   (...)
     58             The world coordinate the camera is looking at
     59     """
---> 60     bsphere = target.get_world_bounding_sphere()
     61     if bsphere is not None:
     62         pos, distance = Vector3(*bsphere[:3]), bsphere[3]

File ~/Insync/kushalkolar@gmail.com/drive/repos/pygfx/pygfx/objects/_base.py:445, in WorldObject.get_world_bounding_sphere(self)
    444 def get_world_bounding_sphere(self):
--> 445     aabb = self.get_world_bounding_box()
    446     if aabb is not None:
    447         return aabb_to_sphere(aabb)

File ~/Insync/kushalkolar@gmail.com/drive/repos/pygfx/pygfx/objects/_base.py:422, in WorldObject.get_world_bounding_box(self)
    420 def get_world_bounding_box(self):
    421     self.update_matrix_world(update_parents=True, update_children=True)
--> 422     return self._get_world_bounding_box()

File ~/Insync/kushalkolar@gmail.com/drive/repos/pygfx/pygfx/objects/_base.py:428, in WorldObject._get_world_bounding_box(self)
    426 if self._geometry:
    427     aabb = self._geometry.bounding_box()
--> 428     aabb_world = transform_aabb(aabb, self._matrix_world.to_ndarray())
    429     boxes.append(aabb_world)
    430 if self._children:

File ~/Insync/kushalkolar@gmail.com/drive/repos/pygfx/pygfx/linalg/utils.py:39, in transform_aabb(aabb, matrix)
     37 """Applies an affine transform to an axis-aligned bounding box."""
     38 corners = np.array(list(itertools.product(*aabb.T)))
---> 39 corners_world = transform(corners, matrix)
     40 return np.array([corners_world.min(axis=0), corners_world.max(axis=0)])

File ~/Insync/kushalkolar@gmail.com/drive/repos/pygfx/pygfx/linalg/utils.py:25, in transform(vectors, matrix, directions)
     23 # ensure type conditions are met so we can use np.dot(out=) kwarg for performance
     24 matrix = matrix.astype(vectors_4d.dtype, copy=False).T
---> 25 return np.dot(vectors_4d, matrix, out=vectors_4d)[..., :-1]

File <__array_function__ internals>:5, in dot(*args, **kwargs)

ValueError: shapes (4,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)
```

**Comment by kushalkolar** [comment]
Looks like it's supposed to create a 4D vector from the 3D one in `linalg.utils.transform` but it's not actually happening for some reason

```python
def transform(vectors, matrix, directions=False):
    """Applies an affine transform to a list of vectors, entry-wise."""
    shape = np.array(vectors.shape)
    shape[-1] += 1
    vectors_4d = np.empty(shape, dtype=vectors.dtype)
    vectors_4d[..., :-1] = vectors
    # if directions=True translation components of transforms will be ignored
    vectors_4d[..., -1] = 0 if directions else 1
    # ensure type conditions are met so we can use np.dot(out=) kwarg for performance
    matrix = matrix.astype(vectors_4d.dtype, copy=False).T
    return np.dot(vectors_4d, matrix, out=vectors_4d)[..., :-1]
```

**Comment by Korijn** [comment]
Ah, I see. Image and Volume don't actually have any geometry (as in, 3d coordinates), so the bounding box is invalid. I'll open a PR to fix that.

**Comment by kushalkolar** [comment]
What do you think about also finding the bounding box that accounts for all `WorldObject` items in a scene?

**Comment by Korijn** [comment]
That's what camera.show_object does! It takes the worldobject you pass in, retrieves the world space bounding box for the object and all its children, merges them and brings that into view.

**Comment by Korijn** [comment]
I fixed the issue, see #303

**Comment by Korijn** [comment]
To be clear, the `camera.show_object` function now supports any object. However, the `` Controller` classes don't have a `look_at` or  show_object`-like utility method just yet. That would be the remaining work in order to close this issue.

**Comment by kushalkolar** [comment]
Any ideas on how a `show_object` function could be implemented for the `Controller` class? I could try to implement it.  In `fastplotlib` I implemented something like this to show everything in a scene. However it can only be called after the canvas has been displayed, calling it before has no effect.

```python
bsphere = scene.get_world_bounding_sphere()
target, distance = Vector3(*bsphere[:-1]), bsphere[-1]

# this seems to work, not entirely sure why
txy = max(target.x, target.y)
txy = txy - (txy * zoom_padding) # zoom_padding is a small value sometimes, like 0.01
target_zoom = (txy / distance) / distance

zoom_factor = target_zoom / controller.zoom_value

curr_pos = camera.position
delta = target.clone().sub(curr_pos)
controller.pan(delta)
controller.zoom(zoom_factor)
```

**Comment by berendkleinhaneveld** [comment]
> I think I am missing a point. Why does the controller need a `show_object()` if the camera has it already?

Because when you use a controller to handle the camera, then the state is managed by the controller. So if you call `show_object()` on the camera, there would need to be a way of updating the camera state in the controller, which currently there is not. I think it would make more sense to have the `show_object()` method also on the controller instead.

**Comment by Korijn** [comment]
> I think it would make more sense to have the `show_object()` method also on the controller instead.

I think both need it, there are use cases for both.

**Comment by almarklein** [comment]
> Because when you use a controller to handle the camera, then the state is managed by the controller. 

👍   it still feels a bit awkward somehow, but I would not know how to do it better 🤷

**Comment by berendkleinhaneveld** [comment]
#326 introduces a `show_object` method on the controllers. @kushalkolar is that enough to close this issue?

**Comment by kushalkolar** [comment]
@berendkleinhaneveld Thanks! I have to test it a bit more. In notebooks via `jupyter_rfb`, `Controller.show_object()` only works after the canvas has already been displayed, I want to test it a bit more to see if it's possible to instantiate the displaying of the scene with things centered.

**Comment by kushalkolar** [comment]
@berendkleinhaneveld I can confirm that this works well, thanks for the implementation! Should I open an issue to keep track of the todo implementation for `OrbitOrthoController`?

**Comment by Korijn** [comment]
Does that mean we can finally finish #287 ? :)

**Comment by Korijn** [comment]
@kushalkolar can you close this if you are happy with the new functionality?

**Comment by kushalkolar** [comment]
> @kushalkolar can you close this if you are happy with the new functionality?

Should we keep it open until it's implemented for `OrbitOrthoController`, or should I make a new issue for that?
