### ISSUE TITLE
Different types of point materials

### ISSUE THREAD

**Issue by GarrettBlair** [pygfx/pygfx#316]
I see that there are point materials for defining spheres, but is there a method for creating different geometries for points (like cubes, triangles, etc.)?

**Comment by Korijn** [comment]
I think instancing is as close as you can get. You can use any mesh and use the transform matrices to position each instance 

https://github.com/pygfx/pygfx/blob/d6941399fc887f2a26879f64169000a53afdfaa1/examples/instancing_mesh.py

**Comment by GarrettBlair** [comment]
More marker style was exactly what I was thinking of. At least it is in the plan for the future, thanks for letting me know!
