### ISSUE TITLE
Caching of shader modules and pipeline objects

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#322]
Right now, each world object gets its own shader modules and pipeline objects (plural because of multiple render passes). However, sometimes they could be re-used. Same holds for e.g. bind groups and bind group layouts.

In cases when there are a lot of objects in a scene, it's likely that most have the same material type, so this form of caching could save significant gpu memory and startup-speed for scenes with many similar objects.

The most tricky part is likely destructing the objects when nothing uses it anymore. -> A solution is a cache that uses weakrefs and also attaching the cached objects on the world object.

Some notes:

* A reusable cache as an "internal service" that is used throughout pygfx for all features that require caching, with a global toggle would be a very useful debugging feature. It can also provide statistics such as cache hit/miss ratios and usage stats.
* Could make more use of caching in the renderer. There are some todo's indicating possible locations.
* ~~We could re-use the command queue instead of recording it on each draw.~~ Could use render bundles (tracking in  #518)

Locations where caching is/can be used:

* [x] In the text subpackage, we apply some caching of font objects and obviously glyphs in the atlas, but that's all really specific to text, so it does not seem right to bring that into the same system.
* [x] `_mipmapsutil.py` #516 
* [x] `_shadowutil.py`. #530
* [x] `_pipeline.py` #525
* [x] `_renderer.py`
* [x] `_flusher.py` #533
* [x] `_blender.py` #533 
* [x] May just have to scan over the whole wgpu subpackage to identify more cases.
* [x] `_environment.py` -> a lot of texture and view creations, do some checks!
* [x] `_mipmapsutil.py` does not cache texture views and bind_groups. Do a bit of benchmarking to see whether that matters. If it does, add caching. If it does not, maybe remove some caching of those objects in other places ...

**Comment by Korijn** [comment]
Some notes:

* Caching as an "internal service" that can be toggled off would be a useful debugging feature.

**Comment by almarklein** [comment]
Updated the top post to list locations of interest for caching. Also spun the render bundle idea into a separate issue.

**Comment by kushalkolar** [comment]
This is exciting! Naive question, does it make sense to store the cache on disk too to reuse it between pygfx runs? I've seen the "Building Vulkan shader cache" thing that pops up on steam the first time you launch a game or after updating gpu drivers.

**Comment by almarklein** [comment]
>  does it make sense to store the cache on disk too to reuse it between pygfx runs?

That's an interesting idea that I had not thought of yet. I think though, that the initial focus will be on being able to reuse stuff when multiple similar objects are created.

**Comment by Korijn** [comment]
> This is exciting! Naive question, does it make sense to store the cache on disk too to reuse it between pygfx runs? I've seen the "Building Vulkan shader cache" thing that pops up on steam the first time you launch a game or after updating gpu drivers.

The idea behind that is mostly to avoid *runtime* shader compilation and pipeline building. You would need to ensure all cacheable construction occurs on start of the application, so there won't be any stuttering after that.

Storing compiled shaders on disk is an option to speed up the next time the application is launched. I'm not sure if you could do the same for pipelines. Probably not.

I propose to create a separate issue for shader caching.

**Comment by almarklein** [comment]
> Storing compiled shaders on disk is an option to speed up the next time the application is launched. I'm not sure if you could do the same for pipelines. Probably not.

No, pipelines are objects on the GPU, we can't serialize those. If we ever want to go down the route of caching to disk, we should do some benchmarks to see if caching shader sources is worth it.
