### ISSUE TITLE
Use vertex buffers for meshes

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#323]
We use bindings (readonly storage buffers) about everywhere. For e.g. lines this is needed, but for meshes not really. Using vertex buffers instead could improve the performance, depending on your hardware.

The one issue holding this back is that when the wireframe property is set, the neighboring positions need to be accessed in order to get the picking coordinates.

Some options to move to vertex buffers:
* Make wireframe a material subclass with its own shader. Downside is that we must pick what lighting it supports.
* ~Reduce picking support for wireframe. Only pick vertex index, not sub-vertex barycentric coords.~
* Don't use vertex buffers but always use storage buffers. Does reduce the complexity of the codebase :)

Another option is to leave it as is. That way subclasses of mesh shaders do keep the freedom to implement more interesting/advanced stuff. Would be nice to have a benchmark to see how much it really matters performance wise. I suspect that for shaders with advanced lighting etc. it does not matter so much.

**Comment by Korijn** [comment]
It's still baffling to me that we can't just set an option on the WGPU pipeline to only render the lines. That's how every other rendering engine does it, I'm pretty sure they don't do all this trickery just to render wireframes.

**Comment by Korijn** [comment]
Also see https://github.com/m-schuetz/webgpu_wireframe_thicklines

**Comment by almarklein** [comment]
> See here: https://github.com/gfx-rs/wgpu-native/commit/6d63d53044aae6bc958578d147dda7aca9e342d0

Yeah, it's biefly been there, but removed just a little while later: 
https://github.com/gfx-rs/wgpu-native/commit/c4c66465367c329fb5bc9455441ecf92dcb08700#diff-cc8e93e710bd9ac3eaa9ca09299e28ba2839191111c4157a43936d8e6e8b26a1

It seems like its (at least currently) not part of the webgpu spec. And if it would, it would likely be lines of 1 physical pixel thick.

**Comment by panxinmiao** [comment]
I use vertex buffer (instead storage buffer) to transfer vertex related data not only for performance, I think it's also a standard practice. In my opinion, `VertexBuffer` exists for this purpose. My idea is that all geometry related attributes should be passed through vertex buffer, while material related attributes should be passed through uniform buffer. This can make the logic more unified.

After the last discussion (https://github.com/pygfx/pygfx/pull/309#issuecomment-1128904408), I searched some informations ( mainly the source code and implementation of threejs , :) ).  

For basic wireframe, use the `wireframe` attribute of `material`, when `wireframe=true`,  directly set PrimitiveTopology to "line-list" to achieve that.

For wireframe requirements of some more advanced effects, use a separate material “WireframeMaterial” (much like LineMaterial) or some wireframe util objects.  At this time, use shader Language to realize it., the vertex buffer transmits the position information of each vertex and its adjacent vertices. 

In threejs, `InterleavedBuffer` is used to do this,  and vertex position data is reused.

https://github.com/mrdoob/three.js/blob/70e0000856c8c9d53910484c56268da4b45b080c/examples/jsm/lines/LineSegmentsGeometry.js#L66-L115

```
const instanceBuffer = new InstancedInterleavedBuffer( lineSegments, 6, 1 ); // xyz, xyz

this.setAttribute( 'instanceStart', new InterleavedBufferAttribute( instanceBuffer, 3, 0 ) ); // xyz
this.setAttribute( 'instanceEnd', new InterleavedBufferAttribute( instanceBuffer, 3, 3 ) ); // xyz
```
`instanceStart` and `instanceEnd` are the data of each vertex and its adjacent vertices, and they are also the two endpoints of the line.

**Comment by almarklein** [comment]
Yes, its sort of standard practice to use vertex buffers, but that's also because storage buffers are not around for that long. Or at least they always felt "advanced/special" in OpenGL. In wgpu they feel very much native :)

That said, I also hope we can find a solution and use vertex buffers. But we can do this after your work on lighting etc.

I wrote earlier that the only thing really needing the storage buffers is picking for wireframe, but this was incorrect. The lookups for neighboring vertices is needed to create barycentric-like coords so that the wireframe can be given a uniform thickness. Not specific to picking. That explains why the project that @Korijn mentioned above also uses storage buffers.

**Comment by almarklein** [comment]
I think we have two options. I'll try to list some pro's and cons:

* Don't use vertex buffers in PyGfx.
   * pro: Simpler codebase (everything is a binding).
   * con: goes against conventions and possibly a performance hit on older hardware.
   * pro: wireframe can be applied to all mesh materials. Same goes for other special (sciency) meshes that people come up with later.
* Use vertex buffers for meshes, introduce `WireFrameMaterial` without shading.
  * con: more code, to introduce special mesh shader for wire frames. 
  * pro: performance and convention.
  * con: no lighting on wireframes, but not really important, I suppose.
