### ISSUE TITLE
Generated example gallery in documentation

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#345]
* we can probably run the following snippet in the pre_install hook for the RTD builds to have lavapipe available:

https://github.com/pygfx/pygfx/blob/b9f9e1ca43375be21097293320ac520cd6ea36a7/.github/workflows/ci.yml#L96-L99

Relates to #145

**Comment by almarklein** [comment]
Discussed with @FirefoxMetzger some ideas on how to handle the images:
* Could render in GH actions, and put *somewhere*, like a bucker ot something, and load these in RTD.
  * Downside is managing the bucket and its access rights, reliance on another service, etc.
* Could render the screenshots on RTD, but sooner or later we'll likely hit the half hour (?) built time limit. 
  * Would the limit go away if we'd take a business account?
* We could render in GH actions and put the screenshots as CI artifacts, which we can then load in RTD. 
  * Is it even possible for an outside service to download artifacts?
  * Race condition: when pusing a new release, RTD starts downloading before our CI is done generating the images.
* Could we render in GH actions and then *push* the artifact to RTD?
* Might be simplest to use GH pages instead.
  * But would miss out on different doc versions, analytics, and other RTD niceties.

**Comment by Korijn** [comment]
A couple of questions and suggestions:

* Would generating the gallery really take that much time? Unlike testing examples, we don't need strict process isolation between examples. That means you can retain the device instance and don't incur the initialization overhead again and again.
* Will rendering on RTD work? Depends on drivers, framebuffers, etc.
* You can publish build pipeline artifacts on GH but there is a max storage limit (sum of all builds artifacts) and a bandwidth limit and it is not very high.
* I would suggest sticking to RTD at first, and see how much we can squeeze out of the half hour time limit. How long does a build take right now? Can we shave off time? We can make installing dependencies (be very specific about which packages and versions to install and use wheels only) and cloning the repo very fast (shallow), and that is all relatively easy.

**Comment by almarklein** [comment]
[Apparently](https://docs.readthedocs.io/en/stable/builds.html) the RTD build limit is 15 minutes by default and 30 minutes for a business account.

> we don't need strict process isolation between examples. That means you can retain the device instance and don't incur the initialization overhead again and again. 

True, but we also have leaks in our caching at the moment, so it will likely blow up if you run all examples after each other on the same device 😄 

A plan might be:
* Test that we can actually render on RTD (via lavapipe, installation commands in top post).
* Test how long it takes to render our current examples. If that takes more than 5 minutes we will likely run into the limit soon as we get more cool examples :)  The current screenshot generation build takes 9 secs for generating the screenshots, so that looks promising.

Note that both scikit-image and vispy use GH pages. I'm not opposed to that option at all.

**Comment by Korijn** [comment]
Now I wonder why testing examples takes several minutes...

**Comment by Korijn** [comment]
I profiled hello_triangle.py for a bit.

```python
import cProfile

with cProfile.Profile() as pr:
    from wgpu.gui.auto import WgpuCanvas, run
    import pygfx as gfx


    canvas = WgpuCanvas()
    renderer = gfx.WgpuRenderer(canvas)
    camera = gfx.NDCCamera()

    triangle = gfx.Mesh(
        gfx.Geometry(
            indices=[(0, 1, 2)],
            positions=[(0.0, -0.5, 0), (0.5, 0.5, 0), (-0.5, 0.75, 0)],
            colors=[(1, 1, 0, 1), (1, 0, 1, 1), (0, 1, 1, 1)],
        ),
        gfx.MeshBasicMaterial(vertex_colors=True),
    )

pr.dump_stats("log.prof")
```

Results:

![image](https://user-images.githubusercontent.com/1882046/197991891-1bfe4e86-118d-412b-a0ab-80056525dbd1.png)

request_adapter and request_device dominate the runtime. Reusing them at the very least will cut down our runtime per example by 93%.

**Comment by almarklein** [comment]
> True, but we also have leaks in our caching at the moment, so it will likely blow up if you run all examples after each other on the same device 😄

Maybe we should just fix those 🚀

**Comment by Korijn** [comment]
I tried this in #362 and it works _really well_ locally, but on CI we're almost hitting 30 minutes. I don't understand.

**Comment by almarklein** [comment]
We've come along a great way in #384. We've found that building the gallery is fast (3 minutes)! We also found that we cannot install the PPA required to install Lavapipe. So let's reconsider our options. My inclination is to go with GH pages. It would be the simplest solution, and not that uncommon (e.g. scikit-image does it too).

**Comment by FirefoxMetzger** [comment]
Actually, we can build the gallery on RTD by simply not using the PPA. The default driver that ships with ubuntu 22.04 seems mature enough to build all of our current examples except for `collection_line.py` (which may fail due to driver issues or memory issues on the runner). 

It took a while to figure out, but now we seem to be back on track 😄

**Comment by almarklein** [comment]
> The default driver that ships with ubuntu 22.04 

Wait, LavaPipe is shipped by default?

**Comment by FirefoxMetzger** [comment]
@almarklein It is part of the default packages, so you can directly `apt install` it without having to enable any other repositories or add a custom PPA.

**Comment by Korijn** [comment]
On Ubuntu 22 you get lavapipe v20 instead of very latest (v23). Oibaf ppa builds are weekly. I don't think the packages in the standard ppa are ever updated (unless it's for significant security reasons).

**Comment by almarklein** [comment]
> On Ubuntu 22 you get lavapipe v20 instead of very latest (v23)

Well as long as it's good enough for building docs ...
