### ISSUE TITLE
Learn from pyrender

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#35]
https://github.com/mmatl/pyrender

Looks similar on many points to our goals here... and integrates with trimesh which seems desirable as well.

What will be the distinguishing features here in visvis2?

(We're based on WebGPU of course, but other than that...)

* Can we make our offscreen software rendering story just as accessible (see https://github.com/gfx-rs/wgpu/issues/644)?
* Texture3D seems to be missing from pyrender

This is a nice showcase: https://github.com/mmatl/pyrender/blob/master/examples/example.py

**Comment by almarklein** [comment]
Nice!

> Can we make our offscreen software rendering story just as accessible

Yes! Though the topic of offscreen does not really relate to software rendering, so I don't follow the issue you refer to?

**Comment by Korijn** [comment]
Well, in order to perform rendering on headless servers, you need to have both. There's no screen and there is no GPU/driver available. So you need offscreen rendering support and software rendering support. What's I liked about pyrender in this instance is that they provide a tutorial and example where the two techniques are combined.

**Comment by Korijn** [comment]
I feel like it would be a worthwhile addition to the lib/docs since it would make clear that visvis2 is useful for a very broad range of use cases, and not just interactive rendering.

**Comment by almarklein** [comment]
Closing. Looks like we have comparable features by now (and more). Maybe it has better support for gltf that we can learn from, but we track that via #85.
