### ISSUE TITLE
Text rendering consistency

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#358]
## The idea

In order to try to make our text output look "right", I made a test html page, rendered that in different browsers, and made screenshots. Then I compared results to see the variability. Then I tried to match pygfx's output to that of the browser's.

I made this issue to document what I did. There are many factors that play a role, and maybe someday someone wants to further improve the consistency of our text rendering with browser's output. Then this would be a good starting point ...

## The HTML I used

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Text size test</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans">
</head>
<body>

<style>

body {
    background: #777;
}
div.test {
    font-family: Noto Sans;
    box-sizing: border-box;
    display: inline-block;
    border: 1px solid blue;
    line-height: 1;
    color: #fff;
}
div.light { background: #000; }
div.light .test { color: #fff; }
div.dark { background: #fff; }
div.dark .test { color: #000; }
div.s20 {
    font-size: 20px;
    height: 20px;
}
div.s40 {
    font-size: 40px;
    height: 40px;
}
div.s80 {
    font-size: 80px;
    height: 80px;
}
</style>

<div class='light'>
    <div class='test s20'>20px Lorem ipsum! </div><br />
    <div class='test s40'>40px Lorem ipsum! </div><br />
    <div class='test s80'>80px Lorem ipsum! </div><br />
</div>
<div class='dark'>
    <div class='test s20'>20px Lorem ipsum! </div><br />
    <div class='test s40'>40px Lorem ipsum! </div><br />
    <div class='test s80'>80px Lorem ipsum! </div><br />
</div>

</body>
</html>

```

## The screenshots

![image](https://user-images.githubusercontent.com/3015475/197274340-008605e9-6c51-4a99-a507-7838c8295b2e.png)
![image](https://user-images.githubusercontent.com/3015475/197274253-f1fa2bfa-591b-4447-bedb-1b4e5bd0eba3.png)
![image](https://user-images.githubusercontent.com/3015475/197274278-8077f604-f4dc-48f7-89d4-042170717d53.png)

## Observations

* Appearance wise, the texts look equal.
* You need to open the images in an image editor and zoom in 200-300% to be able to spot (subpixel) differences.
* The type of browser seems to affect the output a tiny bit.
* The OS matters more (e.g. Windows and MacOS handle aa and pixel alignment differently).
* Browsers compensate for the fact that white text on a dark bg looks heavier; the text is made thinner!

## How I tweaked text rendering in PyGfx

* I tuned down the aa softness value a bit to reduce the width of the blurry edge. Our text edges are a bit smoother though, because our text tends to move around, and you don't want too much flicker.
* I made the font a wee bit thicker to match it with the white-on-dark text of the browsers. I tested against different font sizes. To see how the font is made thicker, search for `cut_off_correction`. 
* I tested with just one font (Noto Sans), and I assume (for now) that the results apply to other fonts too 🤷 
* I plan to make an example that uses `extra_thickness` to make black-on-white look equally thick.

**Comment by Korijn** [comment]
@almarklein I feel like we already did all of this? Is there any reason to keep this item open?

**Comment by almarklein** [comment]
Yeah, no need to keep this open 👍
