### ISSUE TITLE
Allow image to be placed anywhere in the same scene

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#367]
Currently instances of `Image` are placed according to the size of the image and it doesn't seem like it's possible to set the position of the image within the scene manually. This would also allow multiple images to be shown in the same scene and help with the implementation of option 1 here #360 

I notice that I can offset the `Image` position by adding values to the `geo.positions` in the shader code here, I could just feed it the information from `Geometry.positions` but I'm not sure if that's the best way (I've never written shaders before :smile: ) https://github.com/pygfx/pygfx/blob/main/pygfx/renderers/wgpu/imageshader.py#L71

**Comment by Korijn** [comment]
Image has a position attribute, does it not work?

**Comment by kushalkolar** [comment]
It seems like setting `positions` doesn't affect anything, I tried all combinations shown below. If I understand the shader code, it seems like it's just creating `pos1` and `pos2` from the texture dimensions? Unlike some of the other shaders where `positions` seems to be used.

```python
positions = [
    [150, 150, 0],
]

positions = [
    [150, 150, 0],
    [150, 150, 0],
]

positions = [
    [150, 150, 0],
    [150, 150, 0],
    [150, 150, 0],
]

positions = [
    [150, 150, 0],
    [150, 150, 0],
    [150, 150, 0],
    [150, 150, 0],
]
```

**Comment by kushalkolar** [comment]
Looks like I should add a `Binding` for `geometry.positions`, will make a PR

**Comment by almarklein** [comment]
Have you tried `image.position.set(150, 150, 0)`? (not the geometry, but the WorldObject)

**Comment by kushalkolar** [comment]
ah, that works setting it on the `WorldObject`!

**Comment by Korijn** [comment]
In general, all world object subclasses support position, rotation and scaling!
