### ISSUE TITLE
"geometry_plane.py" example doesn't render anything

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#372]
The example `geometry_plane.py` doesn't render anything. It produces a window, but then just hangs presumably because the rendering loop is never started.

Mainly creating this issue so that I can file a PR against it in a few minutes ... @almarklein @Korijn let me know if I should create issues for this and file PRs against issues, or if it is okay to just submit a PR directly.

**Comment by almarklein** [comment]
For things that are simple fixes requiring little discussion, just a PR is fine IMO.

**Comment by Korijn** [comment]
Yup, I agree with Almar!
