### ISSUE TITLE
Should the cube mesh in picking_mesh be not connected?

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#374]
I ran the picking_mesh example and noticed that the cube that is displayed is actually not connected, i.e., it is a collection of faces rather than a full mesh. Is this intentional?

![image](https://user-images.githubusercontent.com/4402489/199999403-3c26a04b-f099-4c23-9b99-cfdef1e4aa18.png)

**Comment by almarklein** [comment]
Yeah, that's because of how the box geometry is. Using a mesh that is actually a closed surface might improve this example.

**Comment by Korijn** [comment]
It's not closed so you do proper texture mapping. If the corners are shared to create a closed box you can't assign texture coordinates per side.

**Comment by FirefoxMetzger** [comment]
If it is intentional, we can close the issue :)
