### ISSUE TITLE
Allow closing the event loop via keyboard interrupt

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#377]
When I run the example `cube.py` (or any other example) with pyside6 as GUI backend then a Ctrl+C (`KeyboardInterrupt`) on the terminal will be reported in the shell but won't actually do anything. Would it be possible to add a listener for this that will then close all open windows and terminate the event loop, so that the program exists on Ctrl+C?

**Comment by Korijn** [comment]
Short answer is yes but it is challenging.

Long answers you can find if you google how to support keyboard interrupt for pyside/pyqt.

**Comment by Korijn** [comment]
From memory: the complexity is that KeyboardInterrupt will only be raised if you happen to time it so that CTRL+C is received by the process while the python interpreter is running python code, and not in the middle of waiting on some C code in Qt.

**Comment by FirefoxMetzger** [comment]
Yeah, I read up on that on SO; it's unfortunate (hence my sad-face reaction), and I would like to change it. At the same time, it's more of a nuisance than a real issue, so I will focus on other issues first.

**Comment by Korijn** [comment]
https://github.com/matplotlib/matplotlib/blob/9f96205464930c9064eb20af462c79ac47c6b254/lib/matplotlib/backends/qt_compat.py#L200

**Comment by almarklein** [comment]
FWIW it might be easier to implement for glfw because it uses the asyncio event loop, and although its still not an easy problem, this has been solved e.g. in asyncio-based web servers (like uvicorn and hypercorn).

**Comment by Korijn** [comment]
Are we able to copy their (MPL and Uvicorn) implementations?

**Comment by almarklein** [comment]
I guess so?
