### ISSUE TITLE
Text: font management

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#379]
Font management is the process of detecting and selecting fonts for rendering text. I found this is too big a topic to completely fit in #305. Here I'll try to summarize some things I learned and tried. And propose a plan. 

## Purpose

The dream goal is that users can use the gfx API to provide any text, and it will be rendered as expected, whether this is Latin, Cyrillic, Chinese or Egyptian Hieroglyphs.  Being able to do this is within reach since the Noto font exists. This is an open font, commissioned by Google, that attempts to cover all script known to men.

One big obstacle is that shipping all Noto fonts would take significant amounts of memory. Therefore, we need to find a good subset that we make "Just Work", and think about how to ship fonts for the more special and heavy scripts.

**What I hope to achieve** is that things just work for most users, and that for more special scripts, PyGfx shows a warning that a suitable font is not available, and instructions for how to obtain one. E.g. *"Some characters in your text require NotoSansJp, install this font using ..."*.

## A bit more on Noto

The Noto font is a family with over 100 fonts, organized mainly by script. The *main* font include Latic, Greek, Cyrillic, and punctuation etc. And then there is one font for Arabic, one for Traditional Chinese, one for Egyptian Hieroglyphs, etc.

There are projects that bundle these fonts in a smaller set of font files, e.g. https://github.com/satbyy/go-noto-universal  This is not without consequences, e.g. the line height can become larger because the font file contains a font with larger ascenders. This, and because you still have multiple font files to manage, make me lean towards using the original Noto fonts.

The go-noto project mentioned above does define some categories, based on geographic region, and also based on whether a script is considered ancient (only for historic use). This can help us make reasonable subsets.

## Default font and variations (serif, mono, bold, italic)

Many Noto fonts are available in both sans and serif. Quite a few are only in sans. A handful is only available in serif. The idea it to define a set of fonts using sans, and serif if sans is not available.

Most of this issue focuses on this default font to which we can always fall back. It would make sense, though, to also include e.g. NotoSansMono and NotoSerif.

Other variations on a font are weight (bold) and italic. Each such variation is another font file. E.g. to include bold and italic you'd need regular, bold, italic and bold-italic. Fortunately, we can render pretty good approximations of these variations (thanks to SDF). This means we can ship only the regular fonts. If a user wants the real thing, he can provide the necessary font himself. So when a bold font is requested, the font manager should try to find a matching bold font, and if that is not available, tell the shader to apply the approximation.

## Insights in the required memory

*(the color emoji font is exceptionally large, and I left it out. There is also a monochrome emoji font that is included).*

* All Noto fonts is 47.5 MB.
* Compressed with gzip this becomes 34.0 MB.
* Compressed with lzma this becomes 28.2 MB.

Leaving out ancient fonts:

* Raw: 39.8 MB.
* Zipped (gzip): 30.2 MB
* Zipped (lmza): 25.0 MB

Leaving out CJK (Chinese, Japanese, Korean) and ancient fonts:

* Raw: 10.5 MB
* Zipped (gzip): 5.1 MB
* Zipped (lmza): 4.2 MB

On [this wiki page](https://en.wikipedia.org/wiki/List_of_writing_systems) the population per script is listed. If I score scripts based on this and the size of the font, I can come up with a somewhat motivated "lite subset":
* NotoSans, the main font (latin, greek, cyrillic) - 556 KB
* NotoSansArabic - 177 KB
* NotoSansDevanagari - 191 KB

There are also some special fonts, some of which could be included in a lite subset:
* NotoEmoji 879 KB
* NotoSansMath 587 KB
* NotoSansSymbols - 203 KB
* NotoSansSymbols2 - 657 KB
* NotoMusic - 81 KB

And there is:
* NotoSansMono - 343 KB
* NotoSerif - 376 KB

## Technical stuff

I have a local script that uses the Google fonts api to get a list of all available fonts. From there it selects the Noto fonts and then the fonts that make up our default set. All the font files can then be downloaded. They can also be categorized as mentioned above.

Using freetype it is easy to check what Unicode code points are provided by a font. We can use this to create an index. This way, when we want to render text, we can check for each character from what font file it must be loaded. In #305 I demonstrate how we can render Latin, Arabic and emoji in one text object.

The idea is to create an index for the default (a.k.a. fallback) font: it maps a codepoint to a font. Further, for each font we keep a set (or set-like data structure) that can be queried to check whether a codepoint is in a certain font. That way, a user can provide one or more preferred font families, and the font manager can select the fonts that support the characters, falling back to our NotoSans if needed. The basics of this is implemented in #305.

We can also scan the system fonts (not currently implemented), and users can register their own font.

## The plan

Ship a subset by default. Either with PyGfx, or a new package specific to fonts. This could be the "lite" subset, or perhaps all fonts excluding CJK and ancient fonts. Size matters, not only for our end-users, but also because it would be installed e.g. on each CI job that uses pygfx.

For the other fonts, I am not sure yet. I came up with a few options.

### Plan A

Create a package for CJK fonts and another for ancient fonts. People can just pip-install them.

If you have multiple Python environments, you need to install the package multiple times. This can add up if you're a Chinese studying Egyptian Hyroglifics 😉  We could reduce this effect a bit by shipping the fonts in an lzma-compressed zipfile, and unpacking them in the appdata directory (shared between environments).

### Plan B

The package that supplies the basic fonts could have a command to download more fonts. E.g. using `python -m fontmanager download NotoSansJp`. Or in a GUI application the application could support installing more fonts with a click of a button. Auto-downloading is probably a bad idea (firewalls and all that).

### Plan C

We could add a page to the docs that has links to all the font files of interest. We can even put an anchor at each link, so the warning message can produce a link to exactly the file that needs to be downloaded. Once the ttf/otf file is downloaded, on most OS's you can just open it and click "install". 

This needs good support for detecting system fonts, and also detecting when they need to be re-indexed.

Plan B and C don't exclude each-other. Actually, neither does plan A.

**Comment by almarklein** [comment]
Listing the tasks that need to be done related to the plans outlined above:
* Preparation time:
    * a. Query the Google fonts API and download a subset of Noto font files. This can be (manually or automatically) redone to update the fonts.
    * b. Inspect the fonts with FreeType and create an index that maps a Unicode code-point to one of the font files from the default set.
* Docs
    * c. Host a page that has links to the fonts that we mirror, in a way that a specific font can be selected with an URL (using anchors).
* Runtime:
    * d. Detect fonts on the system, and provided via an `entry_point` like [this](https://github.com/pimoroni/fonts-python/tree/master/fonts). Also allow user-specified fonts.
    * e. Inspect these fonts (detect what characters is supports) and cache the results.
    * f. Given a piece of text, a list of font families, and font props, provide a list of `(text, fontfile)` tuples. 
      * Uses the result of (e) to be able to fall back to alt fonts, and eventually the default.
      * Uses the index from (b) to determine what default-font-file is needed.
      * When the necessary default-font is not present, display a warning with a link to (c).

I think it makes sense to put a, b, and c in a separate package, because mirroring those fonts would make the repo pretty big. Task d and e are pretty independent, though might be useful to other projects. In task f everything comes together, needing input from b, d, e.

My current impression is that it would be easiest to implement all the above tasks in a new library in the pygfx org.

I think this can be put together relatively fast, since code for most pieces is already there. If we want to merge #305 faster, we can removing from the PR all font files except the "NotoSans Regular" and "Noto Arabic Regular" (because we need the latter in tests related to RTL), and then update pygfx to make use of the new lib later.

**Comment by Korijn** [comment]
What are the specific decisions remaining at this point? Can I help you get going? :)

**Comment by almarklein** [comment]
The main decision, I think, is where to implement d-e-f. I'll start by creating a new repo for a-c, and implement d-e-f in pygfx (in this PR), and see how it goes.

**Comment by almarklein** [comment]
* a-c: https://github.com/pygfx/noto-mirror
* d: done in this pr

**Comment by Korijn** [comment]
Some questions I have at this point:

* Are you going to create wheels for noto-mirror? Or do something else?
* Besides right-clicking font files to install, I would also like to document how to install font files on the command line on at least debian systems, for people building applications with Dockerfiles

**Comment by almarklein** [comment]
> Are you going to create wheels for noto-mirror? Or do something else?

No. The only purpose is to provide a Mirror, and an index that we copy into pygfx so that it knows what font it needs for a specific code point.

We could, at some point, also create a package that ships all or a subset of the Noto fonts, to provide an alternative way for users to install the fonts. 

> Besides right-clicking font files to install, I would also like to document how to "ship" font files,

Good point. Will add this to #391

**Comment by almarklein** [comment]
Things are working as intended now! An illustrated story:

----

<img width="556" alt="image" src="https://user-images.githubusercontent.com/3015475/206719737-e5bf171b-f72b-44b9-882c-6852e5a29138.png">

----

<img width="565" alt="image" src="https://user-images.githubusercontent.com/3015475/206719809-1c69f43e-0899-408c-b43c-241865fa041e.png">

----

👎 😢 

----

<img width="482" alt="image" src="https://user-images.githubusercontent.com/3015475/206719927-736797dd-425e-4f28-a156-4a909a7791d1.png">

----

<img width="687" alt="image" src="https://user-images.githubusercontent.com/3015475/206720042-4f9e11ee-4ac8-4c89-8506-6c197913c495.png">

----

<img width="204" alt="image" src="https://user-images.githubusercontent.com/3015475/206721636-7ac69d60-f6d7-4074-a9e2-71e6320e46ed.png">

----

<img width="499" alt="image" src="https://user-images.githubusercontent.com/3015475/206721745-fdd73eb3-06f4-448c-b87d-a8214260ff9a.png">

----

<img width="562" alt="image" src="https://user-images.githubusercontent.com/3015475/206721919-cfe9c628-823b-4f86-aa07-ed23ed741cd2.png">

----

👍 😃

**Comment by almarklein** [comment]
Closes by #305
