### ISSUE TITLE
Creating video with pygfx

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#381]
I'm working on the sphinx gallery for the examples and I got the basic pieces working. At the moment we can generate a gallery and have sphinx-gallery use pygfx to render images and add them. Something like this:

![image](https://user-images.githubusercontent.com/4402489/201003035-3d9a7f76-6f12-4933-a5f0-d9982f794b43.png)

There are a few more things to iron out (like giving each example a title so that sphinx can link it automatically), but the basics are there.

One thing that is, perhaps, a bit of a luxury, but is still really useful for us is to show videos/animations in the gallery. This essentially works by creating a GIF that gets shown instead of the usual PNG. For this I have two discussion points:

- Is there an existing example of capturing a video with pygfx?
- The code for the video may have to be partly embedded in the example (to say "take a picture here, but do a video for X seconds there"). From a pedagogical perspective, this is suboptimal because we would ideally like to just show the example with the usual `run()` call so that they can see it nicely once they copy the code. Would an alternative be to say "we always show 5 sec of video for each render"?

I'm not 100% clear yet on how I want to solve this problem, but if you have ideas, I'm all ears :)

**Comment by Korijn** [comment]
> * Is there an existing example of capturing a video with pygfx?

I don't believe so but I guess you could start with an offscreen rendering example and then manually perform the render loop for the desired number of frames. Essentially I imagine just a for loop where you call `animate()`, then `canvas.draw()` to get a frame as an ndarray, and at the end of the loop you write the ndarrays to a GIF or video with something like imageio.

I hope @almarklein has a clearer vision to share with you.

> * The code for the video may have to be partly embedded in the example (to say "take a picture here, but do a video for X seconds there"). From a pedagogical perspective, this is suboptimal because we would ideally like to just show the example with the usual `run()` call so that they can see it nicely once they copy the code. Would an alternative be to say "we always show 5 sec of video for each render"?

One suggestion: You could keep the main examples simple, ending with `gfx.show()` in the `if __name__ == "__main__":` statement, and have a separate folder with video examples that build on (by importing) the main examples by tacking on an alternative to the `gfx.show()` call. You can keep the code for generating the videos separate from the gallery that way, but still generate them.

**Comment by FirefoxMetzger** [comment]
> I don't believe so but I guess you could start with an offscreen rendering example and then manually perform the render loop for the desired number of frames.

Yeah, I was thinking of this, too. My reservation about it is that the code for this needs to live somewhere. Either in the example or in some function that we import under the hood to do the generation. The issue here is that currently all examples are written to run indefinitely, so there needs to be an example-specific way to configure the duration of the video for sphinx, as it might be different for each example.

It also doesn't help that sphinx will run the example with a simulated `__name__ == "__main__"`, so the main guard doesn't work at all 😅 .

> One suggestion: You could keep the main examples simple, ending with gfx.show() in the if __name__ == "__main__": statement, and have a separate folder with video examples that build on (by importing) the main examples by tacking on an alternative to the gfx.show() call. You can keep the code for generating the videos separate from the example code that way, but still generate them.

I think that wouldn't play nicely with sphinx-gallery. The way generation works (on a high level) is that it transpiles a specially formatted `plot_my_example.py` into a `my_example.rst` and a `my_example.ipynb`. The example file itself generates most of the layout and then sphinx-gallery runs the example to record and show the output of each code block. We then register a hook to replace the output of some code blocks with images (or GIF) that we generate using pygfx.

The problem with importing the code in a video example from another example would then be that the resulting page has a nicely rendered video/GIF, but doesn't show any code to set up the video which I think nullifies the pedagogic value of showing the code and the animated result. We could keep two examples, one to show how to do it in practice, and one to show the video, but I think that duplication adds more maintenance burden for us than it adds value for a user.

Ideally, we'd run the video/GIF generation inside the callback that creates the output image to have both the code and the output in one place. This works fine in theory, except that you need a way to tell our callback when to create an image and when to create an animation. You may also wish to have some control over the video itself, e.g., over the duration. This info is example-specific, so it should probably live somewhere within the example. The question is just where and how can you make it distract as little as possible from the _actual_ content.

**Comment by Korijn** [comment]
Well, right now, the auto gui actually can be controlled to always instantiate offscreen canvas and noop event loops with an environment variable. That's how the examples are tested. You can use the same mechanism here

**Comment by almarklein** [comment]
> Is there an existing example of capturing a video with pygfx?

No. I think @Korijn is correct. Examples that are testable must already satisfy a few conditions (listed in the readme). One is that there is a global `renderer` object, and an render function is registered via `request_draw`. This means you can get the animate function from `renderer.target.draw_frame` and simply call it multiple times and take screenshots.

One thing to take into account is that some examples use the time to e.g. make things rotate. So we should either fake time, or just wait 1/60 sec between each render.

> The code for the video may have to be partly embedded in the example

I think the example should define how it should appear in the gallery. This can be done in a concise comment. This is what vispy does:

https://github.com/vispy/vispy/blob/f6b19fb03b9d2c391bc24a15e3de7b4c836894dc/examples/scene/line.py#L2

We already have `# run_example = false` to control whether an example should be run (just to touch the code), and `# test_example = true` to make a screenshot and compare it with a reference (we currently only do this for the validation examples). We could add something similar for the gallery.

To avoid having many such comments, maybe we can combine these into a one-line comment. Something like:
```py
# example:: test_run: True, test_screenshot: True, gallery: True, gallery_video: 10 
```

**Comment by FirefoxMetzger** [comment]
> One thing to take into account is that some examples use the time to e.g. make things rotate. So we should either fake time, or just wait 1/60 sec between each render.

I think it would be easier to "fake time". This way we can avoid worrying about a lot of edge cases, like what if the process that creates the video is temporarily put to sleep, etc. Do we already have an example on how to do this?

**Comment by Korijn** [comment]
All I can think of is this time mock in the example unit tests:

https://github.com/pygfx/pygfx/blob/2b762a314ed67ac81f3ed7ce1bbb2bdee2b6e0f5/examples/tests/test_examples.py#L69-L75

**Comment by almarklein** [comment]
Another option could be to update the examples not to use the time, but assume that the fps is at 30 (which the GUI backends run at by default). Then we can just take screenshots (which may take much longer on lavapipe) and set the mp4/gif playback speed at 30 fps.

**Comment by FirefoxMetzger** [comment]
Using `canvas.draw()` does the trick. If we are not concerned about timings, we can do:

```python
import pygfx as fx
import imageio.v3 as iio
from wgpu.gui.offscreen import WgpuCanvas


cube = fx.Mesh(
    fx.box_geometry(200, 200, 200),
    fx.MeshPhongMaterial(color="#336699"),
)

def animate():
    rot = fx.linalg.Quaternion().set_from_euler(fx.linalg.Euler(0.005, 0.01))
    cube.rotation.multiply(rot)

disp = fx.Display(WgpuCanvas())
disp.before_render = animate
disp.show(cube)

frames = []
n_frames = 3 * 25  # about 3 second GIF
for _ in range(n_frames):
    frames.append(disp.canvas.draw())

iio.imwrite("output.gif", frames, duration=40, loop=0)

```
![output](https://user-images.githubusercontent.com/4402489/205618406-83a152ee-c4d7-4824-a102-283e39df62b7.gif)


This solves my issue. Closing!
