### ISSUE TITLE
Resource Management in pygfx

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#382]
When generating the sphinx gallery one of the things we have to decide is when to render for a given code block (gallery scripts have code and text blocks like a notebook). I'm wondering how to best do that, so I checked how it is done for matplotlib and they check for currently open figures in each block and then close the figure once they are done processing it.

I was wondering if we could/should do the same for pygfx, hence my question is *how are resources managed at the moment*.

Currently, I have a stub implementation in place that looks for a `gfx.Camera` and a `gfx.Scene`, sets up an offscreen renderer and takes a screenshot (`renderer.snapshot()`). This works well enough to get everything up and running, but we might want to be a little more sophisticated to ensure that we can show examples that, for example, change parameters in the canvas or renderer.

**Comment by Korijn** [comment]
As far as I can recall, everything is handled via standard python garbage collection. There are no manual dispose or close calls.

**Comment by FirefoxMetzger** [comment]
Hm, so no context management via `canvas.close()` or similar?

**Comment by kushalkolar** [comment]
There is a `canvas.close()` and at least for me GPU usage shown by `nvtop` goes down immediately after it's called, at least with the jupyter rfb backend

**Comment by Korijn** [comment]
Oh.. hm. And if you just let the variable go out of scope? Does the memory leak?

**Comment by kushalkolar** [comment]
gc.collect() doesn't seem to do much

```python
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx
import numpy as np

def draw(shape):
    canvas = WgpuCanvas()
    renderer = gfx.renderers.WgpuRenderer(canvas)
    scene = gfx.Scene()

    im = np.random.rand(*shape).astype(np.float32) * 255

    image = gfx.Image(
        gfx.Geometry(grid=gfx.Texture(im, dim=2)),
        gfx.ImageBasicMaterial(clim=(0, 255)),
    )
    scene.add(image)

    camera = gfx.OrthographicCamera(*shape)
    camera.position.set(shape[0] / 2, shape[1] / 2, 0)
    camera.scale.y = -1

    canvas.request_draw(lambda: renderer.render(scene, camera))
    return canvas
```

```python
c = draw((8192, 8192))
c
```

VRAM usage: 295MiB

```python
c = draw((128, 128))
c
```

VRAM usage: 311MiB 

```python
import gc
gc.collect()
```
VRAM usage: 359MiB :confused: 

Also, it appears that `canvas.close()` reduces GPU usage, but GPU VRAM remains unchanged until you kill the python kernel. Calling `gc.collect()` before or after `canvas.close()` has no effect on VRAM usage even if there are no remaining references to the canvas.

**Comment by Korijn** [comment]
Like this, I mean:

```python
c = draw((128, 128))
del c
import gc
gc.collect()
```

You have to ensure there are no references to `canvas` before you call `gc.collect()`, to see if that triggers the memory to be released or not

**Comment by kushalkolar** [comment]
Yup I tried that too, same thing.

339MB of VRAM usage that doesn't go away, PID is 565848 

![image](https://user-images.githubusercontent.com/9403332/201072718-be3cdbc7-2146-4a3e-ad88-d8cce1517b29.png)

**Comment by Korijn** [comment]
I'm a little hesitant in that I don't trust the jupyter backend to actually clear every last references to the canvas, but OK, that seems like a leak.

**Comment by almarklein** [comment]
To get back to the original question, none of our examples does something related to code blocks in a notebook-like way. IIUC that was what your question is about? So I think all examples should (at least for now) be considered simple scripts.

Later we could add actual notebooks for more step-to-step guides.

**Comment by Korijn** [comment]
I have been reading up on this a little bit, and it seems to me that the Python interpreter does not just free/release memory back to the OS on demand. It rather keeps allocated memory around for re-use. So maybe that is not the right way to measure this.

**Comment by FirefoxMetzger** [comment]
> To get back to the original question, none of our examples does something related to code blocks in a notebook-like way. IIUC that was what your question is about? So I think all examples should (at least for now) be considered simple scripts.

@almarklein Sort of. For gallery examples that use matplotlib sphinx gallery will run the example, detect any open figures, and render them to PNG. We would ideally do something similar in pygfx by detecting open scenes/canvases/renderers and rendering those to PNG. 

The question is just what to search for to detect that there is something for pygfx to render. A natural choice is at the resource boundary, hence my question how resources are currently managed.

> the Python interpreter does not just free/release memory back to the OS on demand

Isn't this done by most applications to reduce memory fragmentation? In any case, the host memory and GPU memory should work differently because the OS doesn't manage vRAM. I'm not sure how it works in Vulkan, but for nvidia/cuda you have to create a cuda context which is responsible for the memory management on the GPU.

If you want, I can have a more detailed look at the gc and see if I can figure out if/why the canvas isn't cleared up. I would like to focus on the current PRs first though (`gfx.show`, the guide, and the sphinx gallery) so depending on yours and @almarklein s thoughts I could investigate this next or do something else.

**Comment by almarklein** [comment]
> The question is just what to search for to detect that there is something for pygfx to render. A natural choice is at the resource boundary, hence my question how resources are currently managed.

You mean how to detect open canvases? I think for now we can assume that all examples that we put in the gallery have exactly one canvas. These should have a `renderer` in the global scope, and you can use that to render a frame, and get the canvas object to create a screenshot.

> If you want, I can have a more detailed look at the gc and see if I can figure out if/why the canvas isn't cleared up. I would like to focus on the current PRs first though (gfx.show, the guide, and the sphinx gallery) so depending on yours and @almarklein s thoughts I could investigate this next or do something else.

Let's first focus on the open PR's indeed.

**Comment by FirefoxMetzger** [comment]
> You mean how to detect open canvases? I think for now we can assume that all examples that we put in the gallery have exactly one canvas. These should have a renderer in the global scope, and you can use that to render a frame, and get the canvas object to create a screenshot.

Yes, I'm looking for a way to detect open canvases or some other unique indicator of when I should render a picture. At the moment I can simply do one render at the end of each example, but I was wondering if refactors like "let's put all primitive geometries into one example called _Geometric Primitives_" would be meaningful.

Yes, `renderer` could be a good target to look for. However, once we start using the new `gfx.show` for our examples there will be no global `renderer` variable anymore 😅 (... if only we had a [`display`](https://github.com/pygfx/pygfx/issues/383) variable we could check instead 🤣)

**Comment by almarklein** [comment]
Original issue is solved in the gallery PR. The memory leak is now tracked in https://github.com/pygfx/wgpu-py/pull/306. Closing!
