### ISSUE TITLE
dataclass and decorators for gfx.show

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#383]
While improving show in #380 I made two suggestions that we may want to track for future reference: 

First, we could consider wrapping `gfx.show` into a dataclass:

```python
@dataclass
class Display:
    canvas: object = None
    renderer: gfx.Renderer = None
    camera: gfx.Camera = None
    ...

    def show(self, scene, up):
        ...
```

This way we can create a `disp = Display()` that can be customized as the program executes. We then only need to call `disp.show(scene)` in the end. This would make managing a custom setup easier, as we have all the data in one object instead of having to manually track multiple objects.

Secondly, we could consider creating a decorator for the callback functions that can be set in `gfx.show`. I.e., instead of calling `gfx.show(scene, before_render=animate)` we would do:

```python

@gfx.show.before_render
def animate():
    ...

# calls `animate` before rendering
gfx.show()
```

This would mostly be syntactic sugar and make our life a bit easier. The downside of this is that it introduces global state for `gfx.show`, since we would have to track the callback once it was registered.

**Comment by kushalkolar** [comment]
Interesting idea, it's somewhat similar to how I thought about the [`Subplot`](https://github.com/kushalkolar/fastplotlib/blob/master/fastplotlib/subplot.py) class in fastplotlib. 

Do you think `camera` should be part of `Display`, it is possible to have multiple scenes and cameras (with viewports) on the same canvas using the same renderer.
