### ISSUE TITLE
Make renderer.show_fps draw on canvas instead of cout

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#387]
`gfx.renderer.WgpuRenderer` can be constructed with `show_fps=True`, which will periodically print the current FPS on the screen. I think it would be more useful if this FPS would show up in the corner of the window instead, e.g. the top right as it is in many other applications.

We could make this an enhancement by allowing `show_fps` to accept a string like `show_fps="top right"` (with values "top|bottom left|right" or `show_fps="console|cout"` or `show_fps=None` to control the behavior. Perhaps even allow a callback that gets called periodically with `show_fps=lambda fps: <awesomeness>`.

**Comment by almarklein** [comment]
Good idea. We need text rendering first though!

This is also a nice use-case for text periodically updates, BTW.

**Comment by Korijn** [comment]
Alternatively, as a quicker path to getting this sorted, you could also wrap the canvas widget in a very simple GUI window using something like Qt to show the FPS in a textbox or something.

But I think we should just wait to get text rendering implemented. :)

**Comment by FirefoxMetzger** [comment]
Agreed. Let's wait for https://github.com/pygfx/pygfx/pull/305

**Comment by Korijn** [comment]
This was completed in #486
