### ISSUE TITLE
box_geometry parsed as returning NoReturn

### ISSUE THREAD

**Issue by ccaven** [pygfx/pygfx#389]
Downloaded the latest version via pip. When using `gfx.box_geometry`, Pylance detects all future code as unreachable.
The signature seems to be reported as `NoReturn`
![image](https://user-images.githubusercontent.com/19079506/202881510-d5688ccf-2ddb-46b0-94b4-1cd7ca882ee1.png)
VSCode:
![image](https://user-images.githubusercontent.com/19079506/202881581-d510bc4b-188f-4862-b09c-8eff7b6cc31a.png)

**Comment by ccaven** [comment]
Upon further investigation, this seems to be a problem with Pylance.
It's detecting `np.cross` to have a possible `NoReturn`
![image](https://user-images.githubusercontent.com/19079506/202883536-5404d127-df49-4b32-94d8-9a17231c6622.png)

I'll close this issue because it no longer relates to pygfx.

**Comment by Korijn** [comment]
Yeah it's pretty annoying 🙂 but it's indeed an issue in the numpy type annotations and pylance.

**Comment by ccaven** [comment]
One solution seems to be adding `dtype=np.float64` (or a different precision) to the `np.cross` function call
