### ISSUE TITLE
Shadow map bug

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#393]
In the screenshot below you can see that shadow mapping works properly in the green circle, but incorrectly in the red circle. There should be a shadow on the portion of the pillar below the light source as it is occluded.

I think this is caused by the near plane for the shadow map cameras.

![image](https://user-images.githubusercontent.com/1882046/203770725-15bd91b8-4320-47c5-9427-ca7b93ca4a10.png)

**Comment by Korijn** [comment]
Indeed, adjusting the near plane from `0.5` to `0.1` in the following line resolves the problem in this case.

The question remains what good settings are and how one would automatically determine them.

https://github.com/pygfx/pygfx/blob/2b762a314ed67ac81f3ed7ce1bbb2bdee2b6e0f5/pygfx/objects/_lights.py#L516

![image](https://user-images.githubusercontent.com/1882046/203827482-0d329d67-0b54-479c-8fd5-241c77434aee.png)

**Comment by panxinmiao** [comment]
For specific light source shadows in the scene, you may need to adjust the shadow camera parameters to achieve specific purposes. This is particularly significant  in the current directional light shadow. see "light_directional_shadow.py".

In this example, it's should like this:
```
light.shadow.camera.near = 0.1
light.shadow.camera.update_projection_matrix()
```
Of course, maybe we should set the default value of the near plane of the shadow camera a little smaller.

**Comment by Korijn** [comment]
@FirefoxMetzger I think it would be worthwhile to apply the fix proposed here to the sponza example, if you are going to put the screenshot front and center on the README. It's a very simple fix and it looks much better.
