### ISSUE TITLE
Repeated calls of `Display.show` freeze the program / get stuck

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#394]
I was experimenting with ways to detect if the gallery has already rendered a particular display and noticed that it is currently impossible to make repeated calls to `Display.show`. E.g. the following snippet will freeze on the second `disp.show` call when using pyside:

```python
import pygfx as gfx

cube = gfx.Mesh(
    gfx.box_geometry(200, 200, 200),
    gfx.MeshPhongMaterial(color="#336699"),
)

if __name__ == "__main__":
    disp = gfx.Display()
    disp.show(cube)

    # stuck here forever
    disp.show(cube)
```

My guess is that this happens because the `canvas`/window was closed by the user and the second call to `show` waits forever for the previous canvas to re-appear; however, this never happens because it is already closed.

This can be both a bug or a feature. We could treat it as a bug and change this so that `show` checks the state of the canvas/renderer and creates a new one if needed. This would allow repeated calls to `show`. Alternatively, we can treat this as a feature, and we can document that this is supposed to be a one-time-use method and raise a descriptive exception on repeated calls. The latter could be used by the gallery to check if the example used `show` on the given display and if so the gallery could proceed with rendering the scene for the docs.

**Comment by Korijn** [comment]
I'm on board with making this a one time use thing, although I can imagine people wishing to reuse a display in a jupyter notebook perhaps. Tough luck I guess. :)

**Comment by FirefoxMetzger** [comment]
Hm, what would the logic be for a jupyter instance? The same canvas appearing in two different locations?

**Comment by Korijn** [comment]
I don't really know, I can just imagine users would try initializing the Display class in one cell, and using `disp.show(scene1)` in the next, and `disp.show(scene2)` in another one, expecting it to just work.

**Comment by almarklein** [comment]
I'm also in favor making it onetime use. Trying to revive/recreate the canvas may quickly get complicated (e.g. what if a custom canvas was provided). People can still use `gfx.show()` repeatedly.

**Comment by almarklein** [comment]
Canvases have an `is_closed` method that maybe of use here.

**Comment by FirefoxMetzger** [comment]
Hm. I wrote a quick PR for this, but apparently, this doesn't work when combined with the offscreen backend, because it can't be closed:

```python
from wgpu.gui.offscreen import WgpuCanvas

foo = WgpuCanvas()
foo.close()

assert foo.is_closed()  # fails

```

I've discussed this with Almar during our meeting today and the consensus was that we should probably make the offscreen canvas closable (by setting a flag but not changing its behavior) so that it behaves the same as other canvases.
