### ISSUE TITLE
Pin lavapipe

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#395]
We could consider pinning lavapipe to prevent main from breaking.

I think apt-get and debian PPAs don't support pinning natively, so instead we could create a zip file with the .deb files installed by apt-get, and use that on CI to install.

I guess we'd need to host it somewhere, I can make another repo that automates this process via Actions and publishes the zipfile to a Release.

That way we can control when we upgrade, just like we do for wgpu-py.

**Comment by almarklein** [comment]
So far the Lavapipe has not broken our CI **that** often. E.g. with the current breaking of the volume validation example, I like to think that something was fixed that was previously broken. My suggestion would be to just update the screenshots when it happens. Unless we end up having to do this every week, of course :)
