### ISSUE TITLE
Linalg refactor

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#40]
Goal of this issue is to be provide a more pythonic API and to make it easier to track changes to world object transforms.

* Start using the https://github.com/pygfx/pylinalg package so we can drop the linalg module and tests from this project.
* Refactor such that we work with plain ndarrays for all data (e.g. vectors, matrices, quaternions)
* Provide modules with linalg utils (e.g. `pylinalg.quaternion.from_euler()`)
* Be consistent about functions accepting arguments: `xx(point)` vs `xx(x, y, z)`. Also in the pygfx itself.
* Be able to add and multiply vectors, and be able to scale (interpolate) rotations.
* In-place ops ...

**Comment by almarklein** [comment]
This can be useful: https://www.python.org/dev/peps/pep-0646/

**Comment by almarklein** [comment]
Korijn is working on it: https://github.com/pygfx/pylinalg/pull/5
