### ISSUE TITLE
FileNotFoundError: noto_default_index.json not found

### ISSUE THREAD

**Issue by EricThomson** [pygfx/pygfx#412]
In last few days when I try to `import pygfx` (Windows 10) I get (truncated stack trace):

```
File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\utils\text\_fontmanager.py:175, in FontManager._load_default_font_index(self)
    171 def _load_default_font_index(self):
    172 
    173     # Load the json
    174     index_filename = os.path.join(get_resources_dir(), "noto_default_index.json")
--> 175     with open(index_filename, "rt", encoding="utf-8") as f:
    176         ob = json.load(f)
    177     families, fnames, index = ob["families"], ob["filenames"], ob["index"]

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Eric\\miniconda3\\envs\\fpl\\lib\\site-packages\\pygfx\\pkg_resources\\noto_default_index.json'
```
I installed using  `pip install -U https://github.com/pygfx/pygfx/archive/main.zip`

I downloaded `noto_default_index.json` and dropped it into `pkg_resources` folder, and things seem to work. The other files seemed to be in there.

**Comment by Korijn** [comment]
I guess we overlooked updating our packaging code to ensure these files get shipped. Thanks for reporting!

**Comment by almarklein** [comment]
Oh dear, my mistake! I never updated `data_files` in setup.py. Interesting how this slipped passed the CI checks...

**Comment by kushalkolar** [comment]
Since the CI workflows clone the repo they'll pull in more stuff than pip, even if pip installing from the repo
