### ISSUE TITLE
Line geometry positions for streaming time series data

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#414]
If I understand correctly the positions buffer is not expandable (or maybe it is since there was a recent change to allow non contiguous arrays?), so I'm wondering what's the best approach to visualize streaming time series data. For instance, I want to add a new vertex to the line on each rendering cycle.

If it's not possible to expand the Geometry positions, one approach I could see is preallocating a large chunk of line, setting the alpha of future timepoints as 0, and then creating new line with an offset that's ready to go once the previous "chunk" is nearly full.

**Comment by almarklein** [comment]
Buffers have a fixes size. 

>  maybe it is since there was a recent change to allow non contiguous arrays?

Not sure what you refer to here, but the TextGeometry van use just part of its buffer if a new string is set that is smaller.

> one approach I could see is preallocating a large chunk of line, setting the alpha of future timepoints as 0, and then creating new line with an offset that's ready to go once the previous "chunk" is nearly full.

Something like this would be the way to go, yes. You may want to have a custom shader, but maybe with using alpha this is not necessary.

**Comment by panxinmiao** [comment]
@almarklein 
We can provide the ability to "only draw a part of vertices of Geometry" in the API in some way. (by the `draw()` args of `render_pass` in wgpu), maybe we can add a `draw_range` attribute to `Geometry`.

**Comment by almarklein** [comment]
@panxinmiao Good idea. I added this idea to #19

**Comment by kushalkolar** [comment]
Interesting! Maybe this would also allow dynamically drawing only the portion of the geometry that is currently being viewed by the camera?

**Comment by almarklein** [comment]
Hold your horses :)  This only allows setting an offset and a count, so it's still a contiguous region: https://wgpu-py.readthedocs.io/en/stable/reference_classes.html#wgpu.GPURenderCommandsMixin.draw
