### ISSUE TITLE
Gallery build breaks on windows

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#425]
In https://github.com/pygfx/pygfx/pull/422 we changed the behavior of building the gallery to only execute files that are in a path that is not `**/other/*`. This breaks on Windows - I guess because paths use `\` instead, which the current regex doesn't capture.

I'll submit a fix soon(TM).

**Comment by FirefoxMetzger** [comment]
Another issue is that our test suite doesn't specify an encoding to use when testing the examples. This used to not be a problem, but the text rendering PR (https://github.com/pygfx/pygfx/pull/305) introduced some kyrillic in the example. Ofc, this breaks on Windows, which doesn't default to using UTF-8 🙄.

I'll leave the comment for this here and fix it in the corresponding PR, because they both small issues and seem related.

**Comment by almarklein** [comment]
> This breaks on Windows - I guess because paths use \ instead, which the current regex doesn't capture.

Woops, my bad!

> Another issue is that our test suite doesn't specify an encoding to use when testing the examples.

I think Korijn fixed this in #424

**Comment by FirefoxMetzger** [comment]
@almarklein Indeed. I will wait until #424 is merged before continuing this - otherwise, I think we will end up duplicating the work and may create an ugly merge conflict.
