### ISSUE TITLE
Add autosummary in the docs

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#427]
I am looking into https://github.com/pygfx/pygfx/issues/113 and I've noticed that our reference docs are currently a "dump" of all modules onto a single page. I think it would be cleaner if we had each module on a single page.

The downside of this would be that we can no longer Ctrl+F on a single page to find the function we want. The upside is that we don't serve a single gigantic page if users only want to check a single function/module. It is also advantageous if we ever want to introduce analytics, because we can get per-module view-counts.

**Comment by almarklein** [comment]
> I think it would be cleaner if we had each module on a single page.

Maybe not per module, but per sub-package. E.g. geomeyty, materials, cameras, etc.

**Comment by FirefoxMetzger** [comment]
On second thought, it might not be wise to split on the module/sub-package level. We make an effort to forward all classes and functions into the global `pygfx` namespace. Consequentially, there is no easy way for a user to know which sub-package to check when looking up a specific function. For example, how would I go from `gfx.Display` to searching in `gfx.utils.Display`?

From that perspective, I think it is easier if all classes and functions are documented on the same page using their user-facing name (e.g. `pygfx.Display` for `pygfx.utils.Display`).

**Comment by almarklein** [comment]
We could have a page for each subpackage and still show `gfx.Display`, right?

**Comment by FirefoxMetzger** [comment]
We could have a summary list for the main namespace that links to the docs in the sub-package. The downside to this is that we would have to manually maintain this list. 

Alternatively, we could duplicate the documentation and have the docs generated for both `gfx.Display` and `gfx.utils.Display`. I personally don't like this option very much, but am suggesting it here anyway for completeness.

**Comment by almarklein** [comment]
> We could have a summary list for the main namespace that links to the docs in the sub-package. The downside to this is that we would have to manually maintain this list.

Ah, because then we cannot simply autodoc the whole module. I like the idea of documenting per subpackage, to have somewhat smaller chunks, and we can introduce things a bit in the subpackage's docstring. We can start with `automodule`, to make it easy, despite causing the objects to contain the subpackage name. @Korijn what do you think?

**Comment by FirefoxMetzger** [comment]
I started putting something together in https://github.com/pygfx/pygfx/pull/430 .

Here is a link to the rendered docs on how I would do it (not finished, but you get an idea of what I am aiming at):
https://pygfx--430.org.readthedocs.build/en/430/reference.html

**Comment by almarklein** [comment]
Only the subpackage `geometries` is populated now, right? I like how that works! Is the idea that the root reference page only links to the pages for the subpackages (because you removed some objects, but not all)?

**Comment by FirefoxMetzger** [comment]
Yes, I am currently working my way through the individual functions in `geometries` to make sure that they are part of the docs and that they have a good enough docstring. After that I will have a go at the remaining modules.

>  Is the idea that the root reference page only links to the pages for the subpackages

Sort of. The idea for the root page is to have two segments: (1) a table with all the items in the root namespace (this is the thing I suspect most users will be searching for), and (2) a list of sub-packages with links to their respective documentation (on a new page).

> (because you removed some objects, but not all)

I removed some objects, because they were causing a duplicate generation of the same function in different places. This causes a warning in sphinx which in turn fails our CI. For now (to give a quick demo) I commented those duplicate entries.

Eventually, I want to remove most of the objects in the bottom and only link to individual sub-package pages. If we can't use an alias for the list of items in the main namespace, then we could also consider placing the docs for those elements below those lists to continue allowing Ctrl+F searching for things; however, this is something to figure out later on.

**Comment by Korijn** [comment]
> @Korijn what do you think?

I'm following your work here and don't have a strong opinion just yet. It's important to me that it steers newcomers towards the right choices.

Also, maybe as a reference, I've always found the reference docs for three.js pretty easy to navigate: https://threejs.org/docs/
