### ISSUE TITLE
TextGeometry doesn't conform to geometry naming scheme

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#429]
The new `TextGeometry` is a class and thus doesn't match our current naming scheme for the other geometries, which are all functions, e.g., `box_geometry`. Would it make sense to introduce a thin wrapper function `text_geometry` which calls `TextGeometry` to keep the names consistent?

**Comment by almarklein** [comment]
Yes, we decided on making it a class, so we can give it settable properties. Can't we just document alongside `Geometry`?

**Comment by FirefoxMetzger** [comment]
That's what I'm doing for now, but I figured I'd point it out because it breaks the current pattern in the API. In that case, let's leave it as is :)
