### ISSUE TITLE
Move some objects out of the root namespace

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#438]
In #430 we can see some objects being documented that are really meant for internal usage. These should not be present in the root namespace.

* `id_provider`
* `RenderFunctionRegistry`

And then there are objects that power-users need when creating custom shaders. These objects should be in a sensible subpackage (probably `pygfx.renderers.wgpu`). Perhaps we can (at some point) have extended docs specific for these users.

* `register_wgpu_render_function`
* `register_svg_render_function`

Specific cases:
* `pillow_image()` (defined in `pygfx.materials`): It converts a PIL image to a Texture. I propose to rename to `texture_from_pillow_image` and move to the utils subpackage. I don't think it needs to be present in the global namespace.

**Comment by FirefoxMetzger** [comment]
I agree with all of the above.
