### ISSUE TITLE
How to deal with lack of RGB texture format

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#44]
This is similar to #42 

Textures in wgpu can be scalar, 2-channel or 4 channel. There are no RGB textures. We currently simply raise an error when NxMx3 data is provided. But many images are in RGB format by default, and having to append a channel with numpy is annoying. So perhaps we should automatically convert the data. Either in the Texture (the wrapper class), or as we upload the data.

**Comment by ivoflipse** [comment]
Good question on where to handle it.

I prefer being explicit so they'd have to tell us the data is RGB, then we can convert it to RGBA with the A set to all 1s. 

Instead of checking if the dim is 3 and then converting it automatically, because the user may not like our default behavior and wouldn't have a way of overriding it.

But then again, I don't know what other kinds of data users could have, so maybe we don't have to accommodate any other use case (for now)

**Comment by Korijn** [comment]
As long as we don't make it hard for users to "opt out" (or in) automatic behaviour, we're fine, I think

**Comment by almarklein** [comment]
The `Texture.__init__` has a required argument `dim`, so we know when 3d or 2d is intended. When 2D, an NxMx3 array is simply something we can't handle, because there are no texture formats to match that. So I guess an automatic conversion makes sense ...

**Comment by Korijn** [comment]
> The `Texture.__init__` has a required argument `dim`, so we know when 3d or 2d is intended. When 2D, an NxMx3 array is simply something we can't handle, because there are no texture formats to match that. So I guess an automatic conversion makes sense ...

Let's say we have a function that can do the conversion, then we can call it for the user or we can raise a helpful error that refers the user to the conversion function so they can call it.

I guess both are valid choices and they both have different "user friendliness", one "just works" (doesn't raise an error at runtime) and the other doesn't "secretly" perform additional (potentialy costly?) operations.

You could offer a kwarg that disables the automatic conversion and instead raises an error, allowing user to pick the behaviour they prefer.

Does that make any sense or am I just rambling here :)

**Comment by Korijn** [comment]
I could also imagine that users may want to keep a reference to an ndarray and modify it via their own reference? That would only work if our reference is either to the same ndarray or a view.

**Comment by almarklein** [comment]
Yes that makes sense. Though I'm not a fan of a kwarg that defines the behavior on another kwarg :)  

At the moment, the ndarray that is provided is also what gets set in `texture.data` (same reference). We can document that people should reference that instead of their original reference. I dislike it a bit that sometimes it's the same and sometimes not, so I also like the idea of a convenience function. I'll leave this open for a bit for now.

**Comment by Korijn** [comment]
Sure, I don't have any preference either way, just voicing my thoughts :) hope it helps

**Comment by ivoflipse** [comment]
This is probably easier to answer once we have something that uses pygfx in a real world sense

**Comment by almarklein** [comment]
Yes, extra voices help :)  I'm hoping as pygfx takes more shape, one option will come over as more natural :)
