### ISSUE TITLE
Sponza Rendering needs a second look

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#453]
xref: https://github.com/pygfx/pygfx/pull/442#issuecomment-1404951278

Even after adjusting the near plane when rendering the sponza scene, there still seems to be a glitch/bug in the lighting that needs solving:

![image](https://user-images.githubusercontent.com/4402489/218767824-5ae0a7ad-d128-4ec0-93cb-037ef498b0a8.png)

I don't know what the cause is, but could it be that the model of the lamp holder is not closed at the bottom and as such light can slip through?

**Comment by Korijn** [comment]
I think the lights need to be moved up by a fraction, or the near planes of the shadow cameras need to be reduce by a fraction.
