### ISSUE TITLE
Improvements to base materials

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#47]
Generic parameters:

* [x] opacity - 1.0-0.0 float, multiplied with alpha texture map if set. #121
* [x] clipping planes (requires check in every material's fragment shader) #124
* [ ] stencil buffer options
* [ ] alpha testing

**Comment by almarklein** [comment]
@Korijn do we consider stencil-buffer and alpha-testing internal details (not pubic API) for the time being? If so, we can close this if #131 is merged.

**Comment by Korijn** [comment]
Yes, we do consider them internal. We'll revisit the capping example from threejs later
