### ISSUE TITLE
FlyController

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#471]
> Is it a lot of work to also implement fly controls?
> 
>     * W/S move forward/backward
> 
>     * A/D strafe sideways (left/right)
> 
>     * R/F move up/down
> 
>     * Mouse movement controls viewing direction (without holding any mouse buttons down)
> 
>     * Optional:
>       
>       * Q/E rolls camera about the viewing axis
> 
> 
> It's much more convenient to navigate scenes like sponza with this kind of control scheme.

**Comment by Korijn** [comment]
Closed by #504
