### ISSUE TITLE
adding float16 support

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#475]
It would be useful to have float16 support, it seems like it was merged into webgpu last year? https://github.com/gpuweb/gpuweb/pull/2696

This is a bit out of my knowledge, I've just started playing with wgpu and digging into how pygfx works wih wgpu-py, would this be difficult to implement? (I might give it a shot!)

Usecase: reducing VRAM usage for very large tiling of textures.

**Comment by Korijn** [comment]
Closing because we believe this already works.

@kushalkolar feel free to re-open if you disagree.
