### ISSUE TITLE
Lighting artifacts

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#478]
![image](https://user-images.githubusercontent.com/1882046/224282749-beb4cb4b-4a6a-4e7b-b90c-3e6ce82a0fae.png)

This is from the reference screenshots for validate_light_shadow.py

![image](https://user-images.githubusercontent.com/1882046/224283658-df362084-1ab5-4369-870b-8367858e10d8.png)

In the sponza example we see the same effect

Not sure what's causing this

**Comment by almarklein** [comment]
Looks a bit like z-fighting. Maybe a camera helper gets in the way or something?

**Comment by Korijn** [comment]
Closed by #477
