### ISSUE TITLE
metal::packed_float3 is being generated (inappropriately?) and used in expressions without a cast, breaks calls to metal::dot

### ISSUE THREAD

**Issue by sadaszewski** [pygfx/pygfx#480]
See this issue: https://github.com/gfx-rs/naga/issues/1561

Also this: https://stackoverflow.com/questions/54407927/no-matching-function-for-call-to-dot-and-reflect

I had to change:
```
        struct IncidentLight {
            color: vec3<f32>,
            direction: vec3<f32>,
            visible: bool,
        };
...
        struct BlinnPhongMaterial {
            diffuse_color: vec3<f32>,
            specular_color: vec3<f32>,
            specular_shininess: f32,
            specular_strength: f32,
        };
```
to
```
        struct IncidentLight {
            color: vec3<f32>,
            visible: bool,
            direction: vec3<f32>,
        };

...
        struct BlinnPhongMaterial {
            diffuse_color: vec3<f32>,
            specular_shininess: f32,
            specular_color: vec3<f32>,
            specular_strength: f32,
        };
```
in pygfx/renderers/wgpu/_shaderlib.py to get the cube example to run with Metal.

pygfx-0.1.12
wgpu-0.9.4
MacOS 10.14

**Comment by almarklein** [comment]
Thanks for reporting this!

It's odd that the naga issue you linked has been fixed April last year, so that fix should have landed in wgpu-native by now. Also, I'm on a Mac too (MacOS 13.2) but my machine does not express the bug. Any thoughts on that?

That said, the fix seems simple enough. Would you mind preparing a PR for that?

**Comment by sadaszewski** [comment]
Perhaps higher MacOS versions / better hardware support operations like dot() on packed operands? AFAIK the error occurs not because of packed_float3 per se but because dot() cannot operate on this data type. PR: https://github.com/pygfx/pygfx/pull/483
