### ISSUE TITLE
Mipmap questions

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#499]
cc @panxinmiao 

* It appears that when an `env_map` is used for which we dont create mipmaps, the object appears very shiny, as if the metalness is fullout and no roughness. 
* The mipmap generation now happens by simply rendering the image on increasingly smaller views. I wonder if with an unlucky start size, the samples are always mid-pixels, so there is no smoothing taking place. My guess is that it would be better to apply Gaussian smoothing in the fragment shader.

**Comment by panxinmiao** [comment]
> * It appears that when an `env_map` is used for which we dont create mipmaps, the object appears very shiny, as if the metalness is fullout and no roughness.

Yes, In the IBL algorithm, irradiance needs to be sampled from different mipmap levels based on the roughness of the material. If there are no mipmaps, the sampling will default to the highest resolution of the texture (equivalent to roughness always being 0).

> * The mipmap generation now happens by simply rendering the image on increasingly smaller views. I wonder if with an unlucky start size, the samples are always mid-pixels, so there is no smoothing taking place. My guess is that it would be better to apply Gaussian smoothing in the fragment shader.

When generating mipmaps, linear filtering mode was used and the size was reduced only by half each time, so i think the generated mipmaps should be smooth. When sampling irradiance from mipmaps, multiple neighboring mipmap levels are compared and weighted according to the value of roughness to obtain the final irradiance value.

But this is not the completely “physically correct” result (although the difference is small), to obtain the “physically correct” result, we need a more complex technique (compared to simple mipmapping) called  `PMREM` (Prefiltered Mipmap Radiance Environment Maps). PMREM takes into account the angular distribution of the incoming light, resulting in physically accurate reflections and lighting.

**Comment by almarklein** [comment]
> Yes, In the IBL algorithm, irradiance needs to be sampled from different mipmap levels based on the roughness of the material. If there are no mipmaps, the sampling will default to the highest resolution of the texture (equivalent to roughness always being 0).

Aha, thanks for the explanation. So when using an environment map on a standard material, the mipmap feature should be used. I'll add a check for this.

> When generating mipmaps, linear filtering mode was used and the size was reduced only by half each time, so i think the generated mipmaps should be smooth. 

A quick test shows that there is *some* smoothing, but from what I know about scale-space, the linear filtering should not be enough to get the sub-images to represent the correct scale. I'm working on a fix that does something similar as the flusher to perform Gaussian smoothing.

> to obtain the “physically correct” result, we need a more complex technique (compared to simple mipmapping) called PMREM (Prefiltered Mipmap Radiance Environment Maps). PMREM takes into account the angular distribution of the incoming light, resulting in physically accurate reflections and lighting.

If I understand correctly, this would require an external tool to prepare the env map image, correct?

**Comment by almarklein** [comment]
Left is the content at a higher scale. The right is an image of the same resolution, obtained simply by taking every ith pixel from the original (`texture.data[0, ::(2**level), ::(2**level)]`).
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/3015475/230624494-6446b672-4873-47ca-b68e-ef4acac9175b.png">
