### ISSUE TITLE
Picking

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#51]
Either through raycasting or by rendering. Since we can have multiple render targets, and even write to storage textures directly, I prefer the latter.

**Comment by Korijn** [comment]
* Picking by rendering:
  * Doesn't allow picking without rendering
  * Very efficient (runs on GPU)
  * Can only pick in camera view dir and frontmost matter
  * Requires some additional shaders and pipelines probably?
* Picking by raycasting:
  * Can be executed without rendering
  * Not too efficient (runs on CPU)
  * Can pick things behind other objects and along other directions than the camera view dir
  * Requires bounding volume implementation throughout the scene graph
  * Requires ray-bounding volume intersection math

**Comment by Korijn** [comment]
Important point: both approaches have different usecases. We could implement both (long term).

**Comment by almarklein** [comment]
#71 gets us closer!

**Comment by Korijn** [comment]
Picking by rendering is pretty much complete now thanks to #77.

I'll open a new issue to track raycasting by geometry
