### ISSUE TITLE
Viewing data that are already on the GPU 

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#510]
Is there a way to make pygfx work with data that are already on the GPU? Such as tensorflow or torch Tensor arrays. I was looking at how WGPU works with the textures and as far as I understand you give it a texture and then it writes it to GPU (queue.write_texture) But is there a way to make a Texture from a array already on the GPU?

**Comment by Korijn** [comment]
I think it's all scoped to a device object's context ID. I don't think you can acces any memory that is owned by another context. That would be a serious security issue.

**Comment by kushalkolar** [comment]
Ah I see, just read up on CUDA contexts. Is there anything equivalent to interprocess communication that can run on the GPU to send data between a CUDA context and WGPU context (maybe like zmq on GPU?).

Anyways I think I'll benchmark the roundtrip of a cuda torch Tensor -> numpy array -> wgpu texture before seeing if it's really necessary.

**Comment by almarklein** [comment]
> Is there anything equivalent to interprocess communication that can run on the GPU to send data between a CUDA context and WGPU context (maybe like zmq on GPU?).

I have no idea ...

**Comment by Korijn** [comment]
If there is something like that it certainly won't be running on the GPU, it can't run anything sophisticated like that because it's not a CPU. :)

**Comment by kushalkolar** [comment]
Thanks for the details!

Tested it out and roundtrip GPU -> CPU -> GPU is more than fast enough for visualizations. `(4096, 4096)` can be done at at least 30Hz on a RTX 3080 (running on a new Debian install, for some reason it's maxing out at half my vsync, I'll figure that out later).

fpl example but should be same performance with pygfx

```python
import torch
import fastplotlib as fpl
from wgpu.gui.auto import WgpuCanvas
import pygfx

canvas = WgpuCanvas()
renderer = pygfx.WgpuRenderer(canvas, show_fps=True)

plot = fpl.Plot(canvas=canvas, renderer=renderer)

size = (4096, 4096)

img = plot.add_image(torch.cuda.FloatTensor(*size).random_().cpu().numpy(), name="img")

def update(p):
    p["img"].data = torch.cuda.FloatTensor(*size).random_().cpu().numpy()

plot.add_animations(update)
plot.show()

fpl.run()
```
