### ISSUE TITLE
DirectionalLightHelper pointing in the opposite direction

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#513]
While investigating the light bug in #482 I noticed that (on main) the light indicators for directional lights are pointing in the wrong direction. The arrow tip points towards _positive_ Z while the light shines along _negative_ Z (as it should).

![image](https://user-images.githubusercontent.com/4402489/233163775-f60700d2-3174-4020-8302-4686b13cfd54.png)

**Comment by almarklein** [comment]
Aha, I suspect that when we changed the lights to point in -Z we forgot to update the helpers.

**Comment by FirefoxMetzger** [comment]
I think this got fixed by #482 since the PR declares that all lights use camera space. (forward is minus Z)

![image](https://user-images.githubusercontent.com/4402489/235293831-1251a988-7846-4ff7-ba8b-fd3b8140fc71.png)

**Comment by almarklein** [comment]
Nice how this solved itself "naturally" :)
