### ISSUE TITLE
Rotation Handles of Gizmo have wrong color in mode "screen"

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/pygfx#515]
While exploring the gizmo behavior on main (to make sure I port it correctly) I noticed that the colors of the rotation handles are switched when selecting the mode "screen":

![image](https://user-images.githubusercontent.com/4402489/233553411-0e618517-66a7-4d99-924c-68cfeda0977b.png)

**Comment by almarklein** [comment]
I think it's correct. The color of the rotation handles are that of the axis around which it rotates. The blue axis is the camera view direction.

**Comment by almarklein** [comment]
I think the confusion may stem from the fact that the rotation-arc is not drawn, and only the axis is shown.
