### ISSUE TITLE
Feature Request: Ability to paint Mesh Faces, and vertex size for Meshes

### ISSUE THREAD

**Issue by sharon92** [pygfx/pygfx#534]
`gfx.Geometry` lets you set colours on each vertex. It would be nice to be able to paint element faces, i.e colours should be the size of `geometry.indices` . 

Use case - Hydraulic Modelling, every element has different roughness coefficient. In the river bed, for example roughness=20, and in foreland 10.

Right now I draw a wireframe mesh, then sort the unique roughness factors and overlay the wireframe mesh with flat shading.

So for a mesh with 20 different roughness coefficients. I paint the whole mesh 2 times in 21 loops. First loop is wireframe, then 20 loops with unique areas of the whole mesh.

In wireframe mode in `gfx.Mesh` the sizes of geometry don't take any effect. It would be nice to customize the vertex sizes in wireframe mode.

**Comment by Korijn** [comment]
> `gfx.Geometry` lets you set colours on each vertex. It would be nice to be able to paint element faces, i.e colours should be the size of `geometry.indices` .

Assigning per-face attributes is only possible if you don't share vertices between triangles, allowing you to set a face's color by assigning it to all three vertices of that face.

You can already do this, and there isn't any other way to go about it

**Comment by almarklein** [comment]
Hacking the mesh fragment shader:
```py
            //let out_color = vec4<f32>(physical_color, opacity);
            let out_color = vec4<f32>(0.0, 0.1 + 0.1 * f32(varyings.pick_idx), 0.0, 1.0);
```
and then running the cube example (2 faces per side):
<img width="473" alt="image" src="https://github.com/pygfx/pygfx/assets/3015475/a1d2cf52-db31-439e-b11a-79de038116a5">

**Comment by sharon92** [comment]
> Actually, I think it is. We already do picking based on the face index. The vertex shader runs once for each index (in the index buffer). The appropriate vertices are looked up, but each 3 corners (or 4 for quads) of each face run separately.

nice. Anyway I could help with this? If you point me to the code I can try my luck.

> What do you mean with vertex size? Are you perhaps looking for `wireframe_thickness`?

For example in SMS (Aquaveo) I can customize the vertex color and diameter, and color and thickness of edges separately:
![image](https://github.com/pygfx/pygfx/assets/51754340/4868521d-7caa-4c09-9f42-1700818a1b8c)

**Comment by sharon92** [comment]
>  You can actually use the same geometry object so you don't have to replicate the data.

oh thats good to know. So if i first instantiate 

`points = gfx.Geometry(positions=data)`

I can plot the points using this and then if I draw the triangles using

`points.indices = index`

`gfx.Mesh(points, material)`

the `positions` wont be copied? If so I can reuse the geoms for all the objects I am using because they rely on the same vertices.

**Comment by almarklein** [comment]
> `points.indices = index`

I think the simplest solution is to create the mesh in the way you already do, and then use the same geometry for the Points.
```py
mesh = Mesh( .. )
points = Points(mesh.geometry, PointsBasicMaterial(..))
```

The points will only use the `positions` field. For completeness, this would also work:
```py
mesh = Mesh( .. )
points = Points(
    gfx.Geometry(positions=mesh.geometry.positions, .. ),
    gfx.PointsBasicMaterial( .. ),
)
```

In this case they have separate geometry objects, but still use the same buffer for the positions. This would be a solution if both objects used other fields from the geometry which you *don't*  want to share (technically they both can use `texcoords` and per-vertex `colors`).

> You could actually create a WorldObject subclass that manages two child objects

Yeah, like a higher level compound `WorldObject`. Or just use a `gfx.Group` which has the Points and Mesh as children. Whatever works easiest in your use-case.

**Comment by sharon92** [comment]
@almarklein @Korijn 

I was able to paint face colors in my branch. I added a keyword `face_colors` in ` _mesh.py` and for it to work I need to supply `colors` and `texcoords` in `geometry` object.  (face_colors needs to be true and vertex_colors needs to be false)

`texcoords` supply the index and `colors` is the color to the index in `texcoords`

Screenshot:
![image](https://github.com/pygfx/pygfx/assets/51754340/0d9b6cf7-80c3-43b5-af1a-cf477db74169)

I have updated the example in my fork if you are interested in checking it out :)
