### ISSUE TITLE
Fastest way to add or remove thousands of WorldObjects 

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#538]
I have the following use case:

We display thousands (2,000 - 3,000) of Line objects (they are contours around neurons) like what you see in the top left Subplot here: https://user-images.githubusercontent.com/9403332/210027199-6e4ac193-6096-4d18-80d5-a41591ea4d4f.gif

We want to rapidly make a subset of them visible or not visible, for example make a subset of 500 Line objects visible and the rest not visible, and we want this to work at a speed of at least 10 Hz because it's linked to user interaction. 

I have tried adding and removing the Line world objects from the scene in a for loop but this is slow. I also tried changing the visibility. Is there a way to change "bulk" visibility very quickly?

Will make a minimal example later today if that helps.

**Comment by Korijn** [comment]
Put them in a separate scene and just don't render it.

**Comment by panxinmiao** [comment]
I think what you are looking for is the `Group` class. You can use the `Group` class to group objects together and control their visibility by setting the "visible" property of the `Group` to show/hide the objects.

**Comment by Korijn** [comment]
Well, with threejs you have something called "LineSegments" which you provide with start/end pairs for geometry. Every line segment is then independent. I guess I thought we supported that already, but maybe we don't. :)

**Comment by almarklein** [comment]
Ah, yes, could also use `gfx.LineSegmentMaterial`! Though it could be that if you make the lines semi-transparent, you might get artifacts due to overlapping fragments (would have to check whether this is actually the case).

**Comment by kushalkolar** [comment]
It seems like making a single `Line` world object with `LineMaterial` and changing the alpha is very fast, however it's not as nice as having individual objects and I have to get rid of the line joining adjacent circles. From the [line segements example](https://github.com/pygfx/pygfx/blob/main/examples/feature_demo/line_segments.py) I can't figure out how to set an arbitrary start-stop for each segment. 

I'm guessing there isn't a fast way to do this with individual world objects? If not then I'll create an abstraction for managing these in a similar way to the current `LineCollection` in `fastplotlib`, which is mostly a `pygfx.Group` with some additional high level functionality.

This is what I'm trying to do:

https://github.com/pygfx/pygfx/assets/9403332/62c84cbb-d030-4620-b4aa-02afa46d8ca7

With regular `pygfx.LineMaterial` and `map_interpolation="nearest"` I get these artifacts where there would be overlapping fragments

alpha set to `0` at the positions that join two circles:
![image](https://github.com/pygfx/pygfx/assets/9403332/d8ca43dd-6537-4ac5-b9c5-cb8e8286b742)

Those artifacts are exactly between the join points of circles:
![image](https://github.com/pygfx/pygfx/assets/9403332/d710da95-b300-4c08-af1f-2c2a2dcd830c)

Entire scene just to highlight the points between adjacent circles:
![image](https://github.com/pygfx/pygfx/assets/9403332/475c1f33-2142-4989-93ac-6d7578c34312)


```python
def set_visible_alpha(ev):
    ixs_visible = ev.pick_info["selected_indices"]
    ixs_hide = np.setdiff1d(np.arange(len(circles)), ixs_visible)
    
    # over here each circle is 50 points, but for our real data this will be arbitrary
    for i in ixs_visible:
        contours.world_object.geometry.colors.data[i * 50:(i * 50) + 50, -1] = 1
        
    for i in ixs_hide:
        contours.world_object.geometry.colors.data[i * 50:(i * 50) + 50, -1] = 0

    contours.world_object.geometry.colors.update_range()

# fpl selector on heatmap in right subplot
selector.bounds.add_event_handler(set_visible_alpha)
```

Using a "holder" scene to put objects we don't want to render is slow, this takes ~500ms, and profiling showed that ~200ms is spent in `for i in ixs_visible` and the `Group.add` calls.

```python
holder_scene = pygfx.Scene()

`contours.world_object` is a `pygfx.Group` that holds all the circle lines.
`contours.graphics` is a regular `list` that has all the circle lines as well.
def set_visible(ev):        
    # get ixs that should be visible
    ixs_visible = ev.pick_info["selected_indices"]
    
    # add back anything that should be visible
    for i in ixs_visible:
        if contours.graphics[i].world_object in holder_scene.children:
            contours.world_object.add(contours.graphics[i].world_object)
    
    # get things to hide
    ixs_hide = np.setdiff1d(np.arange(len(circles)), ixs_visible)
    # hidden lines    
    hidden_objs = [contours.graphics[i].world_object for i in ixs_hide]
    # add to non-rendered scene
    holder_scene.add(*hidden_objs)
```

**Comment by kushalkolar** [comment]
If you saw the the original version of the above reply please ignore, I was setting vertex colors as `0` instead of just the alpha which is why it looked like there were fragment artifacts, there actually aren't any!

**Comment by Korijn** [comment]
> From the line segements example I can't figure out how to set an arbitrary start-stop for each segment.

Given your observations so far, I'd say this should be your focus at this point!

**Comment by kushalkolar** [comment]
From the shader it just segments it out into chunks of 5:

https://github.com/pygfx/pygfx/blob/c3e6f85b0bd339a17c36b31d895f6676c204b436/pygfx/renderers/wgpu/lineshader.py#L461-L467

I will think more about this later, but the simplest thing could be to pass a list of tuples of `(start_i, end_i)` indices for each segment to `LineSegmentMaterial`, and in the shader anything between `end_i` and `start_i - 1` is degenerate triangles.

**Comment by kushalkolar** [comment]
Ah, but then isn't it only going to create straight lines betweens the pairs of points? What I need is:

```python
[[seg_1_pos_1, seg_1_pos_2, ..., seg_1_pos_n, seg_2_pos_1, seg_2_pos_2, ...]]
```

where each segment can be of arbitrary length.

**Comment by Korijn** [comment]
> Ah, but then isn't it only going to create straight lines betweens the pairs of points? What I need is:
> 
> ```python
> [[seg_1_pos_1, seg_1_pos_2, ..., seg_1_pos_n, seg_2_pos_1, seg_2_pos_2, ...]]
> ```
> 
> where each segment can be of arbitrary length.

I think that would get you the result you need?

**Comment by panxinmiao** [comment]
For your use case, another option is to use InstancedObject. However, it seems that the current implementation of InstancedMesh in pygfx only supports setting the local transformation matrix of instances. Therefore, if you want to set other instance properties such as color or visibility, you may need to extend the class yourself and implement the corresponding methods.

**Comment by kushalkolar** [comment]
> > Ah, but then isn't it only going to create straight lines betweens the pairs of points?
> 
> I think that would get you the result you need?

For example if I modify the line segments example and draw circles it produces ths, I'm looking for circles which are complete but only the points between the circles are not draw. The circles can each have arbitrary numbers of points:

![image](https://github.com/pygfx/pygfx/assets/9403332/1a1e8487-9c63-4c70-8804-e537e02f8105)


```python3
"""
Line Segments
=============

Display line segments. Can be useful e.g. for visializing vector fields.
"""
# sphinx_gallery_pygfx_render = True

import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx
from itertools import product


canvas = WgpuCanvas()
renderer = gfx.WgpuRenderer(canvas)

scene = gfx.Scene()


def make_circle(center, radius: float, n_points: int = 75) -> np.ndarray:
    theta = np.linspace(0, 2 * np.pi, n_points)
    xs = radius * np.sin(theta)
    ys = radius * np.cos(theta)

    return np.column_stack([xs, ys]) + center


spatial_dims = (20, 20)

circles = list()
for center in product(range(0, spatial_dims[0], 15), range(0, spatial_dims[1], 15)):
    circles.append(make_circle(center, 5, n_points=75))

pos_xy = np.vstack(circles)

positions = np.column_stack([pos_xy, np.zeros(pos_xy.shape[0])]).astype(np.float32)

colors = np.random.uniform(0, 1, (positions.shape[0], 4)).astype(np.float32)
geometry = gfx.Geometry(positions=positions, colors=colors)

material = gfx.LineSegmentMaterial(
    thickness=6.0, color=(0.0, 0.7, 0.3, 0.5), vertex_colors=False, map_interpolation="nearest"
)
line = gfx.Line(geometry, material)
scene.add(line)

camera = gfx.OrthographicCamera(maintain_aspect=False)
camera.show_object(line)

controller = gfx.PanZoomController(camera, register_events=renderer)


if __name__ == "__main__":
    canvas.request_draw(lambda: renderer.render(scene, camera))
    run()
```

**Comment by Korijn** [comment]
> For example if I modify the line segments example and draw circles it produces ths, I'm looking for circles which are complete but only the points between the circles are not "visible". 

Is it feasible to postprocess the geometry to create the shapes you want? Seems simple enough?

**Comment by almarklein** [comment]
>  I'm looking for circles which are complete but only the points between the circles are not "visible"

To extend on what Korijn said, you'll need to create a new positions array that is about twice as long, because each end-point will also have to be the next start-point if you want a contiguous line. And then you have to end in such a way that the line between two circles is in a gap between two segments ;)

About using alpha: that works, but you probably get a better result by using a position that is `[nan, nan, nan]`. I just tested, and this indeed introduces a hard gap in the line. Only no nice caps, this is something we could probably fix in the shader.

About the holder scene: the way this could work is to have 2 (or more) static scenes that you can render or not render. Moving objects from one scene to the other is not going to be fast.

----

All this said ... I think there is a slight misunderstanding (at least on my part): when you said "We want to rapidly make a subset of them visible or not visible"  I think I assumed that set to be static, but your video indicates that this set can be different every time - or can they still be grouped somehow, i.e. are there multple circles that are always visible/invisible together?

If you want to switch visibility on a fine-grained level, my thoughts actually turn towards the `wobject.visible` property. You said in the top post that you had tries that. Was there a problem with it?

**Comment by kushalkolar** [comment]
Thanks! I now understand how I could use pairs of positions, I'll just stick to a `nan` point between segments because then it's an almost 1-1 mapping between the real data positions and the buffer, we want to easily change things like the color after drawing.

`nan` works well and doesn't create the notches :smile: 

![image](https://github.com/pygfx/pygfx/assets/9403332/00c7f3e2-0d5a-4eb1-8313-19ec4e6084f4)

> About the holder scene: the way this could work is to have 2 (or more) static scenes that you can render or not render. Moving objects from one scene to the other is not going to be fast.

Ah ok, so basically adding or removing thousands of objects from a scene is never going to happen under ~30ms?

> All this said ... I think there is a slight misunderstanding (at least on my part): when you said "We want to rapidly make a subset of them visible or not visible" I think I assumed that set to be static, but your video indicates that this set can be different every time - or can they still be grouped somehow, i.e. are there multple circles that are always visible/invisible together?

Yes, we want to be able to abitrarily make large numbers of object visible or not visible, they are not grouped. I'll elaborate on the usage tomorrow, I made a new prototype class in `fastplotlib` to manage segements of a single `pygfx.Line` without changing the API and it works quite well, it takes ~30ms for changing 2000 lines (on an old RX 470 GPU).

Thanks for the discussion and all the details! I hope it's also useful for future users when deciding a strategy for drawing a large number of objects.

> If you want to switch visibility on a fine-grained level, my thoughts actually turn towards the wobject.visible property. You said in the top post that you had tries that. Was there a problem with it?

Yes I tried this and it was quite slow, I think it took ~300ms for changing visibilities of a few thousand lines. I can post some detailed profiles later.

**Comment by Korijn** [comment]
I'm confused. `nan` works well? I don't think we've (consciously at least) made an effort to support that?

**Comment by kushalkolar** [comment]
I'll get back to this in a week, busy and moving at the end of the month.

> I would recommend to use cprofile and snakeviz to profile the code that you're running and inspect a flamegraph. If you can, share the cprofile file here. We might spot a very easy way to make it run much faster.

Yup, I use [`viztracer`](https://github.com/gaogaotiantian/viztracer) these days.

> This is surprising ... I just tried, and can change the visibility prop on 1000 objects in under 3ms.

I'll try this again.

> Did you only measure the time needed to change the line? Note that these changes are synced to the GPU right before the next draw, and this will add a bit of overhead as well.

included the `update_range()` in the time, basically:

```python
t1 = time()

line.geometry.color.data[start:stop, :-1] = 0
line.geometry.color.update_range(start, size=stop)

elapsed = time() - t1
```

**Comment by almarklein** [comment]
> Is there a better way?

Calling `update_range()` only marks what part of the buffer/texture needs to be synced. The renderer applies the syncing right before it draws. There is no one-liner to force the sync early, but you could do this to get more realistic timings:
```py
        from pygfx.renderers.wgpu._update import update_resource
        for buffer in all_buffers_that_need_to_be_synced:
             update_resource(buffer)
```

**Comment by kushalkolar** [comment]
I think I figured this out. I'm not only changing the visibility of 1000 objects, I'm also setting the visibility of the other several thousand objects based on the the selector tool on the right. The slowdown was from an indexer object and for loops I was using to slice lines that should be visible or not. I've resorted to just storing the lines within numpy arrays to give me fancy indexing :smile: 

This takes 10 ms, `contours.graphics` is a numpy array of fastplotlib Graphic objects which manage the `pygfx.WorldObject`

```python
for g in contours.graphics[ixs_visible]:  # graphcis is a numpy array
    if not g.visible:
        g.visible = True  # just refers to WorldObject.visible
    
for g in contours.graphics[ixs_hide]:
    if g.visible:
        g.visible = False
```

https://github.com/pygfx/pygfx/assets/9403332/5e709c82-4b6c-493b-9bf1-45016028fb75

**Comment by kushalkolar** [comment]
Closing, here's the real usecase. The linear region selector on the top right heatmap is moved, and that changes the visible contours on the "mean" subplot on the left. This was via remote use through the internet, it's much faster locally on LAN. :smile: 

https://github.com/pygfx/pygfx/assets/9403332/8d391e55-9760-452c-b8bb-d06c80671d37
