### ISSUE TITLE
PyPi version is different?

### ISSUE THREAD

**Issue by Choons** [pygfx/pygfx#545]
trying to get started with pygfx and noticed if I install with "pip install -U pygfx glfw" that the examples in this repo largely don't work, but if I do the development install of this repo with pip they work fine.

**Comment by Korijn** [comment]
Yes, that's right, we're still in the version 0 range, so there's no API stability guarantees just yet. See https://semver.org/

We could consider performing another release soon though, @almarklein?

Either way, @Choons, are you implying an expectation that we release every commit to the master branch of this repo to pypi? It seems a bit extreme.

**Comment by Choons** [comment]
I'm not implying anything. You may simply want to update your read me install instructions to not show a non-working example right after you tell people to install with pip.

**Comment by Korijn** [comment]
Alright, we can consider that. I think we will start guaranteeing stability once we hit v1.0.0 in accordance with the semantic versioning scheme. For now it's all still under construction.

**Comment by Choons** [comment]
OK, thanks. pygfx looks like it could be really great-- something Python has been sorely missing in the graphics field. Looking forward to learning it.

**Comment by Korijn** [comment]
> OK, thanks. pygfx looks like it could be really great-- something Python has been sorely missing in the graphics field. Looking forward to learning it.

I'm glad to see we are not the only ones with that feeling of a gaping hole in Python's ecosystem!

**Comment by almarklein** [comment]
> [...] not show a non-working example right after you tell people to install with pip

Fair point 😄

**Comment by Korijn** [comment]
I wanted to add for future readers, you can also view the repo at the time of the last release, like so:

![image](https://github.com/pygfx/pygfx/assets/1882046/3b10ff34-317e-4d14-bb51-362c3e01de7f)

That way everything you can read on the repo will be compatible with the corresponding release on pypi.

**Comment by almarklein** [comment]
I think we've resolved this issue via #546, #547, and the a new release 🚀
