### ISSUE TITLE
Tolerance for picking

### ISSUE THREAD

**Issue by sharon92** [pygfx/pygfx#552]
Is there a way to implement a tolerance for picking?

To pick points, I want to get a search radius (tolerance) under the mouse and return the nearest point.

Or a way to pick points by rectangles which are drawn by dragging the mouse over the canvas?

**Comment by Korijn** [comment]
See #407

**Comment by sharon92** [comment]
@Korijn cool! Thanks :)

**Comment by kushalkolar** [comment]
[This example](https://github.com/pygfx/pygfx/blob/main/examples/feature_demo/image_click_events.py) shows how to get 3 nearby points, but you can just return all objects using a distance threshold.

**Comment by sharon92** [comment]
@kushalkolar Thanks for the link! Yeah I didnt think enough. With Click events I can make a search radius myself perfect!
