### ISSUE TITLE
How to support functionality that requires specific wgpu features/extensions

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#569]
## Introduction

So wgpu by itself is pretty complete, but it does come with a set of extensions that can be enabled to unlock certain features. In wgpu these extensions are called "features".

We already require one such feature: the TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES enables (amongst other things) interpolating samplers for float32 textures (a feature that's important for sciency use-cases). We now enable this by default in wgpu-py.

Recently another case came up for supporting writable buffers (with "storage" binding type), in #567.

## Current state

So far, we have no way to enable specific features in pygfx. The features that are enabled, are always enabled. This means though, that some use-cases (as in #567) are not possible.

### Expose extensions in pygfx

My initial thought was to simply provide API for the user to provide wgpu-features, e.g. via the initializer of the renderer.

A possible downside, however, is that this results in code that may not work on all hardware, which defeats one important aspect for why we use wgpu in the first place: we want the same visualization to run everywhere and look the same.

Another issue is that there is one device per process, so the features must be enabled "from the start", which may result in some annoyances especially in interactive sessions (e.g. copying a piece of code into your notebook and then having to add code to the beginning, and restart the notebook to be able to run it).

### Enable a subset of features by default

This is basically what we do know, but we'd select more features. We can then be clear on what functionality is supported and what not. This won't be set in stone (we can enable more features later), but at least we can document it.

A possible downside is that pygfx won't even start on hardware that does not support all the required features (even if the visualization to run does not use them).

A thing to take into account is that at some point people may manage to run pygfx in the browser via Pyscript. At that point, any device with a browser may become a device we want to support.

I think we should do some research on how these features map to devices. Is there a subset that's safe to enable that covers a lot of ground?

### Simpler Tier system

If we cannot get away with defaults, we could also setup a systems of 2 or 3 tiers. So tier 1 enables most/all standard visualizations, and runs on all devices, tier 2 unlocks fancy features but does not work on mobile devices, etc.

----

### As known in wgpu-core

https://docs.rs/wgpu/latest/wgpu/struct.Features.html - this page also contains some more details, such as what backends and hardware the feature is available on.

### As defined by webgpu

https://gpuweb.github.io/gpuweb/#gpufeaturename

    ["depth-clip-control"](https://gpuweb.github.io/gpuweb/#depth-clip-control),
    ["depth32float-stencil8"](https://gpuweb.github.io/gpuweb/#depth32float-stencil8),
    ["texture-compression-bc"](https://gpuweb.github.io/gpuweb/#texture-compression-bc),
    ["texture-compression-etc2"](https://gpuweb.github.io/gpuweb/#texture-compression-etc2),
    ["texture-compression-astc"](https://gpuweb.github.io/gpuweb/#texture-compression-astc),
    ["timestamp-query"](https://gpuweb.github.io/gpuweb/#timestamp-query),
    ["indirect-first-instance"](https://gpuweb.github.io/gpuweb/#indirect-first-instance),
    ["shader-f16"](https://gpuweb.github.io/gpuweb/#shader-f16),
    ["rg11b10ufloat-renderable"](https://gpuweb.github.io/gpuweb/#rg11b10ufloat-renderable),
    ["bgra8unorm-storage"](https://gpuweb.github.io/gpuweb/#bgra8unorm-storage),
    ["float32-filterable"](https://gpuweb.github.io/gpuweb/#float32-filterable),

### As defined by webgpu.h

https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.h#L333

    WGPUFeatureName_DepthClipControl = 0x00000001,
    WGPUFeatureName_Depth32FloatStencil8 = 0x00000002,
    WGPUFeatureName_TimestampQuery = 0x00000003,
    WGPUFeatureName_PipelineStatisticsQuery = 0x00000004,
    WGPUFeatureName_TextureCompressionBC = 0x00000005,
    WGPUFeatureName_TextureCompressionETC2 = 0x00000006,
    WGPUFeatureName_TextureCompressionASTC = 0x00000007,
    WGPUFeatureName_IndirectFirstInstance = 0x00000008,
    WGPUFeatureName_ShaderF16 = 0x00000009,
    WGPUFeatureName_RG11B10UfloatRenderable = 0x0000000A,
    WGPUFeatureName_BGRA8UnormStorage = 0x0000000B,
    WGPUFeatureName_Float32Filterable = 0x0000000C,

### Extra features for native

https://github.com/gfx-rs/wgpu-native/blob/trunk/ffi/wgpu.h#L19

    WGPUNativeFeature_PushConstants = 0x60000001,
    WGPUNativeFeature_TextureAdapterSpecificFormatFeatures = 0x60000002,
    WGPUNativeFeature_MultiDrawIndirect = 0x60000003,
    WGPUNativeFeature_MultiDrawIndirectCount = 0x60000004,
    WGPUNativeFeature_VertexWritableStorage = 0x60000005,

**Comment by almarklein** [comment]
As for the feature we currently have set by default: we do this mostly (only?) to get filterable float32, for displaying images and (more importantly) volume rendering on f32 data.

The specs do mention "Float32Filterable", but this is not yet implemented in wgpu-core (see https://github.com/gfx-rs/wgpu/issues/2170). So for now we use `TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`, which represents a collection of features related to textures. However, this one is native-only, so it would be better if we can eventually use an "official" webgpu feature.

**Comment by almarklein** [comment]
Skimming through https://docs.rs/wgpu/latest/wgpu/struct.Features.html, some features only work on Vulkan, some only on native (not web), some on Vulkan and dx12 (not meta/osx), etc. 

My current stance: it would be a shame if we could not provide power-users with everything that their hardware is capable off. At the same time we should make it clear that using an extension may limit where the visualization can run.

My suggestion would be to introduce `gfx.enable_wgpu_features()` that must be called before the first renderer is created. Maybe that function could return a summary of the consequences of using the requested features, e.g. cannot run on Metal, can only run native, etc.

We could additionally do the tier-idea, e.g. by allowing `gfx.enable_wgpu_features("native")` and it would enable all native features that are supported by matal/dx12/vulkan.

Also, we should enable `TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES` in pygfx, not wgpu-py.

**Comment by Korijn** [comment]
Three.js requires a number of webgl features in order to run, and allows users to enable more just by specifying which features they want. I don't think they even document this.
