### ISSUE TITLE
OrthographicCamera + FlyController: w + s don't work.

### ISSUE THREAD

**Issue by JonathanCSmith** [pygfx/pygfx#577]
Not sure if I've done something odd, but I get unexpected behaviour when combining these two. There does seem to be some changes to the frustrum (rendered objects get clipped) but the actual camera perspective doesn't shift.

**Comment by almarklein** [comment]
In contrast to a perspective projection, with an orthographic projection distant object appear equally large as objects near to the camera. Therefore, moving forwards or backwards has no visible effect, apart perhaps from objects moving in and out the viewing frustrum (depth range).

The OrthographicCamera is therefore not a good match for the fly controller. I'd recommend using a PerspectiveCamera instead.
