### ISSUE TITLE
Wheel event inconsistencies

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#583]
The wheel event object has properties like `button`  and `buttons`, but they are always zero and the empty tuple, respectively. The reason is that the wgpu event dict does not have these fields for the wheel event, but the PyGfx event object does, because it inherits from `PointerEvent`, so we always get their defaults.

This is confusing, because it looks like the event is broken.

**Comment by Korijn** [comment]
It's consistent with web standards though: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent

WheelEvent inherits MouseEvent which includes said properties

**Comment by almarklein** [comment]
Fixed upstream (just need a release of wgpu-py and jupyrer_rfb:
* https://github.com/vispy/jupyter_rfb/pull/78
* https://github.com/pygfx/wgpu-py/pull/397

**Comment by almarklein** [comment]
Can close
