### ISSUE TITLE
API for transforming a world object

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#60]
Regardless of how we implement transformations, there are (at least) two ways that the WorldObject API can be:

* Using `wobject.position`, `wobject.rotation` and `wobject.scale` as we do now. One can set either, and they are composed "under the hood". This is similar to how one can set these properties in a tool like blender.
* Using `wobject.transform`, e.g. `ob.transform = Translation(3,4,5) * Rotation.from_euler(...)`.

The former is nice, as one can individually set and update the translation and rotation. The latter is nice, because one can compose the current transform with a new transform.

**Comment by almarklein** [comment]
The former is probably better because its similar to what ThreeJS and e.g. Unity do.

**Comment by Korijn** [comment]
If we introduce the matrix auto update flag, like there's has, you can have both. That flag can be set by users who would rather directly set the matrix property.
