### ISSUE TITLE
Improve buffer/texture update_range

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#600]
During the work in (https://github.com/pygfx/gfxmorph) we realized two issues:

* It would be nice if the uploading of data could be more precise, rather than uploading the full range from minimal to maximal index. The most obvious solution is to define chunks to get a balance between number of upload calls and the size of the uploads.
* It may be convenient to specify indices to upload using a mask or list of indices, rather than a min-max-range.
* We observed that when using update_range to do precise uploads, some indices that changed were not updated, resulting in glitches. We've not yet found the cause, but it may be in pygfx.
* Also make a benchmark test, so we can compare speeds.
* Look into using the queue and e.g. buffer mapping. Note that `buffer.map()` is the busy-wait-sync version of `buffer.map_async()`, perhaps that makes it slow. On the other hand, using the async version might make things fast.
* See https://github.com/fastplotlib/fastplotlib/pull/473#issuecomment-2119817761 for some logic we can probably re-use from fpl.

**Comment by kushalkolar** [comment]
This could be useful! Right now in fastplotlib, if precise indices are provided (such as with a binary mask with arbitrary indices), `update_range()` is just called for each one. I haven't benchmarked the performance since we haven't run into any yet. 
 https://github.com/fastplotlib/fastplotlib/blob/master/fastplotlib/graphics/_features/_base.py#L328

**Comment by almarklein** [comment]
Thought that I had from #666: right now we check for updates right before a frame, which means that the drawing is delayed, and this delay may be variable. We could also update date right after a frame is rendered, resulting in a more stable fps. A downside might be that the display of new data is delayed. So should probably be optional? Also relates to https://github.com/pygfx/pygfx/issues/495.

**Comment by hmaarrfk** [comment]
I think the reason that parts of the texture were not updated has to do with data alignment on the GPU
