### ISSUE TITLE
API for volumes

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#63]
### Based on meshes

Like Three-JS, we're very much oriented to rendering meshes. In the below code, you create a cube, to which you apply a material, which has the 3D texture as a map.

For rendering a slice through a 3D volume this makes sense; you can make arbitrary geometry, and the (3D) texcoords can sample the mesh in any way you want. This can be done with `MeshBasicMaterial` (implemented in #62).

For 3D we'd need a different material to indicate that the renderer should do some raycasting.

```py
tex = gfx.Texture(vol, dim=3, usage="sampled")
view = tex.get_view(filter="linear")
material = gfx.MeshVolumeMaterial(map=view, clim=(0, 255))
geometry = gfx.CubeGeometry(...)
geometry.texcoords = .....
volume = gfx.Mesh(geometry, material)
```

### Using a Volume world-object -> the geometry is implicit

For actual 3D rendering the above feels awkward (to me). You let the user specify positions and texcoords, while these are fully determined by the volume shape. The below makes the geometry implicit:

```py
tex = gfx.Texture(vol, dim=3, usage="sampled")
view = tex.get_view(filter="linear")
material = gfx.VolumeBasicMaterial(map=view, clim=(0, 255))
volume = gfx.Volume(material)
```

### Even simpler?

In the above, the texture is given as the `map` of the material. This is a consistent with how mesh materials work, but the texture is the base source of data (in contrast to the mesh, where the positions are the "base" data). Maybe like this:

```py
tex = gfx.Texture(vol, dim=3, usage="sampled")
view = tex.get_view(filter="linear")
material = gfx.VolumeBasicMaterial(clim=(0, 255))
volume = gfx.Volume(view, material)
```

@Korijn Thoughts?

**Comment by Korijn** [comment]
> You let the user specify positions and texcoords, while these are fully determined by the volume shape

That's only true if you **want** the geometry to be determined by the volume shape

**Comment by Korijn** [comment]
By the way, you could put that class in the `helpers` subpackage, we already have one such class which wraps very common and convenient initialization code :)

https://github.com/pygfx/pygfx/blob/master/pygfx/helpers/_axes.py
