### ISSUE TITLE
Syntax highlighting of shaders

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#636]
While working on large shaders as in #628, it would help to have WGSL syntax highlighting. Right now the shaders are strings, which makes this hard. 

* Fix via an IDE: there is a VSCode extension to highlight WGSL in strings in JS, but not for Python.
* Fix by moving (most) shaders into their own files.

**Comment by Korijn** [comment]
Related https://github.com/pygfx/shadertoy/issues/5

**Comment by almarklein** [comment]
We now have our shaders as `.wgsl` files, and we have https://github.com/pygfx/python-string-shaders (a VSCode extension that is also aware of our templating syntax).
