### ISSUE TITLE
It's a very interesting project.

### ISSUE THREAD

**Issue by HongLouyemeng** [pygfx/pygfx#654]
Hi,Thanks for your excellent work, I'd like to ask if this library can support rasterization and ray tracing

**Comment by almarklein** [comment]
You'd have to be more specific what you mean with rasterization. In the end it renders an image, which is a rasterization for sure. 

We don't support ray tracing. This is a render engine based on forward rendering. We have support for e.g. BPR materials, environment maps, shadow ... but no raytracing at this point.
