### ISSUE TITLE
lines looks slightly different now

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#663]
I just want to confirm that #628 made a significant enough change to the line shader that we should expect slightly different renders of regular lines? 

I'm getting these kinds of diffs:

alpha:
![diff-line_cmap-alpha](https://github.com/pygfx/pygfx/assets/9403332/516b1135-0b3e-46c7-b7a5-9910f7867033)

rgb:
![diff-line_cmap-rgb](https://github.com/pygfx/pygfx/assets/9403332/0227f9bd-585e-431a-8f0d-0793a17a8411)

alpha:
![diff-line_collection-alpha](https://github.com/pygfx/pygfx/assets/9403332/77496c87-ed18-4128-bf90-d312eeea47a8)

rgb:
![diff-line_collection-rgb](https://github.com/pygfx/pygfx/assets/9403332/bc383f01-d947-4169-be06-1aff6a96d8d6)

**Comment by almarklein** [comment]
Yes, it is expected that they look slightly different. In particular they are likely a bit wider, because the earlier version did not account for the loss of thickness due to aa. I suspect the diffs relate mostly to that extra thickness. Does that make sense?

**Comment by Korijn** [comment]
@kushalkolar just wondering how the new line shader is working out for you in general? no breakage of features, or performance issues?

**Comment by kushalkolar** [comment]
> In particular they are likely a bit wider, because the earlier version did not account for the loss of thickness due to aa. I suspect the diffs relate mostly to that extra thickness. Does that make sense?

Yup! 

> just wondering how the new line shader is working out for you in general? no breakage of features, or performance issues?

No issues so far, all the diffs showed thicker lines but no other changes w.r.t. screenshots. Not sure about performance, it seems fine but we should probably make some kind of comprehensive benchmark that we can run.
