### ISSUE TITLE
Make test-screenshots RGB (instead of RGBA)

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#684]
Now (depending on how and where you view the image) the images are shown on a white background, while on screen the bg is black. This makes some objects hard to see, and therefore the screenshots harder to judge. I propose we apply a blend step so we get an RGB image instead. Note that errors in the transparency handling will still be detected, since they'd result in a different end-result.

**Comment by Korijn** [comment]
I've open sourced some code that we use in our E2E test suite where we do lots of screenshot comparison. It includes some fancy diff generation code and it's a lot more pleasant than the code we have here.

https://github.com/pygfx/image-comparison

Still need to add some unit tests, I had to rewrite some portions to untangle it from our codebase.

**Comment by almarklein** [comment]
Nice to have this in a separate module, so we can avoid replicating code in wgpu-py, pygfx, fastplotlib 😛

**Comment by Korijn** [comment]
That's what I was thinking
