### ISSUE TITLE
Dynamically changing the image map doesn't trigger recompilation

### ISSUE THREAD

**Issue by hmaarrfk** [pygfx/pygfx#686]
I am following suite of what goes on in in the `ImageBasicMaterial` to try to add a second texture (an alpha texture in my case) that could be switched based on user input to create different visual effects.

https://github.com/pygfx/pygfx/blob/be0d87a422e2596b91d6658d2645f547ca7da11f/pygfx/materials/_image.py#L55

However, it seems that setting the `map` doesn't necessarily trigger the recompilation of the image shader.

Instead i'm resorting to pseudocode that looks like:

```python
from copy import copy
old_material = image.material
new_material = copy(old_material)
new_material.map = new_map
image.material = new_material
```

it would be nice if i could use code that looks like:
```python
image.material.map = new_map
```

I have a feeling it is because it doesn't use the `_store` attribute of the material and thus doesn't get triggered for recompilation or update automatically.
https://github.com/pygfx/pygfx/blob/main/pygfx/renderers/wgpu/shaders/imageshader.py#L155

In my usecase, the shape and size of the mask may dynamically change to create different effects.

**Comment by almarklein** [comment]
I can reproduce this for `Image`, but not for `Mesh`. As you already hinted, the mesh material uses `._store` and the image material does not. Easy fix incoming 🚀

**Comment by hmaarrfk** [comment]
is that it ? so if i add variables to the store and change them they will retrigger a whole new compilation and setup of the assets in the scene?

**Comment by almarklein** [comment]
Almost ... the system keeps track of what variables (in a store) are *used* during each stage of composing the pipeline. Here you see a few cases of `wobject.tracker.track_usage()`:

https://github.com/pygfx/pygfx/blob/c5c588eecb228134aeaba62f9c1b96c46691adab/pygfx/renderers/wgpu/engine/pipeline.py#L511-L530

Then, basically, these values are tracked for changes.

It is also aware of hierarchy, so if you swap out a colormap of the same format, it will only update the bindings, i.e. not recompile the shader if its not needed.

**Comment by hmaarrfk** [comment]
Interesting. I'll have to look deeper at this code to better understand the interaction.

**Comment by almarklein** [comment]
The trackable mechanis are implemented here, btw: https://github.com/pygfx/pygfx/blob/main/pygfx/utils/trackable.py
