### ISSUE TITLE
Wireframe rendering

### ISSUE THREAD

**Issue by Korijn** [pygfx/pygfx#70]
What's the "wgpu way" to render wireframes? I.e. openGL's polygon mode?

**Comment by Korijn** [comment]
It's `RasterizationStateDescriptor` which contains `PolygonMode` but it hasn't landed in wgpu-py yet. OK, I'll wait! :)

**Comment by almarklein** [comment]
You mean drawing the wireframe of a mesh, without having to create new line-pair data?

> It's `RasterizationStateDescriptor` which contains `PolygonMode` but it hasn't landed in wgpu-py yet. 

Any sources; this is new for me :)

**Comment by Korijn** [comment]
https://github.com/gfx-rs/wgpu/blob/49cf466dc4d8f04466fcf74214b577dbed888253/wgpu-types/src/lib.rs

**Comment by Korijn** [comment]
Also see https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonMode.xhtml

**Comment by Korijn** [comment]
This should be possible now!

**Comment by almarklein** [comment]
Implemented in #136
