### ISSUE TITLE
Textures from arrays with little- or big-endian byte order

### ISSUE THREAD

**Issue by schlegelp** [pygfx/pygfx#714]
Hello!

While working on #707 I had a look at `Texture` because I ran into issues with image volumes that were little- or big-endian encode (e.g. `>u4`) - which seems not uncommon for e.g. microscopy formats:

```python
>>> import pygfx as gfx
>>> import numpy as np
>>> dummy = np.zeros((10, 10, 10), dtype='>u4')
>>> tex = gfx.Texture(dummy, dim=3)
TypeError: Cannot convert '>I' to wgpu format. You should provide data with a different dtype.
```

It looks like `get_item_format_from_memoryview()` is the initial gatekeeper as it complains because only native (`=`) [byte-orders](https://numpy.org/doc/stable/reference/generated/numpy.dtype.byteorder.html) are in the mapping. I tried circumventing it but then `to_texture_format()` complains when trying to run `gfx.show()`.

At the end of the day I was just wondering if that was a hard constraint (i.e. it actually matters to the GPU) or whether it would be possible to be more forgiving with regard to endian-ness?

**Comment by almarklein** [comment]
The short answer is that the GPU requires data in little-endian order, and that the buffer does not do auto-conversions, but requires the data to be in a supported format.

I've added this topic to #19, which we will work on relatively soon. At the very least we can provide a more meaningful errror message, and we should also check whether the logic works correctly on big-endian systems.

**Comment by almarklein** [comment]
The second statement should be the case, but I'm not sure whether it is currently implemented as such; we'd have to double-check.

**Comment by almarklein** [comment]
Done in #795. Big endian data is treated similarly to non-contiguous data: it supported (and automatically converted), but when `force_contiguous` is set, it is disallowed, to make sure it does not result in performance reduction in cases that have intensive gpu-syncing.
