### ISSUE TITLE
Make it possible to dynamically change material.pick_write 

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#720]
Follow up on #704

Problem: changing `pick_write` once the object is rendered, does not invoke a shader recompile.

**Comment by schlegelp** [comment]
I ran into an issue with this:

When a material starts off with `pick_write=True` everything works as expected, i.e. I can toggle between `True` and `False` to determine whether the object should be pickable. 

When a material starts off with `pick_write=False`, however, setting it to `pick_write=True` doesn't have any effect. 

Is that intended/expected?

**Comment by hmaarrfk** [comment]
This was not my intention in my original PR. Could you create a minimum reproducer then we can better troubleshoot.

**Comment by schlegelp** [comment]
For background: I'm running my app interactively (i.e. non-blocking) from an `ipython` session and I was trying set `pick_write=True` while working with the scene.

For the minimal reproducer, I thought you would prefer a stand-alone script and it turns out the issue only appears when trying to set `pick_write=True` after the first `renderer.render()`. 

```python
# Initialise the event loop
import pygfx as gfx
from wgpu.gui.auto import WgpuCanvas, run

canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

# Initialize with pick_write=False
cube = gfx.Mesh(
    gfx.box_geometry(200, 200, 200),
    gfx.MeshBasicMaterial(pick_write=False),
)
scene.add(cube)

def on_hover(event):
   print("Hovering over object:", event.pick_info["world_object"])

scene.add_event_handler(on_hover, "pointer_move")

camera = gfx.PerspectiveCamera(70, 16 / 9)
camera.show_object(scene)

controller = gfx.TrackballController(camera, register_events=renderer)

def animate():    
    renderer.render(scene, camera)    
    canvas.request_draw()
    # Setting pick_write=True after the first renderer.render() has no effect
    cube.material.pick_write = True
    
if __name__ == "__main__":    
    canvas.request_draw(animate)
    run()
```

Hope this is helpful.

**Comment by hmaarrfk** [comment]
I could recreate. But I’m on the the road. You should open a new issue.
