### ISSUE TITLE
Transparency blending issue

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#724]
I discovered this in #708, because markers with a transparent face and opaque edges produce the issue very well. But it can also be reproduced with normal points, of which some are made opaque black. The cyan lines and text in the below image are drawn on top as annotations. You'd expect the pink on the black circle to be equally dark as the pink on the background. But it's much brighter instead.

<img width="839" alt="image" src="https://github.com/pygfx/pygfx/assets/3015475/db5351c0-8235-4bd0-8db0-583efe7136f6">

**Comment by hmaarrfk** [comment]
Haha. We struggle with this alot. Are these points all from the same material and geometry? Or are they distinct objects?

I ask because for distinct objects we've been able to get (more) reliable results by using z and the render order. 

Without both being set correctly, we would often be blending things with the background instead of the object that was placed behind it.

**Comment by Korijn** [comment]
I wonder if this is related to #622

**Comment by almarklein** [comment]
This is one points objects.

**Comment by hmaarrfk** [comment]
Do you think it is also related to the AA artifacts 
I zoomed into the screenshot you took. It seems that some circles are blending with the background. 


![IMG_9301](https://github.com/pygfx/pygfx/assets/90008/24b1634f-0b89-43cc-b33c-b126526849c6)

**Comment by almarklein** [comment]
I see three things going on:

* Colors blend differently with the bg than with black opaque objects. This is because we consider the framebuffer to be transparant, allowing to render rgba images. I think this is best solved by using a `gfx.Background` in examples that use transparency.
* My initial surprise was: why do black edges, when shown through a semi-transparent face become the color of the face, rather than staying black? This is actually the expected behavior; it perfectly follows the blend equation. The effect I was expecting falls in the category of advanced physical light simulation (is it called translucency?).
* The black edges due to aa. Not sure yet why they appear.

**Comment by almarklein** [comment]
I think understand the dark edges too now: the faces of these dark disks/edges are opaque, so all transparent fragments that are between the face and that marker get blended. On the edges, however, aa makes the fragments semi-transparent, and therefore they get blended with the aforementioned transparent fragments, as well as the fragment that are *behind* the marker (up until an opaque fragment is encountered).

For `ordered2` this means that if the dark marker happened to be blended first, you'd get a dark edge. If its blended later, all is good. With `weighted` the dark semi-transparent fragment from the aa edge contribute to the transparency's combined color, making it darker. So it order-independently fails ;)
