### ISSUE TITLE
Order-independent transparency

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#73]
In #71 we laid the foundations for rendering to textures and managing those texture in the renderer. From there, the step to implementing OIT should be quite near!

## Links

* A great overview in a Bsc thesis by Felix Brüll in 2018: [Order Independent Transparency Acceleration](https://www2.in.tu-clausthal.de/~cgstore/theses/ba_felix_br%C3%BCll_2018.pdf)
* Weighted Blended Order-independent transparency (McGuire 2013): [publication](http://jcgt.org/published/0002/02/09/) [blog](http://casual-effects.blogspot.com/2015/03/implemented-weighted-blended-order.html)
* Phenomenological Transparency (McGuire 2016): [publication](https://casual-effects.com/research/McGuire2017Transparency/index.html) [blog](http://casual-effects.blogspot.com/2015/03/colored-blended-order-independent.html)
* Stochastic Transparency (Enderton 2011): [publication](http://enderton.org/eric/pub/stochtransp-tvcg.pdf)
* Adaptive Transparency (Salvi 2012): [publication](https://software.intel.com/content/www/us/en/develop/articles/adaptive-transparency.html)
* Multi Layer Alpha Blending MLAB (Salvi 2017): [publication](https://software.intel.com/content/www/us/en/develop/articles/multi-layer-alpha-blending.html)
* Multi-Layer Alpha Tracing (Brüll 2020): [publication](https://www.researchgate.net/publication/344441737_Multi-Layer_Alpha_Tracing/link/5f75d904299bf1b53e03ef42/download)
* OIT in vispy [#984](https://github.com/vispy/vispy/issues/984), [#2039](https://github.com/vispy/vispy/pull/2039), [#2230](https://github.com/vispy/vispy/pull/2230)

### Transparency is hard

Doing transparency the right way is hard. But it is also important to get right (IMO) or transparency will always be problematic for your viz library. The thing is that semi-transparent fragments must be blended with other semi-transparent fragments (and any opaque fragments) *in a fixed order*. That order can be back to front, or front to back, but it must be consistent. It is virtually impossible to make the fragments blend in a consistent order.

### A-buffer

The theoretically most correct solution for this is an A buffer. You store all drawn fragments, sort them, and then blend them together. Unfortunately, its hard to establish how many fragments should fit, and that number might be problematic memory-wise. 

### Weighted blended

Morgan McGuire has gone the road of an approach to blend fragments in such a way that the end result is the same, no matter the order of the fragments. It's not perfect, but much better then nothing, and at least it consistent, e.g. no popping effects. One major benefit is that it is relatively easy to implement on modest hardware (e.g. no spinlock, and even without multiple render targets, if you add another render pass).

His weighted blended approach is from 2013, proposing a fully order-independent method, and an extension to weigh fragments by their depth. In 2016 he proposed a version using 3 render targets to also support transmission effects (color modulation).

*(in an earlier version of this text I said that the 2016 work added the depth-weighting, but this was wrong.)*

One feature/issue with this technique is that there are no sharp transitions as one object crosses another:

![image](https://user-images.githubusercontent.com/3015475/139557492-8461fc34-77c1-48ad-ae95-e6ac76ed0710.png)

This can be seen as a feature when you render particle systems (e.g. smoke), but for the more sciency visualizations this is a disadvantage.

### Fixed-size buffer

The obvious solution to the memory-hungry A-buffer is to store a limited amount of fragments (the per-pixel fragment array). I limit the scope to methods that do the following: keep a limited number of foremost fragments, and merge the high-z fragments together.

Marco Salvi from Intel has proposes MLAB (Multi Layer Alpha Blending). The major contribution is that the blending is done with different equations depending on the order of the two samples. If all fragments pass in either front-to-back or back-to-front order, the result is perfect. Otherwise it becomes an approximation. You can see how this approach is therefore not fully order independent.

Felix Brul proposed an improvement to MLAB making it not necessary to keep the pixel array sorted, thereby reducing the buffer writes.

I also quite like the idea of keeping the `n` front fragments and blending the rest using McGuire's method.

All these methods require spin-locking to atomically update the fragments-structure. This is a trick available on modern OpenGL and also in wgpu. See Felix' thesis for details on the implementation, and also see #108.

### Other methods

Here's a list of other methods that exist, but which I've discarded:
* Depth peeling involves rendering your scene several times, peeling of one (or two) layers at a time.
* Stochastic Transparency (aka screen-door transparency), where you only draw opaque fragment, but drop some fragments in let semi-transparent objects. By rendering at a higher resolution and then smoothing the result you get a reasonable result. Can also use multi-sampling for this, I believe.
* K-buffer: keep a limited number of fragments, drop the rest.
* K-buffer with a variable amount of fragments per pixels.
* Adaptive Transparency is the precursor to MLAB and related approaches. It keeps track of a stepwise transfer function.

## Thoughts

Some methods (including weighted blended) assume you first render all opaque objects and then apply the fancy trickery when you render non-opaque objects. In games I assume it's generally easy to distinguish between these groups of objects, but I feel like its harder for us with more sciency data. E.g. volume rendering could have a mix of transparent and opaque objects. *So I hope we can realize a single pass, in which we do all the drawing and picking at once.*

We should consider that some objects want to emit multiple fragments per pixel (e.g. volume rendering).

All of this also relates to anti-aliasing (where transparent fragments are often introduced), deferred rendering (which looks a bit like the A-buffer stuff), picking (can you also pick non-opaque objects?).

At first I like weighted blended a lot, but I think you'd need a spin-lock to do it in a single pass, so we might as well implement a more correct approach like MLAB or Felix' improved variant of that. I also find Stochastic Transparency has its charm. *update: a second pass is needed anyway.*

### Update

Since we need two render passes anyway, it seems reasonable to start with implementing McGuire's approach and then try to also store the first `n` fragments. I will make a new issue for this plan: #196

**Comment by Korijn** [comment]
Would it be very complicated to make this opt-in? Such that a user can actively _choose_ to use this, or is it too tied up with the various shaders and the renderer?

**Comment by almarklein** [comment]
That's a good question. On the one hand we may want to give users control over e.g. blending. On the other, I've always dreamt of a tool where you can just put objects in a scene and everything renders "correctly". Depending on how OIT gets implemented, it may be hard to have both. We have to choose what tool we want to be. I'm leaning towards less control, more render-correctness, because something like OIT would be very hard to implement "on top" of a more rawish pygfx. Anyway, something to think about ...

**Comment by almarklein** [comment]
Closing, since we have OIT now. A few remaining cleanups are tracked in #196.
