### ISSUE TITLE
additive blending?

### ISSUE THREAD

**Issue by tlambert03** [pygfx/pygfx#750]
Apologies for what feels like a very basic question.  I've looked through the docs and source code and I'm struggling to find something like an additive blending mode (might just be semantics and I'm missing it?)

I'm using a `QWgpuCanvas` with a `WgpuRenderer`, and have added a few `pygfx.Image` to the scene, each with a `ImageBasicMaterial` (using `depth_test=False` for what it's worth) and each with a different colormap (e.g. Red, Green, and Blue).  What I'd like is for the colors in these three images to render to something similar to or the same as what I would get with a single RGB image (but for my application I want to retain individual addressable images with independent colormaps).  I've tried `renderer.blend_mode`: "opaque", "ordered1", "ordered2", "weighted", "weighted_depth", "weighted_plus"... and I do get something that appears sort of additive with the `weighted` variants.  but it's "muted" compared to what I'd expect (i.e. R,G,B don't seem to add up to white; they saturate at something around #9C9C9C)

thanks!

**Comment by almarklein** [comment]
This is indeed not currently supported. There is [renderer.blend_mode](https://pygfx.readthedocs.io/en/stable/_autosummary/renderers/wgpu/pygfx.renderers.wgpu.WgpuRenderer.html#pygfx.renderers.wgpu.WgpuRenderer.blend_mode) which defines how things are blended. For additive blending, we could add an option there (and matching classes in `blender.py`).

**Comment by tlambert03** [comment]
Ok thanks for confirming!  I'll try to take a stab at adding a new mode if I can find some time
