### ISSUE TITLE
An API for subplots

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#76]
Or ... rendering a scene to a subregion.

Also look into using a renderer with multiple cameras.

**Comment by Korijn** [comment]
There's a ton of relevant three.js examples you can look at for inspiration:

- https://threejs.org/examples/?q=camera#webgl_camera_array
- https://threejs.org/examples/?q=camera#webgl_camera
- https://threejs.org/examples/?q=view#webgl_multiple_views
- https://threejs.org/examples/?q=mult#webgl_multiple_canvases_complex
- https://threejs.org/examples/?q=mult#webgl_multiple_canvases_grid
- https://threejs.org/examples/?q=mult#webgl_multiple_canvases_circle
- https://threejs.org/examples/?q=mult#webgl_multiple_renderers
- https://threejs.org/examples/?q=mult#webgl_multiple_scenes_comparison

**Comment by Korijn** [comment]
Three.js offers a number of APIs that can be used separately or in combination:

* [ArrayCamera](https://threejs.org/docs/index.html#api/en/cameras/ArrayCamera) which is primarily intended for VR, where you have a special camera subclass that holds an array of subcameras, each of which has a "viewport" dict which determines the portion of the canvas that subcamera renders to
* WebGLRenderer provides a couple of things:
  * OpenGL's [Scissor Test](https://www.khronos.org/opengl/wiki/Scissor_Test) via `renderer.setScissorTest(enabled)` and `renderer.setScissor(x, y, width, height)`
  * `renderer.setViewport(x, y, width, height)` is offered separately, I'm not sure why

**Comment by Korijn** [comment]
Can we close this now that we have the Viewport class?

**Comment by almarklein** [comment]
Yes, that covers it!
