### ISSUE TITLE
Sweet example idea: drawing on an image in a 3D scene

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#78]

**Comment by Korijn** [comment]
We have this now: [`scene_in_a_scene.py`](https://github.com/pygfx/pygfx/blob/main/examples/scene_in_a_scene.py)

**Comment by almarklein** [comment]
I think this was @ivoflipse's idea, and was about manually drawing something (using the mouse) using the picking mechanism.

**Comment by Korijn** [comment]
In that case it's already covered in https://github.com/pygfx/pygfx/issues/93
