### ISSUE TITLE
test examples on more python versions?

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#792]
Currently examples are only tested on python 3.9, would you be interested in also testing on python 3.10 - 3.12:

https://github.com/pygfx/pygfx/blob/79f7542d98f485cc6fa2b797fa904fab98372a8d/.github/workflows/ci.yml#L118-L128

And adding python3.12 to the test builds too:

https://github.com/pygfx/pygfx/blob/79f7542d98f485cc6fa2b797fa904fab98372a8d/.github/workflows/ci.yml#L62-L80

**Comment by almarklein** [comment]
Good point. The example tests cover more code than the unit tests, so it makes sense to at least use the highest and lowest supported Python version.

**Comment by almarklein** [comment]
Closed by #793
