### ISSUE TITLE
Image with the size set by the material

### ISSUE THREAD

**Issue by hmaarrfk** [pygfx/pygfx#799]
In an offline conversation with Almar he had asked me if it would be beneficial to have an image object who's size in world space was determined by a property different than the geometry grid. 

I think I've found our main usecase:

1. Generally, we might have a surface, be-it an image, that we might be interested in replacing the texture with an other one.
2. However, the size of the texture may change quite dynamically with the usage of the system. Think of "preview mode" in a biomedical engineering context and "record mode". One may have much lower pixel count, but you still want the illusion that you are capture the same region of interest in "physical space".
3. We had been historically swapping the geometry size, then appropriately swapping the scale.
4. The problem is that the fact of changing the "scale" of the image object, may change the location of any children that you want to place along the texture itself.

Our solution has been to:

1. Always embed the image in a larger group. This is somewhat tiring and the abstract nature is hard communicate across our team (even I get confused, and I mostly recreated the hierarchy). The higher level group stays "constant" in shape, making it easier to add labels and whatnot
2. Constantly changing the scale of the image object is easy to forget. The typical workflow consists of
    - Change the image geometry.
    - Change the scale.
    - It would be preffarable to "just change the geometry's grid"

To implement this "scale invariant image" my general strategy has been:

1. Add a property to the image material  called `shape_mode` (the name could be better, suggestions appreciated). It can change between `geometry` and `material`.
2. Add a property to the image material called `image_shape` that sets the extent of the image shape (shape = yx, size = xy).
3. Then for the Image world object, switch between grabbing the geometry `bounding_box` to that of the material.

```python
class MyImage(gfx.Image):
    def get_bounding_box(self):
        if self.material.shape_mode == "material":
            image_shape = self.material.image_shape
            return np.asarray([
                [0, 0, 0],
                [image_shape[1], image_shape[0], 0]
            ], dtype='float64')
        else:
            return super().get_bounding_box()
```
5. The shader gets modified with:

```wgsl
            $$ if shape_mode == "geometry"
                let pos = vec2<f32>(size.xy);
            $$ else
                let pos = vec2<f32>(
                    f32(u_material.image_shape[1]),
                    f32(u_material.image_shape[0])
                );
            $$ endif
            geo.positions = array<vec3<f32>,4>(
                vec3<f32>(pos.x, 0., 0.0),
                vec3<f32>(pos.x, pos.y, 0.0),
                vec3<f32>(0., 0., 0.0),
                vec3<f32>(0., pos.y, 0.0),
            );
            // let pos1 = vec2<f32>(-0.5);
            // let pos2 = vec2<f32>(size.xy) + pos1;
            // geo.positions = array<vec3<f32>,4>(
            //     vec3<f32>(pos2.x, pos1.y, 0.0),
            //     vec3<f32>(pos2.x, pos2.y, 0.0),
            //     vec3<f32>(pos1.x, pos1.y, 0.0),
            //     vec3<f32>(pos1.x, pos2.y, 0.0),
            // );
```

one of the problems that we have in our model is that the compatibility with the 0.5 pixel offset (which I understand from a sampling theory perspective) isn't really congruent with "i want my image to span from position 0.0 to position 10.0 and no got any fraction beyond 10.0"

A few things I learned:

1. No `geometry.uniform_buffer` exists in standard geometry objects. This makes adding the `image_shape` property to the `geometry` a little harder since you have to add yet an other uniform buffer to your code. Not the end of the world, but I guess the "fewer mods" the better in my mind.
2. I think it might just be easier to make a `ImageGeometry` class that simplifies the bounding box computation if you wish to delagate this scale invariance to the Geometry instead of the Material.

**Comment by almarklein** [comment]
To get an idea, how well does a `Mesh` object work for your use-case? A mesh with a plane geometry (4 positions), and a `material.map` on it. I assume this would solve the positioning issue, but you'd lose e.g. colormapping of the image data.

**Comment by hmaarrfk** [comment]
> To get an idea, how well does a Mesh object work for your use-case? A mesh with a plane geometry (4 positions), and a material.map on it. I assume this would solve the positioning issue, but you'd lose e.g. colormapping of the image data.

Having learned much more about GPUs in the last few months, I presume that would be the same thing that I'm trying to achieve.

We've modified our shaders quite extensively from the "image shader" i don't think it would make sense to revert at this stage (its likely that it is the mesh special case right now).

I'm satisfied enough with your answer!

**Comment by hmaarrfk** [comment]
It might be a good thing to document for new users. 

That an "Image" for manys understanding is a special case of a mesh and a texture map.

**Comment by hmaarrfk** [comment]
I can take this documentation task (along with the creation of an example) as a task I can contribute.

**Comment by almarklein** [comment]
There's two validation examples that show the difference to some extent. A single example demonstrating the two cases side-by side is likely more appealing indeed!
