### ISSUE TITLE
Changing color for the line segment when color_mode is not uniform.

### ISSUE THREAD

**Issue by maharshi-gor** [pygfx/pygfx#806]
Hi,

I am trying to create an example using the line geometry and line material to create multiple lines. I use the [nan, nan, nan] buffer to create different segments.

I am using the `color_mode=vertex` in the line material and passing the `colors=<vertex_colors>` in geometry. I want to change the color of the specific segment clicked by the user which I am tracking using the `pointer_down` event.

I can get the correct vertex indices to update the color buffer but canvas.request_draw() does not change the color. I tried exploring the examples but the examples talk about the uniform color change which is done through the material of the object.

can I get a reference on how to get the color changed?

Here is my code for reference,
```
lines = gfx.Line(
    gfx.Geometry(positions=pygfx_streamlines, colors=pygfx_colors),
    gfx.LineMaterial(thickness=5.0, opacity=1.0, color_mode='vertex', pick_write=True)
)

def on_pick(event):
    vertex = event.pick_info["vertex_index"]
    print("Vertex : ", vertex)
    print("Vertex Coord: ", pygfx_streamlines[vertex])
    selected = find_line(vertex)
    color = pygfx_colors[selected[0]][:3]
    pygfx_colors[selected[0]:selected[1] + 1] = (*color, 0.5)
    lines.material.color_mode = 'vertex'
    canvas.request_draw()


def find_line(vertex):
    left = right = vertex

    while not np.isnan(pygfx_streamlines[left][0]):
        left -= 1

    while not np.isnan(pygfx_streamlines[right][0]):
        right += 1

    print(left, right)
    return [left + 1, right - 1]
```

Thanks

**Comment by Korijn** [comment]
You need to call `pygfx_colors.update_range()` to inform the renderer that the buffer was modified and needs to be synchronized to the GPU before the next draw

**Comment by maharshi-gor** [comment]
Hi Krojin,

Thank you so much for the quick reply. It is working fine now!
