### ISSUE TITLE
Unsolicited Feedback on the Grid Shader

### ISSUE THREAD

**Issue by hmaarrfk** [pygfx/pygfx#821]
I was playing around with the grid example:

and wanted to structure the feedback i had
https://github.com/pygfx/pygfx/pull/820#issuecomment-2227026954

I'm not sure what is the source for many of these, but I've found that the lines generated from the examples
```
examples/feature_demo/line_plot.py
```

Provide very strange results
![image](https://github.com/user-attachments/assets/5a15021f-9c0b-4a31-9105-c606e8b28d11)

Notice how the grid just randomly disappears.

I wish i could say that the artifacts go away with "thicker lines"
```
diff --git a/examples/feature_demo/line_plot.py b/examples/feature_demo/line_plot.py
index 45dd22f..a91ebd1 100644
--- a/examples/feature_demo/line_plot.py
+++ b/examples/feature_demo/line_plot.py
@@ -26,8 +26,8 @@ grid = gfx.Grid(
         major_step=1,
         minor_step=0,
         thickness_space="screen",
-        major_thickness=2,
-        minor_thickness=0.5,
+        major_thickness=5,
+        minor_thickness=4,
         infinite=True,
     ),
     orientation="xy",
@@ -64,7 +64,7 @@ def animate():
     rulery.start_value = rulery.start_pos[1]
     statsy = rulery.update(camera, canvas.get_logical_size())

-    major_step_x, major_step_y = statsx["tick_step"], statsy["tick_step"]
+    major_step_x, major_step_y = 2 * statsx["tick_step"], 2 * statsy["tick_step"]
     grid.material.major_step = major_step_x, major_step_y
     grid.material.minor_step = 0.2 * major_step_x, 0.2 * major_step_y
```
![image](https://github.com/user-attachments/assets/e3dd352b-7030-487b-8e1d-d42f3bb68c7b)

Zooming into the center, you see some very strange things at what appears to be some kind of symmetry point.
![image](https://github.com/user-attachments/assets/300de9b8-7b4c-4927-94a9-de6fafda5f83)

I'm hoping that this stirs some ideas as to why this might be happening. Seems like a rounding error might be causing some of this.

I don't think it has to do with the pixel_ratio since when I set a pixel_ratio of 1 it still occurs:
![image](https://github.com/user-attachments/assets/909be1bd-4845-43a5-ad4b-c9efe3358c79)

**Comment by kushalkolar** [comment]
I've been playing around with this example too, does it occur during a specific camera state?

**Comment by hmaarrfk** [comment]
I'm only using two finger scroll and pan. 

I have to scroll to pathologically bad locations for each of these examples. 

But as you interact with the grid, you do cycle through them so it is jarring to see them pop in and out of these strange states.

**Comment by kushalkolar** [comment]
ok I can finally reproduce this too!

https://youtu.be/6nOYqAjs-WQ

**Comment by hmaarrfk** [comment]
Sorry to make you hunt for it. It was so easy for me to create locally I assumed it was easy....

**Comment by kushalkolar** [comment]
No worries, currently working on axes stuff in fpl so this is very much within what I'm doing right now! :D 

This is really weird, I was wondering why I hadn't spotted this earlier and it's because I've been mostly on my work laptop the past week where it was much harder to reproduce this. It has an nvidia GPU, the artifacts I posted above are from my desktop with an AMD RX 570.

This is from my nvidia:

https://youtu.be/p_KisxfMEuA

**Comment by hmaarrfk** [comment]
> The way that a lot of times it's one half of the canvas, or the artifacts are in quadrants makes me think it's something NDC related?

Yea.....

I mean, here is my demo on youtube, watch at 1080p 
https://youtu.be/XXrUXzLSNnU

but it didn't take any effort

<details><summary>wgpu print info</summary>

```

################ system:

             platform:  Linux-6.8.0-38-generic-x86_64-with-glibc2.39
python_implementation:  CPython
               python:  3.12.4

################ versions:

    wgpu:  0.16.0
    cffi:  1.16.0
 PySide6:  6.7.2
   numpy:  2.0.0
   pygfx:  0.3.0
pylinalg:  0.4.1

################ wgpu_native_info:

expected_version:  0.19.4.1
     lib_version:  0.19.4.1
        lib_path:  libwgpu_native.so

################ object_counts:

                      count  resource_mem

            Adapter:      1
          BindGroup:      0
    BindGroupLayout:      0
             Buffer:      2            40
      CanvasContext:      1
      CommandBuffer:      0
     CommandEncoder:      0
 ComputePassEncoder:      0
    ComputePipeline:      0
             Device:      1
     PipelineLayout:      0
           QuerySet:      0
              Queue:      1
       RenderBundle:      0
RenderBundleEncoder:      0
  RenderPassEncoder:      0
     RenderPipeline:      0
            Sampler:      0
       ShaderModule:      0
            Texture:      0
        TextureView:      0

              total:      6            40

################ wgpu_native_counts:

                  count    mem  backend   a  k  r  e  el_size

        Adapter:      1  1.98K   vulkan:  1  1  0  0    1.98K
      BindGroup:      0      0   vulkan:  0  0  0  0      368
BindGroupLayout:      0      0   vulkan:  0  0  0  0      320
         Buffer:      2    592   vulkan:  2  2  0  0      296
  CanvasContext:      1    160            1  1  0  0      160
  CommandBuffer:      0      0   vulkan:  0  0  0  0    1.28K
ComputePipeline:      0      0   vulkan:  0  0  0  0      288
         Device:      1  11.9K   vulkan:  1  1  0  0    11.9K
 PipelineLayout:      0      0   vulkan:  0  0  0  0      200
       QuerySet:      0      0   vulkan:  0  0  0  0       80
          Queue:      1    184   vulkan:  1  1  0  0      184
   RenderBundle:      0      0   vulkan:  0  0  0  0      848
 RenderPipeline:      0      0   vulkan:  0  0  0  0      560
        Sampler:      0      0   vulkan:  0  0  0  0       80
   ShaderModule:      0      0   vulkan:  0  0  0  0      800
        Texture:      0      0   vulkan:  0  0  0  0      824
    TextureView:      0      0   vulkan:  0  0  0  0      248

          total:      6  14.8K

    * The a, k, r, e are allocated, kept, released, and error, respectively.
    * Reported memory does not include buffer/texture data.

################ pygfx_adapter_info:

      vendor:  Intel open-source Mesa driver
architecture:
      device:  Intel(R) Xe Graphics (TGL GT2)
 description:  Mesa 24.0.5-1ubuntu1
   vendor_id:  32.9K
   device_id:  39.4K
adapter_type:  IntegratedGPU
backend_type:  Vulkan

################ pygfx_features:

                                       adapter  device

                  bgra8unorm-storage:        ✓       -
                      clip-distances:        -       -
               depth32float-stencil8:        ✓       -
                  depth-clip-control:        ✓       -
                  float32-filterable:        ✓       ✓
             indirect-first-instance:        ✓       -
            rg11b10ufloat-renderable:        ✓       -
                          shader-f16:        ✓       -
            texture-compression-astc:        ✓       -
              texture-compression-bc:        ✓       -
            texture-compression-etc2:        ✓       -
                     timestamp-query:        ✓       -
                   MultiDrawIndirect:        ✓       -
              MultiDrawIndirectCount:        ✓       -
                       PushConstants:        ✓       -
TextureAdapterSpecificFormatFeatures:        ✓       -
               VertexWritableStorage:        ✓       -

################ pygfx_limits:

                                                  adapter  device

                                max_bind_groups:        8       8
            max_bind_groups_plus_vertex_buffers:        0       0
                    max_bindings_per_bind_group:    1.00K   1.00K
                                max_buffer_size:    2.14G   2.14G
          max_color_attachment_bytes_per_sample:        0       0
                          max_color_attachments:        0       0
          max_compute_invocations_per_workgroup:    1.02K   1.02K
                   max_compute_workgroup_size_x:    1.02K   1.02K
                   max_compute_workgroup_size_y:    1.02K   1.02K
                   max_compute_workgroup_size_z:    1.02K   1.02K
             max_compute_workgroup_storage_size:    65.5K   65.5K
           max_compute_workgroups_per_dimension:    65.5K   65.5K
max_dynamic_storage_buffers_per_pipeline_layout:        8       8
max_dynamic_uniform_buffers_per_pipeline_layout:        8       8
              max_inter_stage_shader_components:      116     116
               max_inter_stage_shader_variables:        0       0
          max_sampled_textures_per_shader_stage:    65.5K   65.5K
                  max_samplers_per_shader_stage:    65.5K   65.5K
                max_storage_buffer_binding_size:    2.14G   2.14G
           max_storage_buffers_per_shader_stage:    65.5K   65.5K
          max_storage_textures_per_shader_stage:    65.5K   65.5K
                       max_texture_array_layers:    2.04K   2.04K
                        max_texture_dimension1d:    16.3K   16.3K
                        max_texture_dimension2d:    16.3K   16.3K
                        max_texture_dimension3d:    2.04K   2.04K
                max_uniform_buffer_binding_size:    1.07G   1.07G
           max_uniform_buffers_per_shader_stage:       64      64
                          max_vertex_attributes:       29      29
                 max_vertex_buffer_array_stride:    4.09K   4.09K
                             max_vertex_buffers:       16      16
            min_storage_buffer_offset_alignment:       32      32
            min_uniform_buffer_offset_alignment:       64      64

################ pygfx_caches:

                    count  hits  misses

full_quad_objects:      0     0       0
 mipmap_pipelines:      0     0       0
          layouts:      0     0       0
         bindings:      0     0       0
   shader_modules:      0     0       0
        pipelines:      0     0       0
 shadow_pipelines:      0     0       0

################ pygfx_resources:

Texture:  8
 Buffer:  108
```
</summary>

on your laptop you should be able to switch to the intel GPU too if you want.

**Comment by hmaarrfk** [comment]
My guess is that at least part of it has to do with `fract`
https://www.w3.org/TR/WGSL/#fract-builtin
https://github.com/gpuweb/gpuweb/issues/3987

**Comment by kushalkolar** [comment]
ok tried this on my desktop which has an AMD RX570 and Nvidia 3080. Produced artifact using the AMD and saved camera state. I can reproduce it if I set the camera state on the AMD, but on my nvidia I do not get the artifacts with the same camera state :open_mouth: . I also don't get the artifacts on lavapipe.

AMD:

[{'adapter_type': 'DiscreteGPU',
  'architecture': '',
  'backend_type': 'Vulkan',
  'description': 'Mesa 20.3.5 (ACO)',
  'device': 'AMD RADV POLARIS10 (ACO)',
  'device_id': 26591,
  'vendor': 'radv',
  'vendor_id': 4098}]

![image](https://github.com/user-attachments/assets/adc77b11-c7e1-4b49-bd33-9cc94f04084a)

lavapipe:

[{'adapter_type': 'CPU',
  'architecture': '',
  'backend_type': 'Vulkan',
  'description': 'Mesa 20.3.5 (LLVM 11.0.1)',
  'device': 'llvmpipe (LLVM 11.0.1, 256 bits)',
  'device_id': 0,
  'vendor': 'llvmpipe',
  'vendor_id': 65541}]

![image](https://github.com/user-attachments/assets/8ef6321f-9d2d-4ea5-a353-ce49d40125cd)

nvidia:

[{'adapter_type': 'DiscreteGPU',
  'architecture': '',
  'backend_type': 'Vulkan',
  'description': '530.30.02',
  'device': 'NVIDIA GeForce RTX 3080',
  'device_id': 8710,
  'vendor': 'NVIDIA',
  'vendor_id': 4318}]

![image](https://github.com/user-attachments/assets/078bb2de-c856-4a08-b542-7b5a46988d08)


This is what I ran, same as the example but I just selected different GPUs and set the same camera state.

```python3
"""
Line plot
=========

Show a line plot, with axii and a grid.
"""

# sphinx_gallery_pygfx_docs = 'screenshot'
# sphinx_gallery_pygfx_test = 'run'

import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx
from pylinalg import vec_transform, vec_unproject
import wgpu
from pygfx.renderers.wgpu import select_adapter
from pprint import pprint

adapters = wgpu.gpu.enumerate_adapters()
# for me 0 is AMD, 1 is lavapipe, 2 is nvidia
gpu_index = 0

pprint([adapters[gpu_index].info])



select_adapter(adapters[gpu_index])


canvas = WgpuCanvas()
renderer = gfx.WgpuRenderer(canvas)

scene = gfx.Scene()

background = gfx.Background.from_color("#000")

grid = gfx.Grid(
    None,
    gfx.GridMaterial(
        major_step=1,
        minor_step=0,
        thickness_space="screen",
        major_thickness=2,
        minor_thickness=0.5,
        infinite=True,
    ),
    orientation="xy",
)
grid.local.z = -1001

rulerx = gfx.Ruler(tick_side="right")
rulery = gfx.Ruler(tick_side="left", min_tick_distance=40)

x = np.linspace(20, 980, 200, dtype=np.float32)
y = np.sin(x / 30) * 4
positions = np.column_stack([x, y, np.zeros_like(x)])

line = gfx.Line(
    gfx.Geometry(positions=positions),
    gfx.LineMaterial(thickness=4.0, color="#aaf"),
)
scene.add(background, grid, rulerx, rulery, line)

camera = gfx.OrthographicCamera(maintain_aspect=False)
camera.show_rect(0, 1000, -5, 5)

# camera state at which there's an artifact
state = {'position': np.array([4.00873842e+02, 2.09405271e-02, 2.74767522e+01]),
 'rotation': np.array([0., 0., 0., 1.]),
 'scale': np.array([1., 1., 1.]),
 'reference_up': np.array([0., 1., 0.]),
 'fov': 0.0,
 'width': 54.40941020600778,
 'height': 0.5440941020600778,
 'zoom': 1.0,
 'maintain_aspect': False,
 'depth_range': None}


controller = gfx.PanZoomController(camera, register_events=renderer)
camera.set_state(state)

def animate():
    rulerx.start_pos = camera.world.x - camera.width / 2, 0, -1000
    rulerx.end_pos = camera.world.x + camera.width / 2, 0, -1000
    rulerx.start_value = rulerx.start_pos[0]
    statsx = rulerx.update(camera, canvas.get_logical_size())

    rulery.start_pos = 0, camera.world.y - camera.height / 2, -1000
    rulery.end_pos = 0, camera.world.y + camera.height / 2, -1000
    rulery.start_value = rulery.start_pos[1]
    statsy = rulery.update(camera, canvas.get_logical_size())

    major_step_x, major_step_y = statsx["tick_step"], statsy["tick_step"]
    grid.material.major_step = major_step_x, major_step_y
    grid.material.minor_step = 0.2 * major_step_x, 0.2 * major_step_y

    # print(statsx)

    renderer.render(scene, camera)


if __name__ == "__main__":
    canvas.request_draw(animate)
    run()
```

**Comment by hmaarrfk** [comment]
On my GPU:
![image](https://github.com/user-attachments/assets/6df52e1a-20f5-4162-b5eb-2da0042c90fb)

**Comment by hmaarrfk** [comment]
intel GPU:
![image](https://github.com/user-attachments/assets/5840fb29-e7df-4d5c-af8c-d5ec416cdd5b)


(Sorry my previous screenshot i had hacked the shader code)

**Comment by hmaarrfk** [comment]
Your state is the best i've seen, totally non-symmetric!!!

**Comment by kushalkolar** [comment]
I'm starting to think that maybe it's not worth worrying about the AMD so here are some camera states where I get artifacts with my nvidia. All with the same canvas size as the example posted, just replace the state:

```python
{'position': array([155.89944042,   2.14627342, 108.56750306]),
 'rotation': array([0., 0., 0., 1.]),
 'scale': array([1., 1., 1.]),
 'reference_up': array([0., 1., 0.]),
 'fov': 0.0,
 'width': 216.88467178801838,
 'height': 0.25033433674675887,
 'zoom': 1.0,
 'maintain_aspect': False,
 'depth_range': None}
```

![image](https://github.com/user-attachments/assets/228c72c3-02f0-40ab-8f7c-f02f6ccf683c)


```python3
{'position': array([263.84992021,  -0.3825374 , 358.48881345]),
 'rotation': array([0., 0., 0., 1.]),
 'scale': array([1., 1., 1.]),
 'reference_up': array([0., 1., 0.]),
 'fov': 0.0,
 'width': 716.977624007917,
 'height': 2.9049164382820205e-06,
 'zoom': 1.0,
 'maintain_aspect': False,
 'depth_range': None}
```

![image](https://github.com/user-attachments/assets/d1cb966a-4931-4cc6-957b-1c3d1f9dcbf1)

**Comment by hmaarrfk** [comment]
iq always has the best shaders:

https://www.shadertoy.com/view/XtBfzz

Maybe you want to take inspiration!

**Comment by hmaarrfk** [comment]
I'm kinda just in awe of his example.

**Comment by hmaarrfk** [comment]
But apparently pristine grid looks even better still:
https://www.shadertoy.com/view/mdVfWw

**Comment by Korijn** [comment]
Our implementation is a variant on the pristine grid. :)

**Comment by almarklein** [comment]
And the prestine grid was inspired by the work of Inigo Quilez. The world of grid rendering is very small :)

**Comment by almarklein** [comment]
I cannot reproduce the artifact that you're posting on my M1. But I can get weird wobbly effects if I zoom in, and eventually it turns all black.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/d48c4b78-d0c1-4bf8-b4c4-40becb1486f2">

**Comment by almarklein** [comment]
Could you try using a finite grid? I can imagine some weird stuff happening due to that. 

```py
grid = gfx.Grid(
    None,
    gfx.GridMaterial(
        ...,
        infinite=False,
    ),

def animate():
    ...
    grid.local.x = rulerx.start_pos[0]
    grid.local.y = rulery.end_pos[1]
    grid.local.scale_x = rulerx.end_pos[0] - rulerx.start_pos[0]
    grid.local.scale_y = rulery.start_pos[1] - rulery.end_pos[1]

```

**Comment by hmaarrfk** [comment]
> (though it still goes black if I zoom in far enough, so that's likely a different problem).

Is that some near/far clipping planes coming into play?

> Could you try using a finite grid?

That seemed to remove the strangeness on my computer. For one the AA filter on the major and minor ticks finally looks consistent. Previously the line thickness really looked inconsistent.

**Comment by hmaarrfk** [comment]
> Our implementation is a variant on the pristine grid. :) See https://github.com/pygfx/pygfx/pull/743

Sorry this was me acknowledging that the pristine grid was a better choice! Sorry for not making that clear. I've been following alot of the design choices trying to learn about the real of possibilities.

**Comment by almarklein** [comment]
>> Could you try using a finite grid?
>
> That seemed to remove the strangeness on my computer.

Thanks. Looks like the mechanics to make the grid infinite needs some re-thinking. Might be specific to ortho cameras.

BTW, this also explains the rectangular regions displaying the artifacts; the inf grid is composed of a smaller quad, and a larger ring around it. The latter is intended to show the grid in the distance (towards the horizon), but this is not a thing in this use-case, becasue we look straight onto the grid.
