### ISSUE TITLE
CI and more tests

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#83]

**Comment by Korijn** [comment]
We can replicate what was done in https://github.com/pygfx/wgpu-py/pull/188 to enable vulkan software rendering on our CI as well. We don't have any tests that use it yet, but that means we can start adding them!

**Comment by Korijn** [comment]
Closing this as we just merged #239

**Comment by almarklein** [comment]
More unit tests would not hurt, but with the example testing we should touch a pretty large part of the codebase indeed :)
