### ISSUE TITLE
Filter out events under certain conditions

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#832]
It would be useful to filter out events in certain conditions. For example, if an imgui window is overlaid on the same canvas it is useful for pygfx to ignore pointer events from the imgui window.

Example that demonstrates the issue:

https://github.com/user-attachments/assets/08164b03-8bae-4431-ab00-8878f1c8fabf

<details>
<summary>code</summary>
<br>

```python
import numpy as np

from imgui_bundle import imgui
from wgpu.gui.auto import WgpuCanvas, run
from wgpu.utils.imgui import ImguiRenderer


import pygfx

canvas = WgpuCanvas()
renderer = pygfx.WgpuRenderer(target=canvas)

imgui_renderer = ImguiRenderer(renderer.device, canvas)

# random scatter of 100 points
data = np.random.normal(size=(100, 3)).astype(np.float32)

points = pygfx.Points(
    geometry=pygfx.Geometry(positions=data),
    material=pygfx.PointsMaterial(size=20, color=(1., 1., 1., 0.7))
)

scene = pygfx.Scene()
camera = pygfx.OrthographicCamera()

scene.add(points)

camera.show_object(scene)

controller = pygfx.PanZoomController(camera, register_events=renderer)


def update_gui():
    imgui.new_frame()

    imgui.set_next_window_pos((0, 10), imgui.Cond_.appearing)
    imgui.set_next_window_size((300, 0), imgui.Cond_.appearing)

    imgui.begin("window", None)

    changed, new_size = imgui.slider_float(label="pointer_size", v=points.material.size, v_min=1.0, v_max=50.0)

    if changed:
        points.material.size = new_size

    imgui.end()
    imgui.end_frame()
    imgui.render()

    return imgui.get_draw_data()


imgui_renderer.set_gui(update_gui)

def animate():
    renderer.render(scene, camera)

    imgui_renderer.render()

    canvas.request_draw()


canvas.request_draw(animate)
canvas.set_logical_size(700, 500)
run()
```
</details>

One possible solution is for the `WgpuRenderer` to filter out events:

```patch
Index: pygfx/renderers/wgpu/engine/renderer.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pygfx/renderers/wgpu/engine/renderer.py b/pygfx/renderers/wgpu/engine/renderer.py
--- a/pygfx/renderers/wgpu/engine/renderer.py	(revision ea1acde81a8ff9dae443480d9530e399512c991f)
+++ b/pygfx/renderers/wgpu/engine/renderer.py	(date 1722136808131)
@@ -190,6 +190,8 @@
         if enable_events:
             self.enable_events()
 
+        self._event_filters = {}
+
     @property
     def device(self):
         """A reference to the global wgpu device."""
@@ -808,6 +810,12 @@
         adds picking info and then dispatches the event in the Pygfx event system.
         """
         event_type = event["event_type"]
+
+        if EVENT_TYPE_MAP[event_type] is PointerEvent:
+            for filter in self._event_filters.values():
+                if filter[0, 0] < event["x"] < filter[1, 0] and filter[0, 1] < event["y"] < filter[1, 1]:
+                    return
+
         target = None
         if "x" in event and "y" in event:
             info = self.get_pick_info((event["x"], event["y"]))
@@ -819,6 +827,10 @@
         )
         self.dispatch_event(ev)
 
+    @property
+    def event_filters(self) -> dict:
+        return self._event_filters
+
 
 EVENT_TYPE_MAP = {
     "resize": WindowEvent,
```

results in desired behavior if we set the bbox in the imgui update_gui() loop:

```python
    imgui.begin("window", None)
    # get bbox of imgui window
    x1, y1 = imgui.get_window_pos()
    width, height = imgui.get_window_size()

    x2, y2 = x1 + width, y1 + height

    # set bbox of filter
    renderer.event_filters["scatter_size_gui"][:] = [x1 - 1, y1 - 1], [x2 + 4, y2 + 4]
    ...
```

https://github.com/user-attachments/assets/4d41feac-d0e0-41cb-a336-7445b6f76d7a

I haven't yet thought of keyboard input such as text entry. And I wanted to get your thoughts on whether this is a good idea and reasonable way to do this before making a PR on something as fundamental as the `WgpuRenderer` :) .
Some things I thought of: Are there more general use cases than just imgui? Is there a better way to do this? Should this instead be done at the level of the `WgpuCanvas` and not the pygfx renderer?

**Comment by Korijn** [comment]
This scenario relates to #495 

I think the important thing for me is that pygfx is a rendering library, not a gui framework. It feels like feature creep.

We can have all the gui stuff, but let's ensure it's cleanly separated from the core. See #495

**Comment by kushalkolar** [comment]
Thanks! I read through that again, I didn't really grasp it back then but I do now :smile: . Separating rendering and events as you mentioned will make this easier :rocket:

**Comment by almarklein** [comment]
I think what's needed instead is a way to stop propagation. We have this in pygfx, but not at the wgpu level. That way the imgui logic can capture events and prevent them from ending up in the ~renderer~ the object that will handle events in pygfx (probably the viewport).

**Comment by almarklein** [comment]
We can make this part of the jupyter_rfb event spec.

**Comment by kushalkolar** [comment]
Thanks for the ideas! I'm happy to wait until the viewport refactor, we'll use a subclassed renderer in the meantime.

**Comment by Korijn** [comment]
> We can make this part of the jupyter_rfb event spec.

We could make it a separate library even. The pygfx portion is a reimplementation of the browser event API.

**Comment by almarklein** [comment]
In any case, I think it would be good to use the same system in wgpu as in pygfx. I like the idea to just keep using simple dicts. But something that looks like the browser event objects could also be nice.

**Comment by Korijn** [comment]
I see. I like that, dicts are also much more efficient in python. So we just describe the required behavior and associated attributes in the spec then, correct?

**Comment by almarklein** [comment]
Yes, we can e.g. specify that when the dict has `stop_propagation` set to True, the dispatcher will not dispatch to other handlers. Dicts may feel a bit low level, but its light and very transparent.
