### ISSUE TITLE
Can't set pick_write=True after first rendering pass

### ISSUE THREAD

**Issue by schlegelp** [pygfx/pygfx#840]
Hi! This is related to issue #720 and PR #722 which made `pick_write` dynamic. 

In my use case, changing `pick_write` dynamically works like a charm as long as the material is initialised with `pick_write=True`, i.e. I can repeatedly toggle between `True` and `False` to determine whether the object should be pickable. However, when a material starts off with `pick_write=False`, setting it to `pick_write=True` afterwards doesn't have any effect.

While putting together a stand-alone reproducer, I realised that this issue only appears when trying to set `pick_write=True` after the first rendering pass. For background: I'm running my app interactively (i.e. non-blocking) from an ipython session and I was trying set `pick_write=True` while working with the scene.

```python
import pygfx as gfx
from wgpu.gui.auto import WgpuCanvas, run

canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

cube = gfx.Mesh(
    gfx.box_geometry(200, 200, 200),
    gfx.MeshBasicMaterial(pick_write=False),  # <- initialize with pick_write=False
)
scene.add(cube)

def on_hover(event):
   print("Hovering over object:", event.pick_info["world_object"])

scene.add_event_handler(on_hover, "pointer_move")

camera = gfx.PerspectiveCamera(70, 16 / 9)
camera.show_object(scene)

controller = gfx.TrackballController(camera, register_events=renderer)

def animate():    
    renderer.render(scene, camera)    
    canvas.request_draw()
    cube.material.pick_write = True  # <- setting pick_write=True after the first renderer.render() has no effect
    
if __name__ == "__main__":    
    canvas.request_draw(animate)
    run()
```

Thanks!

**Comment by hmaarrfk** [comment]
out of curiousity, if you add a second pickable object does it also happen?

**Comment by schlegelp** [comment]
> out of curiousity, if you add a second pickable object does it also happen?

Yes, the number of object doesn't seem to matter.

**Comment by hmaarrfk** [comment]
Its strange because the attachments are being regenerated.

**Comment by hmaarrfk** [comment]
I looked into this and I think I know why it doesn't change under the hood

This line does not get re-triggered
https://github.com/pygfx/pygfx/blob/8661e8f69037c0480da72c983038e4553b4362ca/pygfx/renderers/wgpu/engine/pipeline.py#L589

Ultimately, the "shader" gets created two different ways, one way with the picking code, the other without. And it isn't being recreated when the material property changes.

I don't really know how to solve it the right way.

I know that if I change this line:
https://github.com/pygfx/pygfx/blob/8661e8f69037c0480da72c983038e4553b4362ca/pygfx/renderers/wgpu/engine/pipeline.py#L183
to
```
        if "create" in changed or "reset" in changed:
```

it works.

I know a few might be on vacation with limited time right now.
