### ISSUE TITLE
Frame counter, time and best practices

### ISSUE THREAD

**Issue by hmaarrfk** [pygfx/pygfx#844]
Almar said that the main goal was to get the architectural principles of PyGFX down before version "1".

One challenge I've faced is with time.

It would be convenient for us to access to the concept of "time" so that we may control certain animations.

However, I'm unsure how to add this time to the global state. Integers? Floating point?

We are looking something with "60 fps" granularity, and it seems that if you have a single floating point counter that it would start to accumulate increasing error as time passed. That isn't really nice when you have animations that require "subsecond" accuracy for computing the "phase" of some object.

It would be nice if it were in some shared state dictionary (i remember I found it a while back).

I will say that we do use a hack with our system where we render the same scene multiple times to create a really large image. so it would be nice to be able to "pause" time sometimes ;)

**Comment by almarklein** [comment]
This is a good point. We've already thought about this as part of #495. I can recommend this post about this topic: http://gameprogrammingpatterns.com/game-loop.html

One thing we want to do is decouple rendering from updating animations, so that animations can be updated with a fixed time interval, even when the fps varies.

**Comment by hmaarrfk** [comment]
In terms of additions to #495 it might to add the variables to the `stdinfo` uniform buffer

https://github.com/pygfx/pygfx/blob/367e02888adea122a78915bdf32085ed7d07830a/pygfx/renderers/wgpu/engine/shared.py#L21

so they can be accessible by shaders ^_^
