### ISSUE TITLE
IO (e.g. glTF)

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#85]

**Comment by Korijn** [comment]
I just stumbled on this link, sharing it here so we can reference it later:

https://github.com/KhronosGroup/glTF-Sample-Models

In particular it's got the Sponza scene which is a pretty great testbed for any engine:

![image](https://user-images.githubusercontent.com/1882046/158356088-f4cea0c3-7a4a-4202-9607-1ad69636fcb5.png)

**Comment by almarklein** [comment]
Also look at [Pyrender](https://github.com/mmatl/pyrender) for gltf support (it uses trimesh extensively).

**Comment by Korijn** [comment]
I propose to close this one as #349 improved supported formats greatly.
