### ISSUE TITLE
another imgui example

### ISSUE THREAD

**Issue by Choons** [pygfx/pygfx#864]
Hi, I am trying to figure out how to use imgui for UI in pygfx. The morph_facecap example is the only one I've found that uses imgui, but the sliders are driven by animation data from a file in a loop instead of a typical user input situation. I'd appreciate a simple imgui example that shows how to use a few simple things like a button, slider, and maybe text input where the user triggers them with mouse/keyboard input. Thanks for pygfx! it's an amazing library.

**Comment by kushalkolar** [comment]
There are a few examples in the wgpu repo.
https://github.com/pygfx/wgpu-py/tree/main/examples

You the pygfx renderer can render to the canvas and then the imgui renderer
can render to the same canvas.

**Comment by Choons** [comment]
perfect! thanks so much
