### ISSUE TITLE
RuntimeError: Request device failed (1): Validation Error

### ISSUE THREAD

**Issue by asmith26** [pygfx/pygfx#865]
Hi there,

I'm trying to run the [example in the README](https://github.com/pygfx/pygfx?tab=readme-ov-file#usage-example), unfortunately it doesn't seem to be working?

```python
$ python example.py 

MESA-INTEL: warning: Haswell Vulkan support is incomplete
Adapter is not Vulkan compliant, hiding adapter: Intel(R) HD Graphics 4600 (HSW GT2)
Traceback (most recent call last):
  File "./example.py", line 15, in <module>
    gfx.show(cube, before_render=animate)
  File "./.venv/lib/python3.12/site-packages/pygfx/utils/show.py", line 271, in show
    ).show(object, up)
      ^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/pygfx/utils/show.py", line 168, in show
    self.renderer = WgpuRenderer(self.canvas)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/pygfx/renderers/wgpu/engine/renderer.py", line 142, in __init__
    self._shared = get_shared()
                   ^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/pygfx/renderers/wgpu/engine/shared.py", line 270, in get_shared
    Shared()
  File "./.venv/lib/python3.12/site-packages/pygfx/renderers/wgpu/engine/shared.py", line 85, in __init__
    self._device = self.adapter.request_device(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 833, in request_device
    return self._request_device(
           ^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 1001, in _request_device
    raise RuntimeError(error_msg)
RuntimeError: Request device failed (1): Validation Error

Caused by:
  Unsupported features were requested: Features(FLOAT32_FILTERABLE)
```

Thanks for any help!

**Comment by almarklein** [comment]
This looks like the Vulkan driver is not complete. In particular, it says the `FLOAT32_FILTERABLE` feature is not available, which is something we assumed to be available on all (somewhat modern) desktops. 

Is this on Linux? Could you try updating the Vulkan driver with `apt install mesa-vulkan-drivers`?

**Comment by asmith26** [comment]
Thanks for your help @almarklein. Yep I'm on Ubuntu Linux. I just ran `sudo apt install mesa-vulkan-drivers`, but unfortunately just get the same error.

**Comment by hmaarrfk** [comment]
> Thanks for your help @almarklein. Yep I'm on Ubuntu Linux. I just ran sudo apt install mesa-vulkan-drivers, but unfortunately just get the same error.

can you be more specific about the version of Ubuntu you are using and the hardware you are using?

I use ubuntu a lot and have gotten Pygfx working on Ubuntu 20.04 through 24.10 with a variety of hardware.

**Comment by asmith26** [comment]
Thanks for your help and info @hmaarrfk
- Ubuntu 24.04 noble
- Not sure if this is helpful:
```bash
$ lspci | grep VGA

00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
```

**Comment by hmaarrfk** [comment]
I should have also read the first line:

> Haswell Vulkan support is incomplete

From what I can tell these errors are coming from Vulkan itself, and not pygfx.

4th gen is quite old. I've only tested as far back as 8th gen.....

Infact, they are telling you that for a variety of reasons, Haswell was not targetted for Vulkan. 

I'm sorry to say but your computer might simply be incompatible with Vulkan.

**Comment by asmith26** [comment]
Thanks again for your help @hmaarrfk. Interestingly I can seem to run the triangle example from `wgpu-py` https://github.com/pygfx/wgpu-py/blob/6bb8bf6497a4dd4624f55f7b2263d9b8a5cceb30/examples/triangle.py

```bash
$ python triangle.py      

# I do seem to get some warnings:

MESA-INTEL: warning: Haswell Vulkan support is incomplete
Adapter is not Vulkan compliant, hiding adapter: Intel(R) HD Graphics 4600 (HSW GT2)
```

![image](https://github.com/user-attachments/assets/d0012581-6ecb-4a22-a4d9-fde99eb67d23)

**Comment by asmith26** [comment]
Thanks for the suggestion and help @almarklein. 

I've figured it out: to run the `wgpu-py` example I needed to follow https://github.com/pygfx/wgpu-py/issues/616#issuecomment-2409817327 and install that from main `pip install git+https://github.com/pygfx/wgpu-py.git`.

All working now, many thanks for both your help again!

**Comment by asmith26** [comment]
Here is the requested output:

```python
>>> print(wgpu.gpu.request_adapter_sync().info)

MESA-INTEL: warning: Haswell Vulkan support is incomplete
Adapter is not Vulkan compliant, hiding adapter: Intel(R) HD Graphics 4600 (HSW GT2)
{'vendor': '', 'architecture': '', 'device': 'Mesa Intel(R) HD Graphics 4600 (HSW GT2)', 'description': '4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.2', 'vendor_id': 32902, 'device_id': 0, 'adapter_type': 'IntegratedGPU', 'backend_type': 'OpenGL'}
```

**Comment by almarklein** [comment]
> ... 'backend_type': 'OpenGL'}

Right, the Vulkan backend is rejected, so it falls back to the OpenGL backend.

**Comment by almarklein** [comment]
Short story is what Mark said; your machine is too old to run Pygfx. The float32 feature that prevents the device from being created, is needed for some functionality in pygfx. In theory we can make it optional, but it would make the code more complicated as we'd have to take into account that the feature may not be available.

That said, as an exercise we can try to see how far your machine can go ...

You could try running pygfx from source and modify this line so `_features` is an empty set:
https://github.com/pygfx/pygfx/blob/a3f8723c4d1d4af0943566c8a0ce01feba9ad317/pygfx/renderers/wgpu/engine/shared.py#L52

That will likely make it possible to run some examples. If this proofs good enough for your use-case, I am open to making it possible to disable that feature.

**Comment by asmith26** [comment]
`_features = set()` works thanks!

![image](https://github.com/user-attachments/assets/4ab387df-1812-4359-a285-6dec1772a8dc)

**Comment by almarklein** [comment]
Hehe, that's actually pretty cool. Ok, I had a brief look, and I think we can support this with minimal effort. #868

**Comment by asmith26** [comment]
Hi again :)

Just thought I'd mention that I seem to be getting a similar error when running the [example in the README](https://github.com/pygfx/pygfx?tab=readme-ov-file#usage-example):

```python
$ uvx --with pygfx,glfw python example_readme.py

Unable to find extension: VK_EXT_physical_device_drm
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Adapter is not Vulkan compliant, hiding adapter: Intel(R) HD Graphics 4600 (HSW GT2)
Traceback (most recent call last):
  File "example_readme.py", line 15, in <module>
    gfx.show(cube, before_render=animate)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/pygfx/utils/show.py", line 268, in show
    ).show(object, up)
      ~~~~^^^^^^^^^^^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/pygfx/utils/show.py", line 168, in show
    self.renderer = WgpuRenderer(self.canvas)
                    ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/pygfx/renderers/wgpu/engine/renderer.py", line 268, in __init__
    self._shared = get_shared()
                   ~~~~~~~~~~^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/pygfx/renderers/wgpu/engine/shared.py", line 311, in get_shared
    Shared()
    ~~~~~~^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/pygfx/renderers/wgpu/engine/shared.py", line 87, in __init__
    self._device = self.adapter.request_device_sync(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        required_features=list(Shared._features), required_limits=Shared._limits
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/wgpu/backends/wgpu_native/_api.py", line 1077, in request_device_sync
    return awaitable.sync_wait()
           ~~~~~~~~~~~~~~~~~~~^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 299, in sync_wait
    return self._finish()
           ~~~~~~~~~~~~^^
  File "~/.cache/uv/archive-v0/4frnPMiQxSsSXCrXOqYXP/lib/python3.13/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 275, in _finish
    raise RuntimeError(error)
RuntimeError: Request device failed (3): Validation Error

Caused by:
  Unsupported features were requested: Features { features_wgpu: FeaturesWGPU(0x0), features_webgpu: FeaturesWebGPU(FLOAT32_FILTERABLE) }:
```

Not sure if you're able to help me fix this? Thanks for any help!

**Comment by Korijn** [comment]
The error message is telling: `Adapter is not Vulkan compliant, hiding adapter: Intel(R) HD Graphics 4600 (HSW GT2)` that's bad news. It means your graphics card is not Vulkan compliant.

Looks like you need to update your graphics drivers.

If that doesn't help your graphics card is not supported. In that case we can see if we can make pygfx work without the GPU feature float32_filterable. But please let us know how you fare after updating your drivers.

**Comment by asmith26** [comment]
Thanks for your help @Korijn. I've just tried running the following (not sure if this is what you mean?):

```bash
$ sudo apt install mesa-vulkan-drivers

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mesa-vulkan-drivers is already the newest version (25.0.7-0ubuntu0.24.04.2).
0 to upgrade, 0 to newly install, 0 to remove and 4 not to upgrade
```

**Comment by Korijn** [comment]
Well, we are kind of repeating what's already been said above. The conclusion can be found in this reply: https://github.com/pygfx/pygfx/issues/865#issuecomment-2416816381
