### ISSUE TITLE
Shader templating

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#87]
If PyShader gets some more functionality for this, we can make the code of our renderers cleaner and easier to maintain and scale.

**Comment by almarklein** [comment]
With WGSL we'd opt for more text-based templating, perhaps just use jinja2.

**Comment by Korijn** [comment]
I'm all for jinja2, it's just easier to maintain since everyone knows how it works and there's good documentation available.

**Comment by almarklein** [comment]
I totally agree. I just hope it covers the type of templating that we need, since it was made for web-stuff, not shaders :)

**Comment by Korijn** [comment]
It's also used in many gitops projects to generate YAML (e.g. Kubernetes+Helm is a very big consumer of Jinja2).

**Comment by Korijn** [comment]
Closed in #97 and #98
