### ISSUE TITLE
does pygfx have fog?

### ISSUE THREAD

**Issue by Choons** [pygfx/pygfx#875]
Hi, I am coming to pygfx from threejs and can't find any fog functionality. Does pygfx have it, or maybe through wgpu? Thanks for any help.

**Comment by almarklein** [comment]
Not yet, keep an eye out on #72. The work in #492 will be needed first, so we have access to the depth buffer in post-processing steps.

**Comment by almarklein** [comment]
Closing, as this is basically a duplicate of #72.
