### ISSUE TITLE
Get coordinate frame right

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#99]
Check + fix + document the coordinate frame definitions. In other words, make sure that up is up.

E.g.:
* I've read that depending on whether you're submitting wgsl or spirv, the NDC might be different.
* The different volume slice examples don't all look/scroll the same. Fix this and understand how.
* Image examples?

**Comment by Korijn** [comment]
NDC is determined by the underlying API so I would expect wgpu to normalize that, but I guess it's... the shading language used? That's surprising.

**Comment by almarklein** [comment]
In the [Naga chat](https://matrix.to/#/!fjjkgHFcwtkREywzfk:matrix.org/$mTf810siPK7BjgCCx5RQpiNfJbvAxprCPZAeMeX5Bo0?via=matrix.org&via=mozilla.org&via=kng.re):

> when you use standalone Naga, it assumes you want the coordinate space "native" to the format. I.e. SPIR-V would be Y-flipped comparing to WGSL, aimed at feeding to Vulkan Naga has options for this in both SPV-in and SPV-out, but the converter binary doesn't have command line atm to switch these options so you produced a SPIR-V module for Vulkan, basically, and then fed it back to wgpu, which expects SPIR-V for WebGPU

So it depend on how you compile your Spirv. Not sure if what we did with PyShader equals how wgsl works.

**Comment by Korijn** [comment]
I added up the axes helper (with an example) to help visualize coordinate frames by the way.

**Comment by Korijn** [comment]
Oh and the grid helper too!
